//! PB-DX39 (`OOS-DX5-3`, `OOS-DX5-7`): gates for the ONE source-relative arithmetic and
//! for the last-known-information store that feeds it.
//!
//! ## What the batch did, in one paragraph
//!
//! `rules::layers::effect_applies_to` has 37 `EffectFilter` arms, of which **20 are
//! source-relative**: they need the effect's SOURCE object's `controller`, `attached_to`,
//! `chosen_creature_type` or `chosen_color`. Each of the 20 re-read
//! `state.objects.get(&source_id)` for itself and answered `false` when that returned
//! `None` — so once the source left the battlefield (CR 400.7 retires its id), every one of
//! them matched nothing. For a **resolution-generated** effect that is CR-wrong: CR 608.2h
//! says the effect *"uses the object's last known information"* once the source *"is no
//! longer in [the] zone [it was expected to be in]"*, and CR 113.7a says the ability
//! *"exists on the stack independently of its source"*. Two deck-legal subjects were live-
//! wrong: Umezawa's Jitte's `+2/+2` mode (destroy the Jitte in response and the bonus went
//! nowhere) and Mardu Ascendancy's `+0/+3` (a `Cost::SacrificeSelf` ability, so its source
//! is ALWAYS gone at resolution — wrong in every game).
//!
//! Twenty reads became **two constructors** consumed by one threaded parameter.
//!
//! ## The scoping is the design, not caution
//!
//! There are two constructors and they carry two different CR justifications:
//!
//! * `source_view_at_resolution` — live first, **then LKI**. CR 608.2h / CR 113.7a. Called
//!   from `snapshot_affected_set` and nowhere else, because that is the CR 611.2c
//!   determination for an effect generated by the RESOLUTION of a spell or ability.
//! * `source_view_live` — live only, **no LKI fallback**. CR 611.3a: a static ability's
//!   effect *"isn't 'locked in'"* and exists only while the ability does, which means only
//!   while the object does. An LKI fallback there would make a departed permanent's static
//!   ability run for the rest of the game.
//!
//! `is_effect_active`'s `EffectDuration::WhileSourceOnBattlefield` arm already refuses the
//! common case, but it does not cover every duration a static registration can carry:
//! `rules/replacement.rs` and the `StackObjectKind::ClassLevelAbility` arm of
//! `rules/resolution.rs` both forward a card def's own duration verbatim, and
//! `Effect::CreateEmblem`'s static loop uses `EffectDuration::Indefinite`. `r7` measures
//! how much of that hypothetical the corpus actually contains, and ratchets it, because a
//! **zero measured** is worth more than a risk argued.
//!
//! ## Rows
//!
//! * **`r1`** — the mechanism gate the acceptance criterion asks for: no arm of
//!   `effect_applies_to_inner` may read the source directly again. Two independent axes
//!   (`OOS-DX36-8`: a survivor scan has a SHAPE axis and a SPELLING axis, and varying one
//!   while holding the other is half a check).
//! * **`r2`** — the 20 source-relative arms, pinned by NAME SET and not by count. A count
//!   assertion passes when one member leaves and another joins.
//! * **`r3`** — the SR-24 successor. That gate's own comment said *"Adding a NEW READER
//!   that consults a fifth snapshot keyword is NOT machine-caught"*. It is now: every
//!   reader of `lki_objects` / `lki_object_snapshot` in the whole workspace is pinned.
//! * **`r4`** — `is_effect_active`'s two source reads stay LIVE-ONLY, so a later batch
//!   cannot "finish the job" and make a departed source's static ability immortal.
//! * **`r5`** — `source_view_at_resolution` has exactly ONE caller and it is
//!   `snapshot_affected_set`. Without this, "the fallback is locked-path only" is a
//!   comment, and this batch's whole subject is that a comment is a claim.
//! * **`r6`** — the capture/clear coupling: everything
//!   `GameState::is_source_of_a_pending_ability` captures FOR is something
//!   `maybe_clear_lki_objects` waits ON, so a snapshot lives exactly as long as the ability
//!   that needs it.
//! * **`r7`** — the corpus census the scoping rests on, ratcheted.
//! * **`t_census_report`** — PRINTS every population above under `--nocapture`. PB-DX8's
//!   rule: a figure that no test prints is a figure that was transcribed.
//!
//! ## Why the walks are walks
//!
//! `r3` and `r5` walk **every `<crate>/src` and `<tool>/src` in the workspace**, reusing
//! `pb_dx49_saga_blanking_roster::workspace_src_files_checked`. PB-DX48's `SITE_SRCS` named
//! six `rules/` files while the function it policed was `pub(crate)` and was defeated by a
//! consumer one crate over; PB-DX49's own first draft walked one crate and was defeated the
//! same way. `r7` walks `all_cards()`, never card source (SR-36).

use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

use mtg_engine::{all_cards, AbilityDefinition, CardDefinition};
use serde_json::Value;

use crate::pb_dx49_saga_blanking_roster::{strip_comments, workspace_src_files_checked};

// ─────────────────────────────────────────────────────────────────────────────
// Shared source access
// ─────────────────────────────────────────────────────────────────────────────

fn workspace_root() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    // crates/engine -> crates -> workspace root
    p.pop();
    p.pop();
    p
}

fn read_engine_file(rel: &str) -> String {
    let path = workspace_root().join(rel);
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

/// `src` with every comment replaced by spaces and then **all whitespace removed**.
///
/// Two properties this buys, both of them the point:
/// * multi-line tolerance — `state\n    .objects\n    .get(&source_id)` squeezes to exactly
///   the same bytes as the one-line spelling. Three of the twenty arms (`AttachedCreature`,
///   `AttachedLand`, `AttachedPermanent`) spelled the read across line breaks at HEAD, which
///   is `OOS-DX50`'s multi-line lesson and is why the task brief's census of "17 occurrences"
///   was a floor and the truth was 20.
/// * receiver-agnosticism — a `use` alias or a differently-named binding
///   (`st.objects.get(&source_id)`) still contains `.objects.get(&source_id)`.
fn squeeze(src: &str) -> String {
    strip_comments(src)
        .chars()
        .filter(|c| !c.is_whitespace())
        .collect()
}

/// `strip_comments`, then every `"..."` string literal blanked.
///
/// Necessary rather than fastidious: `state/diagnostics.rs`'s SR-23 `debug_assert!`
/// messages *quote* `GameState::lki_object_snapshot` to point an author at the right
/// vocabulary. A walk that counts those as readers is counting guidance prose, which is
/// `OOS-CARDS2-7` / `OOS-DX47-2`'s shape one layer over.
fn strip_comments_and_strings(src: &str) -> String {
    let stripped = strip_comments(src);
    let b = stripped.as_bytes();
    let mut out = String::with_capacity(stripped.len());
    let mut i = 0usize;
    while i < b.len() {
        if b[i] == b'"' {
            out.push(' ');
            i += 1;
            while i < b.len() && b[i] != b'"' {
                if b[i] == b'\\' {
                    out.push(' ');
                    i += 1;
                }
                out.push(if b[i] == b'\n' { '\n' } else { ' ' });
                i += 1;
            }
            if i < b.len() {
                out.push(' ');
                i += 1;
            }
        } else {
            let ch = stripped[i..].chars().next().expect("char boundary");
            out.push_str(&stripped[i..i + ch.len_utf8()]);
            i += ch.len_utf8();
        }
    }
    out
}

/// [`strip_comments_and_strings`], with every `#[cfg(test)] mod ... { .. }` body blanked.
///
/// The site rosters below are about **production** readers. An in-source unit module that
/// drives a departure and then asserts on `lki_object_snapshot` is doing exactly what a
/// test should do, and making every such probe redden a roster would train the next author
/// to stop writing them.
fn production_source(src: &str) -> String {
    let mut out = strip_comments_and_strings(src);
    while let Some(at) = out.find("#[cfg(test)]") {
        let Some(rel) = out[at..].find('{') else {
            break;
        };
        let open = at + rel;
        let Some(end) = matching_brace(&out, open) else {
            break;
        };
        let blanked: String = out[at..=end]
            .chars()
            .map(|c| if c == '\n' { '\n' } else { ' ' })
            .collect();
        out.replace_range(at..=end, &blanked);
    }
    out
}

/// The offset of the `}` matching the `{` at `open`. `None` on unbalanced input, so every
/// caller fails **closed** rather than falling back to a byte window (`OOS-DX49-2`).
fn matching_brace(src: &str, open: usize) -> Option<usize> {
    let b = src.as_bytes();
    if b.get(open) != Some(&b'{') {
        return None;
    }
    let mut depth = 0usize;
    let mut i = open;
    while i < b.len() {
        match b[i] {
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return Some(i);
                }
            }
            b'"' => {
                i += 1;
                while i < b.len() && b[i] != b'"' {
                    if b[i] == b'\\' {
                        i += 1;
                    }
                    i += 1;
                }
            }
            _ => {}
        }
        i += 1;
    }
    None
}

/// The comment-stripped body of the named free function in the given engine file,
/// brace-matched. Fails closed.
fn fn_body(rel: &str, name: &str) -> String {
    let src = strip_comments(&read_engine_file(rel));
    let needle = format!("fn {name}(");
    let at = src
        .find(&needle)
        .unwrap_or_else(|| panic!("PB-DX39: `{needle}` not found in {rel} -- renamed?"));
    let open = src[at..]
        .find('{')
        .map(|o| at + o)
        .unwrap_or_else(|| panic!("PB-DX39: no body brace for `{name}` in {rel}"));
    let end = matching_brace(&src, open)
        .unwrap_or_else(|| panic!("PB-DX39: could not brace-match `{name}` in {rel}"));
    src[open..=end].to_string()
}

/// The enclosing function's name for byte offset `at`: the last `fn <name>` at or before
/// `at`. Used by the workspace walks so a site is attributed, not merely counted.
fn enclosing_fn_name(src: &str, at: usize) -> String {
    let head = &src[..at];
    // A site that IS a definition (`fn source_view_at_resolution(`) has `fn ` immediately
    // before it, so the generic rule below would attribute it to the empty string. Name it
    // after itself instead, so a definition and its callers are distinguishable rows.
    if head.ends_with("fn ") {
        return src[at..]
            .chars()
            .take_while(|c| c.is_alphanumeric() || *c == '_')
            .collect();
    }
    match head.rfind("fn ") {
        Some(i) => head[i + 3..]
            .chars()
            .take_while(|c| c.is_alphanumeric() || *c == '_')
            .collect(),
        None => "<top-level>".to_string(),
    }
}

const LAYERS_RS: &str = "crates/engine/src/rules/layers.rs";

// ─────────────────────────────────────────────────────────────────────────────
// Arm splitting
// ─────────────────────────────────────────────────────────────────────────────

/// One `EffectFilter::X => ...` arm of `effect_applies_to_inner`'s `match &effect.filter`.
struct Arm {
    name: String,
    /// The arm's text, comment-stripped and whitespace-removed.
    squeezed: String,
}

/// Split `effect_applies_to_inner`'s filter match into arms.
///
/// Depth-tracked rather than indentation-tracked: an arm pattern begins at a
/// `EffectFilter::` that sits at brace/paren depth 0 relative to the match body, which is
/// true regardless of how rustfmt has wrapped the file.
fn filter_arms() -> Vec<Arm> {
    let body = fn_body(LAYERS_RS, "effect_applies_to_inner");
    let mat = body
        .find("match &effect.filter")
        .expect("PB-DX39: `match &effect.filter` not found in effect_applies_to_inner");
    let open = body[mat..]
        .find('{')
        .map(|o| mat + o)
        .expect("PB-DX39: no brace after `match &effect.filter`");
    let end = matching_brace(&body, open).expect("PB-DX39: could not brace-match the filter match");
    let inner = &body[open + 1..end];

    let b = inner.as_bytes();
    let mut depth = 0i32;
    let mut starts: Vec<(usize, String)> = Vec::new();
    let mut i = 0usize;
    while i < b.len() {
        match b[i] {
            b'{' | b'(' | b'[' => depth += 1,
            b'}' | b')' | b']' => depth -= 1,
            b'"' => {
                i += 1;
                while i < b.len() && b[i] != b'"' {
                    if b[i] == b'\\' {
                        i += 1;
                    }
                    i += 1;
                }
            }
            _ => {}
        }
        if depth == 0 && inner[i..].starts_with("EffectFilter::") {
            let name: String = inner[i + "EffectFilter::".len()..]
                .chars()
                .take_while(|c| c.is_alphanumeric() || *c == '_')
                .collect();
            starts.push((i, name));
        }
        i += 1;
    }
    let mut arms = Vec::new();
    for (idx, (at, name)) in starts.iter().enumerate() {
        let stop = starts.get(idx + 1).map(|(s, _)| *s).unwrap_or(inner.len());
        arms.push(Arm {
            name: name.clone(),
            squeezed: inner[*at..stop]
                .chars()
                .filter(|c| !c.is_whitespace())
                .collect(),
        });
    }
    // Non-vacuity floor: the splitter must actually find the match's arms. A parser that
    // returned `[]` would satisfy every `!contains` assertion below while measuring nothing.
    assert!(
        arms.len() >= 30,
        "PB-DX39: the arm splitter found only {} arms in effect_applies_to_inner (37 at \
         HEAD). The parser has broken and every gate built on it is vacuous; arms: {:?}",
        arms.len(),
        arms.iter().map(|a| &a.name).collect::<Vec<_>>()
    );
    arms
}

/// The arms that consume the caller-supplied source view. Derived from source, never
/// hand-listed, so `r2`'s pin and `r7`'s corpus census cannot drift apart.
fn source_relative_arm_names() -> BTreeSet<String> {
    filter_arms()
        .into_iter()
        .filter(|a| a.squeezed.contains("letSome(src)=source"))
        .map(|a| a.name)
        .collect()
}

/// Every source-relative arm at HEAD, in the order they appear in `effect_applies_to_inner`.
///
/// **Pinned by NAME SET, not by count** — a count assertion is satisfied when one member
/// leaves and another joins on the same commit. The task brief's own census said "17
/// occurrences"; the truth is 20, because three of them spell the read across a line break.
const SOURCE_RELATIVE_ARMS: &[&str] = &[
    "AttachedCreature",
    "AttachedLand",
    "AttachedPermanent",
    "CreaturesYouControl",
    "OtherCreaturesYouControl",
    "OtherCreaturesYouControlWithSubtype",
    "CreaturesOpponentsControl",
    "CreaturesYouControlWithSubtype",
    "AttackingCreaturesYouControl",
    "ArtifactsYouControl",
    "CreaturesYouControlWithSupertype",
    "CreaturesYouControlWithColor",
    "OtherCreaturesYouControlExcludingSubtype",
    "CreaturesYouControlExcludingSubtype",
    "AttackingCreaturesYouControlWithSubtype",
    "OtherCreaturesYouControlWithSubtypes",
    "LandsYouControl",
    "CreaturesYouControlOfChosenType",
    "CreaturesYouControlOfChosenColor",
    "OtherCreaturesYouControlOfChosenType",
];

// ─────────────────────────────────────────────────────────────────────────────
// r1 — the mechanism gate
// ─────────────────────────────────────────────────────────────────────────────

/// Whitespace-free spellings of a direct source read. AXIS 1 (SPELLING).
///
/// Receiver-agnostic by construction: the needles start at the `.objects` / `.object(`
/// segment, so `state.objects.get(&source_id)`, `st.objects.get(&source_id)` and a
/// `use`-aliased receiver all match the same bytes.
const DIRECT_SOURCE_READ_NEEDLES: &[&str] = &[
    ".objects.get(&source_id)",
    ".objects.get(&sid)",
    ".objects.get(&src_id)",
    ".objects.get_mut(&source_id)",
    ".object(source_id)",
    ".expect_object(source_id)",
    ".fizzle_object(source_id)",
    "lki_object_snapshot(source_id)",
    "lki_object_snapshot(sid)",
    "source_view_live(",
    "source_view_at_resolution(",
];

/// AXIS 2 (SHAPE), deliberately a different matcher from axis 1: find every accessor call
/// in the arm and inspect its ARGUMENTS for a source-flavoured token, whatever the callee's
/// receiver or the argument's spelling.
///
/// Over-collects on purpose. Over-collection can only make `r1` redder.
fn accessor_calls_taking_a_source_argument(squeezed: &str) -> Vec<String> {
    const CALL_HEADS: &[&str] = &[".get(", ".get_mut(", ".object(", "snapshot(", "_object("];
    let mut hits = Vec::new();
    for head in CALL_HEADS {
        let mut from = 0usize;
        while let Some(rel) = squeezed[from..].find(head) {
            let at = from + rel;
            let arg_start = at + head.len();
            // Bound the argument list by its matching paren.
            let b = squeezed.as_bytes();
            let mut depth = 1i32;
            let mut j = arg_start;
            while j < b.len() && depth > 0 {
                match b[j] {
                    b'(' => depth += 1,
                    b')' => depth -= 1,
                    _ => {}
                }
                j += 1;
            }
            let args = &squeezed[arg_start..j.saturating_sub(1).max(arg_start)];
            if args.contains("source") || args.contains("sid") {
                hits.push(format!("{head}{args})"));
            }
            from = at + head.len();
        }
    }
    hits
}

/// AXIS 3 (MECHANISM). The ONE form in which a filter arm may legally name `effect`.
///
/// CR 613.1's "**other** creatures you control" wording needs the arm to know which object
/// IS the source, so that it can exclude it; that is a comparison of two `ObjectId`s and
/// never a read of the source's characteristics, which is why it is safe and why
/// `SourceView` does not carry it. Five arms use it verbatim at HEAD
/// (`OtherCreaturesYouControl`, `...WithSubtype`, `...ExcludingSubtype`, `...WithSubtypes`,
/// `...OfChosenType`) — the fix-cycle brief said four, and the truth is five.
///
/// Whitespace-squeezed, so a multi-line spelling of the same statement is the same bytes.
const ALLOWED_ARM_SOURCE_MENTIONS: &[&str] = &["ifeffect.source==Some(object_id){returnfalse;}"];

/// AXIS 3 (MECHANISM). Once the allowed form above is removed, an arm that still names any
/// of these has a handle on the source that did not come from the caller's `SourceView`.
///
/// `effect` is the load-bearing one and it is deliberately the WHOLE binding, not
/// `effect.source`: inside `effect_applies_to_inner` the only things in scope are `state`,
/// `effect`, `object_id`, `obj_zone`, `chars` and `source`, so `effect` is the *only* route
/// to the source id, whether the arm reads it inline, hands it to a local helper
/// (`per_arm_source_controller(state, effect)`) or hands it to one in another file. The
/// three `*id`/`sid` spellings cover the other route — a source id hoisted to a local above
/// the match and consumed by name in the arm.
const BANNED_ARM_TOKENS: &[&str] = &["effect", "source_id", "sid", "src_id", "lki"];

/// An arm's text with every [`ALLOWED_ARM_SOURCE_MENTIONS`] form deleted.
fn arm_text_minus_allowed_forms(squeezed: &str) -> String {
    let mut out = squeezed.to_string();
    for allowed in ALLOWED_ARM_SOURCE_MENTIONS {
        out = out.replace(allowed, "");
    }
    out
}

/// CR 608.2h / CR 113.7a. The acceptance criterion's mechanism gate: a new arm that
/// re-reads the source directly is RED.
///
/// **Three axes, and the third is the one that measures the mechanism.** `OOS-DX36-8`: a
/// survivor scan has a SHAPE axis and a SPELLING axis, and varying one while holding the
/// other is half a check. The first draft of this row had two axes that were *the same
/// idea* — axis 1 is a list of accessor-call spellings whose argument names the source, and
/// axis 2 parses accessor-call argument lists for a source-flavoured token. Neither can see
/// a read that is not an accessor call, and the `/review` proved it by execution: with
///
/// ```text
/// let Some((_, srcobj)) = state.objects.iter().find(|(oid, _)| Some(**oid) == effect.source)
/// ```
///
/// planted in `ArtifactsYouControl` — the exact pre-PB-DX39 defect, restored, and keeping
/// the `let Some(src) = source else` binding so `r2` stayed satisfied — **all twelve gates
/// and the whole engine + simulator suite stayed green.** A second plant, a
/// `fn per_arm_source_controller(state, effect)` helper doing the live read and called from
/// the arm, did the same. That matters concretely because only 2 of the 20 source-relative
/// arms have behavioural LKI probes; for the other 18 this row is the only thing there is.
///
/// Axis 3 is therefore keyed on the MECHANISM rather than on a spelling: an arm may not
/// hold a handle on the source at all, in any spelling, except the one comparison
/// [`ALLOWED_ARM_SOURCE_MENTIONS`] permits. It over-collects on purpose — over-collection
/// can only make `r1` redder — and axes 1 and 2 are kept as the narrower conjuncts they
/// always were, because axis 1 still catches `source_view_live(` being called from inside
/// an arm, which mentions no banned token at all.
#[test]
fn r1_no_filter_arm_reads_the_source_directly() {
    let arms = filter_arms();
    let mut violations: Vec<String> = Vec::new();
    for arm in &arms {
        for needle in DIRECT_SOURCE_READ_NEEDLES {
            if arm.squeezed.contains(needle) {
                violations.push(format!("{} :: axis-1 spelling `{needle}`", arm.name));
            }
        }
        for hit in accessor_calls_taking_a_source_argument(&arm.squeezed) {
            violations.push(format!("{} :: axis-2 shape `{hit}`", arm.name));
        }
        let residue = arm_text_minus_allowed_forms(&arm.squeezed);
        for token in BANNED_ARM_TOKENS {
            if residue.contains(token) {
                violations.push(format!(
                    "{} :: axis-3 mechanism `{token}` (arm residue after removing the \
                     allowed self-exclusion: {residue})",
                    arm.name
                ));
            }
        }
    }
    assert!(
        violations.is_empty(),
        "PB-DX39 r1: a filter arm of `effect_applies_to_inner` holds a handle on the \
         effect's SOURCE instead of consuming the `source: Option<&SourceView>` the caller \
         supplied. That is the defect this batch closed: twenty arms each had to be right \
         about CR 608.2h and none of them was. Consume `source`; if the arm needs a field \
         the view does not carry, add the field to `SourceView` so BOTH constructors \
         answer it. If you genuinely need a new `effect.source == Some(object_id)`-shaped \
         self-exclusion, it is already allowed verbatim; anything else is the regression. \
         Violations: {violations:#?}"
    );
    // Non-vacuity floors: every axis must be capable of firing at all, on the very read it
    // was written for. Axis 3's plant is the `/review`'s own, byte for byte.
    let planted = "EffectFilter::Planted=>{state.objects.get(&source_id).map(|s|s.controller)}";
    assert!(
        DIRECT_SOURCE_READ_NEEDLES
            .iter()
            .any(|n| planted.contains(n)),
        "PB-DX39 r1: axis 1 cannot see the very read it was written for"
    );
    assert!(
        !accessor_calls_taking_a_source_argument(planted).is_empty(),
        "PB-DX39 r1: axis 2 cannot see the very read it was written for"
    );
    let reviewers_plant = "EffectFilter::Planted=>{letSome((_,srcobj))=state.objects.iter()\
                           .find(|(oid,_)|Some(**oid)==effect.source)else{returnfalse;};}";
    let residue = arm_text_minus_allowed_forms(reviewers_plant);
    assert!(
        BANNED_ARM_TOKENS.iter().any(|t| residue.contains(t)),
        "PB-DX39 r1: axis 3 cannot see the `/review`'s map-iteration plant, which is the \
         read it was written for"
    );
    let helper_plant = "EffectFilter::Planted=>{per_arm_source_controller(state,effect)}";
    assert!(
        BANNED_ARM_TOKENS
            .iter()
            .any(|t| arm_text_minus_allowed_forms(helper_plant).contains(t)),
        "PB-DX39 r1: axis 3 cannot see the `/review`'s helper-function plant"
    );
    // And the allowed form must still be *allowed*, or axis 3 is a gate nobody can satisfy.
    assert!(
        BANNED_ARM_TOKENS
            .iter()
            .all(|t| !arm_text_minus_allowed_forms(ALLOWED_ARM_SOURCE_MENTIONS[0]).contains(t)),
        "PB-DX39 r1: the allowed self-exclusion form does not survive its own removal"
    );
}

/// `r1`'s axis-3 companion at FUNCTION scope: `rules/layers.rs` is the only file that may
/// name `effect.source`, and each function's occurrence COUNT is pinned.
///
/// Axis 3 bans the handle inside an arm. This row bans hoisting it just above the arms:
/// `let sid = effect.source;` at the top of `effect_applies_to_inner`, with the arms then
/// naming `sid`, is caught by axis 3 — but `let live = effect.source.and_then(|i|
/// state.objects.get(&i));` with the arms naming `live` is not, because `live` is not a
/// banned token and never could be enumerated. A per-function COUNT is what closes that,
/// and it is `OOS-DX49`'s lesson applied one file over: a SET of sites collapses an extra
/// occurrence inside an already-listed site, so the roster stores counts.
///
/// **PB-DX42b split `is_effect_active`'s single 2-occurrence entry into two 1-occurrence
/// entries.** The function used to carry both the CR 611.3b duration read and the CR 604.2
/// condition read in one body; PB-DX42b split it at that seam into
/// `is_effect_duration_active` and `is_effect_condition_satisfied`, and each now names
/// `effect.source` exactly once. `is_effect_active` itself is a three-line composition of
/// the two and no longer names `effect.source` at all, so it is correctly ABSENT from this
/// roster (re-derived by executing the census in `r1c`'s own algorithm, not assumed from
/// the split: total occurrences workspace-wide in this file is unmoved at 9).
const LAYERS_EFFECT_SOURCE_SITES: &[(&str, usize, &str)] = &[
    (
        "is_effect_duration_active",
        1,
        "CR 611.3b duration read. LIVE-ONLY -- see r4.",
    ),
    (
        "is_effect_condition_satisfied",
        1,
        "CR 604.2 condition read. LIVE-ONLY -- see r4.",
    ),
    (
        "effect_applies_to",
        1,
        "CR 611.3a: the LIVE path's single resolution, via `source_view_live`.",
    ),
    (
        "effect_applies_to_inner",
        5,
        "The five CR 613.1 `other ... you control` self-exclusions, which compare two \
         ObjectIds and read no characteristic. Allowed verbatim by r1 axis 3.",
    ),
    (
        "snapshot_affected_set",
        1,
        "CR 611.2c / CR 608.2h: the LOCKED path's single resolution, via \
         `source_view_at_resolution`, hoisted out of the candidate loop.",
    ),
];

#[test]
fn r1c_effect_source_is_named_only_where_the_roster_says() {
    let src = production_source(&read_engine_file(LAYERS_RS));
    let squeezed_all: String = src.chars().filter(|c| !c.is_whitespace()).collect();
    assert!(
        squeezed_all.contains("effect.source"),
        "PB-DX39 r1c: `effect.source` does not occur in layers.rs at all -- the whitespace \
         squeeze or the comment stripper has broken and this row is vacuous"
    );
    let mut live: BTreeMap<String, usize> = BTreeMap::new();
    let mut from = 0usize;
    while let Some(rel) = src[from..].find("effect") {
        let at = from + rel;
        // Squeeze forward from the hit so `effect\n        .source` counts as one site.
        let tail: String = src[at..]
            .chars()
            .filter(|c| !c.is_whitespace())
            .take("effect.source".len())
            .collect();
        if tail == "effect.source" {
            *live.entry(enclosing_fn_name(&src, at)).or_default() += 1;
        }
        from = at + "effect".len();
    }
    let pinned: BTreeMap<String, usize> = LAYERS_EFFECT_SOURCE_SITES
        .iter()
        .map(|(f, n, _)| (f.to_string(), *n))
        .collect();
    assert_eq!(
        live, pinned,
        "PB-DX39 r1c: the per-function census of `effect.source` in {LAYERS_RS} has moved. \
         `effect.source` is the ONLY route from a filter arm to the source object, so a new \
         function naming it -- or an extra occurrence inside a listed one -- is either a \
         new source-resolution site (which must be one of the two constructors, see r5) or \
         the per-arm read this batch deleted. live: {live:#?}; pinned: {pinned:#?}"
    );
}

/// `r1`'s companion: **no per-arm LKI fallback**, anywhere in `effect_applies_to_inner`.
///
/// The acceptance criterion asks for ONE shared arithmetic. Twenty arms each falling back
/// to `lki_object_snapshot` would satisfy "the Jitte works" and reproduce the shape the
/// batch exists to remove.
#[test]
fn r1b_the_filter_body_never_consults_the_lki_store() {
    let body = squeeze(&fn_body(LAYERS_RS, "effect_applies_to_inner"));
    assert!(
        body.len() > 4_000,
        "PB-DX39 r1b: the measured body is only {} bytes, too small to be \
         effect_applies_to_inner -- the brace bounding has broken and the assertion below \
         would pass vacuously",
        body.len()
    );
    for needle in ["lki_object_snapshot", ".lki_objects"] {
        assert!(
            !body.contains(needle),
            "PB-DX39 r1b: `effect_applies_to_inner` names `{needle}`. The LKI fallback lives \
             in `source_view_at_resolution` and is reached only through \
             `snapshot_affected_set` (CR 611.2c), so that CR 611.3a static abilities do NOT \
             get it -- see `r5`."
        );
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// r2 — the source-relative arm roster
// ─────────────────────────────────────────────────────────────────────────────

/// CR 604.2 / CR 301.5 / CR 205.3m: the twenty arms that need the source's own
/// characteristics, pinned by NAME SET.
#[test]
fn r2_source_relative_arms_are_pinned_by_name() {
    let live = source_relative_arm_names();
    let pinned: BTreeSet<String> = SOURCE_RELATIVE_ARMS.iter().map(|s| s.to_string()).collect();
    assert_eq!(
        live,
        pinned,
        "PB-DX39 r2: the set of `effect_applies_to_inner` arms consuming the shared \
         `SourceView` has changed. If a NEW arm is source-relative, add it here AND make \
         sure it consumes `source` (r1 enforces the second half). If an arm stopped \
         consuming it, that is either a deletion or a regression to a per-arm read. \
         live only: {:?}; pinned only: {:?}",
        live.difference(&pinned).collect::<Vec<_>>(),
        pinned.difference(&live).collect::<Vec<_>>()
    );
    assert_eq!(
        pinned.len(),
        20,
        "PB-DX39 r2: the pinned list is not 20 entries; the task brief's census said 17 and \
         was a FLOOR (three arms spell the read across a line break -- OOS-DX50)"
    );
}

/// Every source-relative arm must also be reachable as a `snapshot_affected_set` candidate,
/// or CR 608.2h can never be exercised for it: the locked set is built by
/// `candidate_ids_for_filter`, and a filter it classifies as yielding no candidates would
/// lock an empty set no matter how good the source view is.
#[test]
fn r2b_every_source_relative_arm_has_battlefield_candidates() {
    let src = strip_comments(&read_engine_file(LAYERS_RS));
    let at = src
        .find("fn candidate_ids_for_filter")
        .expect("PB-DX39 r2b: candidate_ids_for_filter not found");
    let open = src[at..].find('{').map(|o| at + o).expect("body brace");
    let end = matching_brace(&src, open).expect("brace match");
    let body: String = src[open..=end]
        .chars()
        .filter(|c| !c.is_whitespace())
        .collect();
    assert!(body.len() > 500, "PB-DX39 r2b: body too small; parse broke");
    for name in SOURCE_RELATIVE_ARMS {
        assert!(
            body.contains(&format!("EffectFilter::{name}")),
            "PB-DX39 r2b: `EffectFilter::{name}` is source-relative but is not classified in \
             `candidate_ids_for_filter`, so `snapshot_affected_set` would enumerate no \
             candidates for it and CR 608.2h could never apply."
        );
    }
}

/// CR 611.3a: `layers::filter_is_source_relative` — the classifier that makes the LIVE
/// path's source resolution LAZY — must agree exactly with the arms that consume the view.
///
/// The `/review`'s NIT was that `effect_applies_to` resolved `source_view_live` eagerly,
/// above both of `effect_applies_to_inner`'s short-circuits, adding an unconditional
/// `OrdMap::get` per (effect, object) on the layer walk for every LOCKED effect and every
/// non-source-relative arm. The fix skips the lookup for exactly those two populations —
/// which buys a NEW way to be wrong: a filter mis-classified `false` would receive `None`
/// and silently match nothing, i.e. the pre-PB-DX39 defect restored for one variant. The
/// classifier is exhaustive with no `_` arm so a new variant cannot join silently, and this
/// row is what stops an EXISTING variant being moved to the wrong side.
///
/// Both sides are derived from source: the classifier's `true` arms are parsed out of
/// `layers.rs`, and the consuming arms come from [`source_relative_arm_names`], which reads
/// the `let Some(src) = source` binding. Nothing here is hand-listed twice.
#[test]
fn r2c_the_laziness_classifier_matches_the_consuming_arms() {
    let body = squeeze(&fn_body(LAYERS_RS, "filter_is_source_relative"));
    // The `true` side is everything before `=>true,`; the `false` side follows it.
    let split = body.find("=>true,").expect(
        "PB-DX39 r2c: `filter_is_source_relative` has no `=> true,` arm -- it has \
                 been restructured, and this row's parse is no longer measuring it",
    );
    let true_side = &body[..split];
    let false_side = &body[split..];
    let names = |s: &str| -> BTreeSet<String> {
        let mut out = BTreeSet::new();
        let mut from = 0usize;
        while let Some(rel) = s[from..].find("EffectFilter::") {
            let at = from + rel + "EffectFilter::".len();
            out.insert(
                s[at..]
                    .chars()
                    .take_while(|c| c.is_alphanumeric() || *c == '_')
                    .collect(),
            );
            from = at;
        }
        out
    };
    let classified_true = names(true_side);
    let classified_false = names(false_side);
    let consuming = source_relative_arm_names();
    assert_eq!(
        classified_true,
        consuming,
        "PB-DX39 r2c: `layers::filter_is_source_relative` disagrees with the arms of \
         `effect_applies_to_inner` that actually consume the `SourceView`. `effect_applies_to` \
         uses this classifier to decide whether to resolve the source AT ALL, so a filter on \
         the wrong side of it is handed `None` and matches nothing -- the exact CR 608.2h / \
         CR 604.2 defect PB-DX39 closed, restored for one variant and invisible to every \
         other row here. classified-true only: {:?}; consuming only: {:?}",
        classified_true.difference(&consuming).collect::<Vec<_>>(),
        consuming.difference(&classified_true).collect::<Vec<_>>()
    );
    // Non-vacuity: the parse must find BOTH sides, or the equality above could be two
    // empty sets, and the classifier must cover every declared variant (its exhaustive
    // match makes that a compile error, so this is a check on the PARSE, not on the code).
    assert!(
        classified_false.len() >= 15,
        "PB-DX39 r2c: only {} variants parsed on the `false` side (17 at HEAD); the split \
         on `=> true,` has broken and this row is measuring half a function",
        classified_false.len()
    );
    assert!(
        classified_true.is_disjoint(&classified_false),
        "PB-DX39 r2c: {:?} appears on BOTH sides of the classifier -- the `=> true,` split \
         has landed in the wrong place",
        classified_true
            .intersection(&classified_false)
            .collect::<Vec<_>>()
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// r3 — the SR-24 successor: the LKI reader roster
// ─────────────────────────────────────────────────────────────────────────────

/// Every `(file, enclosing fn)` allowed to touch the LKI store, **with its occurrence
/// count**.
///
/// SR-24's own in-source note said *"Adding a NEW READER that consults a fifth snapshot
/// keyword is NOT machine-caught: add it here and add a matching sr13 case, or the gate
/// will silently drop those snapshots."* That is exactly what PB-DX39 did — it added a
/// third reader that consults **no keyword at all** — and nothing in the tree would have
/// noticed. This row is the machine check that note asked for.
///
/// A new entry is not automatically wrong; what it must not be is SILENT. Whoever adds one
/// is thereby told to check that `capture_lki_snapshot`'s gate stores what they intend to
/// read.
///
/// # Two `/review` defeats, both fixed here
///
/// **(1) The needles were `["lki_object_snapshot", ".lki_objects"]`, and the second one has
/// a leading dot.** `GameState::lki_objects(state)` — the path-qualified spelling of the
/// very same accessor — has no dot, so a planted
///
/// ```text
/// pub(crate) fn a2c_alias_reader(state: &GameState, id: ObjectId) -> Option<PlayerId> {
///     let map = GameState::lki_objects(state);
///     map.get(&id).map(|o| o.controller)
/// }
/// ```
///
/// called from `is_effect_active`'s `WhileSourceOnBattlefield` arm as an LKI fallback — i.e.
/// a departed permanent's static ability running for the rest of the game, exactly what
/// `r4` exists to prevent — left **all thirteen gates and the full suite green**. The needle
/// is now the BARE TOKEN at word boundaries, which also means `maybe_clear_lki_objects` and
/// `store_lki_snapshot` are not false hits (`_` is a word character, so the token inside
/// them is not bounded).
///
/// **(2) The roster was a `BTreeSet`, so a read added INSIDE an already-listed function
/// collapsed into the existing element.** Planting
/// `if let Some(o) = self.lki_object_snapshot(ObjectId(1)) { let _leak = o.controller; }`
/// into `maybe_clear_lki_objects` — an allowlisted row — left `r3` green. **That is
/// PB-DX49's own recorded finding on its `r7`**, which PB-DX49 closed with a second
/// conjunct re-checking each allowlisted site's body; this row inherited the shape without
/// the fix. The roster therefore stores a COUNT per site and compares maps, not sets.
const LKI_SITES: &[(&str, &str, usize, &str)] = &[
    (
        "crates/engine/src/state/mod.rs",
        "<top-level>",
        1,
        "The `GameState.lki_objects` field DECLARATION itself. Not a reader; it is here \
         because the bare-token needle sees the declaration too, and hiding it would mean \
         the needle had an exception nobody could audit.",
    ),
    (
        "crates/engine/src/state/mod.rs",
        "lki_objects",
        2,
        "SR-3 public read accessor for the whole store: its own name plus `&self.lki_objects`.",
    ),
    (
        "crates/engine/src/state/mod.rs",
        "lki_object_snapshot",
        2,
        "SR-3 keyed read accessor -- the one every reader below goes through: its own name \
         plus `self.lki_objects.get(&id)`.",
    ),
    (
        "crates/engine/src/state/mod.rs",
        "maybe_clear_lki_objects",
        2,
        "SR-13 clear, gated on stack + pending-trigger emptiness (see r6): the emptiness \
         test and the reset. NOT a read of any snapshot's contents -- if this count moves \
         up, someone has added one.",
    ),
    (
        "crates/engine/src/state/mod.rs",
        "store_lki_snapshot",
        1,
        "PB-DX39: the single insert path, shared by both capture clauses.",
    ),
    (
        "crates/engine/src/state/builder.rs",
        "build",
        1,
        "`lki_objects: OrdMap::new()` -- the field initialiser. Not a reader; visible only \
         because the needle is now the bare token.",
    ),
    (
        "crates/engine/src/state/hash.rs",
        "public_state_hash",
        1,
        "SR-17: the store is hashed as state; not a semantic reader.",
    ),
    (
        "crates/engine/src/effects/mod.rs",
        "damage_source_characteristics",
        1,
        "SR-13 reader 1: CR 702.80c / 702.90e wither + infect + deathtouch off a dead source.",
    ),
    (
        "crates/engine/src/effects/mod.rs",
        "damage_source_controller",
        1,
        "SR-13 reader 2: CR 702.15b lifelink off a dead source.",
    ),
    (
        "crates/engine/src/rules/layers.rs",
        "source_view_at_resolution",
        1,
        "PB-DX39 reader 3: CR 608.2h / 113.7a source-relative EffectFilter arms. Consults \
         controller / attached_to / chosen_creature_type / chosen_color -- NO keyword, which \
         is why widening LKI_RELEVANT_KEYWORDS is not how a future reader is served.",
    ),
    (
        "crates/simulator/src/invariants.rs",
        "attachment_validity_evidence",
        1,
        "PB-DX56 / OOS-FB1-1 reader 4, and the first from OUTSIDE the engine crate: a \
         `check_attachment_validity` violation names an ATTACHER whose `attached_to` \
         target has already departed the battlefield, and this function looks up the \
         target's last-known name/card-types for the crash artefact via the `pub` \
         `GameState::lki_objects()` accessor. Deliberately NOT silent about the SR-24 \
         gate this row's own doc warns about: `None` (no snapshot captured for this \
         target, or the store was already cleared) is reported explicitly as \
         `target_lki=<no snapshot: ...>` in the evidence rather than treated as \
         equivalent to a captured one -- this is diagnostic ENRICHMENT for a human \
         reading a crash report, not a game-rules decision, so an empty map here \
         changes what gets PRINTED, never what the engine DOES.",
    ),
];

/// Byte offsets at which `needle` occurs in `src` **as a whole token** — neither neighbour
/// may be `[A-Za-z0-9_]`.
///
/// This is the fix for the `/review`'s path-qualified-alias defeat. It is deliberately
/// receiver-agnostic: `self.lki_objects`, `state.lki_objects` and
/// `GameState::lki_objects(state)` are all the same token, while `maybe_clear_lki_objects`
/// and `store_lki_snapshot` are not (their preceding `_` is a word character).
fn token_offsets(src: &str, needle: &str) -> Vec<usize> {
    fn wordish(c: u8) -> bool {
        c.is_ascii_alphanumeric() || c == b'_'
    }
    let b = src.as_bytes();
    let mut out = Vec::new();
    let mut from = 0usize;
    while let Some(rel) = src[from..].find(needle) {
        let at = from + rel;
        let before_ok = at == 0 || !wordish(b[at - 1]);
        let after = at + needle.len();
        let after_ok = after >= b.len() || !wordish(b[after]);
        if before_ok && after_ok {
            out.push(at);
        }
        from = at + needle.len();
    }
    out
}

fn live_lki_sites() -> BTreeMap<(String, String), usize> {
    let mut out: BTreeMap<(String, String), usize> = BTreeMap::new();
    for (label, path) in workspace_src_files_checked() {
        let Ok(raw) = std::fs::read_to_string(&path) else {
            continue;
        };
        let src = production_source(&raw);
        for needle in ["lki_object_snapshot", "lki_objects"] {
            for at in token_offsets(&src, needle) {
                // The accessor DEFINITIONS name themselves; attribute by enclosing fn, which
                // puts each definition in its own row rather than hiding it.
                *out.entry((label.clone(), enclosing_fn_name(&src, at)))
                    .or_default() += 1;
            }
        }
    }
    // `capture_lki_snapshot` and `capture_source_lki_for_pending_ability` do NOT appear:
    // both delegate their insert to `store_lki_snapshot` (PB-DX39's single store path).
    out
}

/// CR 608.2h / CR 113.7a: the LKI store's reader set is pinned workspace-wide, **by site
/// and by occurrence count**.
#[test]
fn r3_lki_reader_set_is_pinned() {
    let live = live_lki_sites();
    let pinned: BTreeMap<(String, String), usize> = LKI_SITES
        .iter()
        .map(|(f, n, c, _)| ((f.to_string(), n.to_string()), *c))
        .collect();
    let live_only: Vec<_> = live
        .iter()
        .filter(|(k, v)| pinned.get(*k) != Some(v))
        .collect();
    let pinned_only: Vec<_> = pinned
        .iter()
        .filter(|(k, v)| live.get(*k) != Some(v))
        .collect();
    assert_eq!(
        live, pinned,
        "PB-DX39 r3: the census of functions touching `lki_objects` / \
         `lki_object_snapshot` has changed. SR-24's capture gate stores a snapshot only for \
         a departing permanent that carries one of four DAMAGE keywords OR is the source of \
         an ability already pending (`GameState::is_source_of_a_pending_ability`). A reader \
         outside both of those conditions will silently observe an EMPTY map -- which is \
         precisely how `OOS-DX5-3` and `OOS-DX5-7` stayed open. Add your site to LKI_SITES \
         with a reason and a COUNT, and while you are there decide whether \
         `capture_lki_snapshot`'s gate stores what you intend to read. A count that moved \
         inside an EXISTING row is the same finding: an extra read added to an allowlisted \
         function is still a new reader. differs (live): {live_only:?}; differs (pinned): \
         {pinned_only:?}"
    );
    assert!(
        !live.is_empty(),
        "PB-DX39 r3: zero LKI sites found -- the workspace walk has gone vacuous and the map \
         assertion above is comparing two empty maps"
    );
    // Non-vacuity floor for the tokeniser itself: it must see the path-qualified spelling
    // that defeated the first draft, and must NOT see the two `_`-prefixed function names
    // that would otherwise be false hits.
    assert_eq!(
        token_offsets("letmap=GameState::lki_objects(state);", "lki_objects").len(),
        1,
        "PB-DX39 r3: the tokeniser cannot see `GameState::lki_objects(..)`, the exact \
         spelling the `/review` used to defeat this row"
    );
    assert!(
        token_offsets("self.maybe_clear_lki_objects();", "lki_objects").is_empty(),
        "PB-DX39 r3: the tokeniser treats `maybe_clear_lki_objects` as a hit; `_` is a word \
         character and the roster's counts assume it is not"
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// r4 — the two source reads PB-DX39 pinned stay LIVE-ONLY, split across two
// functions since PB-DX42b
// ─────────────────────────────────────────────────────────────────────────────

/// CR 611.3b / CR 604.2: both source reads PB-DX39 pinned must stay live.
///
/// **PB-DX42b split the function this row used to name.** `is_effect_active`
/// used to carry BOTH reads in one body (the CR 611.3b duration match and the
/// CR 604.2 condition check); PB-DX42b split it at that exact seam into
/// `is_effect_duration_active` (duration only) and `is_effect_condition_satisfied`
/// (condition only), so `is_effect_active` is now a three-line composition of the
/// two and this test's ORIGINAL single-body extraction would find almost nothing
/// to check — the vacuously-green failure mode this whole file's method exists to
/// avoid, reproduced by a refactor rather than a hand-edited comment. Both reads
/// are checked below, one per function, rather than folded back into one body.
///
/// The cite is **CR 611.3b** — *"the effect applies at all times that the permanent
/// generating it is on the battlefield"* — and not CR 611.2b, which this row said until the
/// `/review` corrected it. CR 611.2b is about the *"for as long as"* durations of an effect
/// generated by a RESOLUTION, and it is still the right rule for `is_effect_duration_active`'s
/// `UntilYourNextTurn` / `WhileYouControlSource` arms; it is the wrong one for the claim
/// being made here, which is about a STATIC ability's source leaving the battlefield.
///
/// The `WhileSourceOnBattlefield` read (in `is_effect_duration_active`) asks whether the
/// source is still on the battlefield; answering it from LKI would return *"yes, as it
/// last was"* for the rest of the game. The `condition` read (in
/// `is_effect_condition_satisfied`) supplies a CR 604.2 static ability's controller, and
/// CR 608.2h / CR 113.7a are scoped to an ability that *"exists on the stack independently
/// of its source"* (CR 113.7a) — which a static ability never does.
///
/// This row exists so a later batch cannot "finish the job" by routing these two through
/// `source_view_at_resolution` on the theory that PB-DX39 (or PB-DX42b's split) missed them.
///
/// # It is a WHITELIST, because an absence test cannot be made complete
///
/// The first draft asserted the ABSENCE of three literals
/// (`lki_object_snapshot`, `.lki_objects`, `source_view_at_resolution(`). The `/review`
/// defeated it in one line, by giving the LKI read a new NAME: a
/// `fn a2c_alias_reader(state, id)` wrapping `GameState::lki_objects(state)` and called
/// from the `WhileSourceOnBattlefield` arm as an `unwrap_or_else` fallback left every gate
/// green while making a departed permanent's static ability run for the rest of the game.
/// No list of forbidden names can be complete, because the attacker picks the name. A list
/// of PERMITTED identifiers can be, because each function's vocabulary is finite and small
/// — so the assertion is now set equality over the identifiers each body contains, and
/// `a2c_alias_reader` would redden it by existing.
///
/// **`is_effect_condition_satisfied`'s vocabulary is taken with comments AND string
/// literals stripped** (`strip_comments_and_strings`, not the bare `strip_comments` the
/// original single-function version used): PB-DX42b's `debug_assert!` inside that function
/// carries a long CR-613.1d prose message, and a whitelist keyed on the RAW body would have
/// to enumerate every English word in that message, which would make an unrelated wording
/// edit redden a gate about LKI-vs-live reads for no reason connected to what it checks.
/// `is_effect_duration_active` carries no string literals, so stripping them changes
/// nothing for it, but both are extracted the same way for consistency.
///
/// Brittle on purpose: a genuine refactor of either function is exactly the moment someone
/// should re-read the two CR arguments above.
///
/// **PB-DX42b (`scutemob-233`): three tokens removed, and the PROVENANCE matters more than
/// the removal.** `IS_EFFECT_CONDITION_SATISFIED_VOCABULARY` carried `"Copy"`,
/// `"EffectLayer"` and a bare `"unwrap_or"`, which after PB-DX42b occur nowhere in the LIVE
/// (comment-and-string-stripped) body — only inside the `OOS-DX42b-1` explanatory `//`
/// comment above the `debug_assert!`, which discusses the REJECTED `unwrap_or(Copy)` design.
///
/// **This gate was GREEN when the vocabulary was captured and the coordinator's own later
/// edit is what reddened it.** The first draft of this note said the pinned set "was
/// evidently captured before [comment stripping] was adopted and never re-derived" — i.e.
/// that the slack was pre-existing. That is FALSE, and the evidence is a measurement rather
/// than a memory: `cargo test --workspace --no-fail-fast` ran GREEN at 5,231 / 0 / 5 on the
/// tree that first introduced this vocabulary, and the three tokens are EXACTLY the
/// identifiers that the next edit — gating the `debug_assert!` on `Some` instead of
/// `unwrap_or(EffectLayer::Copy)` — deleted from the body. The gate did its job on its first
/// real event; what failed is that the edit shipped without re-running the suite.
/// **PB-DX28's "re-take the measured table" MEDIUM, committed by the coordinator rather than
/// by a delegated agent** — and a wrong provenance is worse than a wrong count, because the
/// next reader reuses the reason. Removed rather than left as silent slack in a gate whose
/// whole point is exact set equality.
const IS_EFFECT_DURATION_ACTIVE_VOCABULARY: &[&str] = &[
    "Battlefield",
    "EffectDuration",
    "Indefinite",
    "None",
    "Some",
    "UntilEndOfTurn",
    "UntilYourNextTurn",
    "WhilePaired",
    "WhileSourceOnBattlefield",
    "WhileYouControlSource",
    "ZoneId",
    "_",
    "a",
    "a_ok",
    "b",
    "b_ok",
    "duration",
    "effect",
    "false",
    "get",
    "is_phased_in",
    "let",
    "map",
    "match",
    "o",
    "obj",
    "objects",
    "paired_with",
    "source",
    "source_id",
    "state",
    "true",
    "unwrap_or",
    "zone",
];

const IS_EFFECT_CONDITION_SATISFIED_VOCABULARY: &[&str] = &[
    "InFlightGuard",
    "PlayerId",
    "Some",
    "check_static_condition_ctx",
    "condition",
    "contains",
    "controller",
    "crate",
    "debug_assert",
    "effect",
    "effects",
    "else",
    "enter",
    "eval",
    "false",
    "get",
    "id",
    "if",
    "in_flight",
    "layer",
    "let",
    "map",
    "mut",
    "obj",
    "objects",
    "player",
    "ref",
    "required",
    "required_characteristic_layer",
    "return",
    "source",
    "source_id",
    "state",
    "true",
    "unwrap_or_else",
];

/// Every `[A-Za-z_][A-Za-z0-9_]*` run in `src`.
fn identifiers(src: &str) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let b = src.as_bytes();
    let mut i = 0usize;
    while i < b.len() {
        if b[i].is_ascii_alphabetic() || b[i] == b'_' {
            let start = i;
            while i < b.len() && (b[i].is_ascii_alphanumeric() || b[i] == b'_') {
                i += 1;
            }
            out.insert(src[start..i].to_string());
        } else {
            i += 1;
        }
    }
    out
}

/// One half of r4: check a single function's body against a pinned vocabulary, the LKI
/// absence needles, and an exact count of live `.objects.get(&source_id)` reads.
fn r4_check_one(
    fname: &str,
    pinned_words: &[&str],
    expected_live_reads: usize,
    min_body_len: usize,
) {
    let raw_body = fn_body(LAYERS_RS, fname);
    let comment_and_string_stripped = strip_comments_and_strings(&raw_body);
    let body = squeeze(&raw_body);
    assert!(
        body.len() > min_body_len,
        "PB-DX39/PB-DX42b r4: `{fname}`'s measured body is only {} bytes (expected more \
         than {min_body_len}); the brace bounding has broken",
        body.len()
    );
    let live = identifiers(&comment_and_string_stripped);
    let pinned: BTreeSet<String> = pinned_words.iter().map(|s| s.to_string()).collect();
    assert_eq!(
        live,
        pinned,
        "PB-DX39/PB-DX42b r4: `{fname}`'s vocabulary has changed. Its source read(s) are \
         LIVE-ONLY on purpose (CR 611.3b duration, CR 604.2 static condition), and an LKI \
         fallback makes a departed permanent's static ability immortal -- the exact \
         opposite of CR 611.3b. A new identifier here is either that regression under a \
         name no forbidden-list could have anticipated (the `/review` used \
         `a2c_alias_reader`), or a legitimate refactor -- in which case re-read the two CR \
         arguments in this row's doc and then update the vocabulary. \
         new: {:?}; gone: {:?}",
        live.difference(&pinned).collect::<Vec<_>>(),
        pinned.difference(&live).collect::<Vec<_>>()
    );
    for needle in [
        "lki_object_snapshot",
        ".lki_objects",
        "source_view_at_resolution(",
    ] {
        assert!(
            !body.contains(needle),
            "PB-DX39/PB-DX42b r4: `{fname}` now names `{needle}`. Its source read(s) are \
             LIVE-ONLY on purpose (CR 611.3b duration, CR 604.2 static condition). An LKI \
             fallback makes a departed permanent's static ability immortal -- the exact \
             opposite of CR 611.3b."
        );
    }
    // Non-vacuity: the live read(s) must still be there, so "no LKI needle" is a
    // statement about how they read and not about them having been deleted.
    assert_eq!(
        body.matches(".objects.get(&source_id)").count(),
        expected_live_reads,
        "PB-DX39/PB-DX42b r4: expected exactly {expected_live_reads} live \
         `state.objects.get(&source_id)` read(s) in `{fname}`. If one legitimately moved, \
         update this count and say where it went."
    );
}

#[test]
fn r4_is_effect_active_reads_are_live_only() {
    // Floors measured at HEAD: 682 and 961 squeezed bytes respectively. Comfortably
    // under each, so a body shrinking toward the OTHER function's size (logic
    // silently moving) fails loudly instead of this test quietly measuring nothing.
    r4_check_one(
        "is_effect_duration_active",
        IS_EFFECT_DURATION_ACTIVE_VOCABULARY,
        1,
        500,
    );
    r4_check_one(
        "is_effect_condition_satisfied",
        IS_EFFECT_CONDITION_SATISFIED_VOCABULARY,
        1,
        700,
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// r5 — the LKI-consulting constructor has exactly one caller
// ─────────────────────────────────────────────────────────────────────────────

/// Every `(file, enclosing fn)` naming `source_view_at_resolution`, workspace-wide.
///
/// **The needle is the BARE IDENTIFIER at word boundaries, not `identifier(`.** The first
/// draft required the trailing paren, and the `/review` walked through it with
///
/// ```text
/// let at_res: fn(&GameState, ObjectId) -> Option<SourceView<'_>> = source_view_at_resolution;
/// ```
///
/// in `effect_applies_to`, calling `at_res(..)` — i.e. giving the CR 611.3a static path the
/// LKI fallback this row exists to deny it — and every gate stayed green. **Mitigated, and
/// it is worth saying which half held**: the in-source unit test
/// `pb_dx39_source_view_tests::the_live_static_path_never_consults_last_known_information`
/// DID go red, so the behaviour was covered and only the gate was not. Taking a function's
/// address is a use like any other, and now it is measured like one.
fn live_at_resolution_callers() -> BTreeSet<(String, String)> {
    let mut out = BTreeSet::new();
    for (label, path) in workspace_src_files_checked() {
        let Ok(raw) = std::fs::read_to_string(&path) else {
            continue;
        };
        let src = production_source(&raw);
        for at in token_offsets(&src, "source_view_at_resolution") {
            let func = enclosing_fn_name(&src, at);
            // The definition names itself; that is the `fn` whose body starts here.
            if func != "source_view_at_resolution" {
                out.insert((label.clone(), func));
            }
        }
    }
    out
}

/// CR 608.2h / CR 611.3a: the last-known-information fallback belongs to the LOCKED
/// (resolution-generated) path and nowhere else.
///
/// Without this row, *"the fallback is locked-path only"* is a comment — and this batch's
/// whole subject is that a comment is a claim. A second caller would silently re-open the
/// regression the two-constructor split exists to prevent: a `affected_set: None` effect
/// registered by a static ability whose source has departed would START applying.
#[test]
fn r5_source_view_at_resolution_has_exactly_one_caller() {
    let live = live_at_resolution_callers();
    let pinned: BTreeSet<(String, String)> = [(
        "crates/engine/src/rules/layers.rs".to_string(),
        "snapshot_affected_set".to_string(),
    )]
    .into_iter()
    .collect();
    assert_eq!(
        live,
        pinned,
        "PB-DX39 r5: `source_view_at_resolution` -- the ONLY constructor that consults last \
         known information -- has a caller other than `snapshot_affected_set`. CR 608.2h and \
         CR 113.7a are scoped to an ability that 'exists on the stack independently of its \
         source' (CR 113.7a); a CR 611.3a static ability's effect exists only while its \
         ability does, so giving it an LKI fallback makes a departed permanent's static \
         ability run for the rest of the game. If the new caller really is a CR 611.2c \
         resolution-time determination, add it here with that reasoning. \
         live only: {:?}; pinned only: {:?}",
        live.difference(&pinned).collect::<Vec<_>>(),
        pinned.difference(&live).collect::<Vec<_>>()
    );
}

/// `r5`'s companion, wrong way round: the LIVE constructor must NOT consult the store, so
/// the split is a real split and not two names for one function.
#[test]
fn r5b_source_view_live_never_consults_the_lki_store() {
    let body = squeeze(&fn_body(LAYERS_RS, "source_view_live"));
    assert!(
        body.contains(".objects.get(&source_id)"),
        "PB-DX39 r5b: `source_view_live` no longer performs the live read at all; the \
         measured body is {body:?}"
    );
    assert!(
        !body.contains("lki_object_snapshot"),
        "PB-DX39 r5b: `source_view_live` consults the LKI store. CR 611.3a: a static \
         ability's effect 'isn't locked in' and exists only while the ability does."
    );
    // And the resolution constructor must, or `r5`'s pin would be guarding a no-op.
    let at_res = squeeze(&fn_body(LAYERS_RS, "source_view_at_resolution"));
    assert!(
        at_res.contains(".objects.get(&source_id)") && at_res.contains("lki_object_snapshot("),
        "PB-DX39 r5b: `source_view_at_resolution` must read LIVE FIRST and fall back to the \
         LKI store second (CR 608.2h's order is the rule, and the Jitte's own rulings are \
         its two halves. 2005-02-01 #3: `If the Jitte is MOVED after the +2/+2 mode is \
         announced but before it resolves, the bonus is given to the creature that is \
         equipped when the ability resolves` -- the LIVE half. 2005-02-01 #5: `If the Jitte \
         LEAVES THE BATTLEFIELD after the +2/+2 mode is announced but before it resolves, \
         the bonus is given to the creature that was most recently equipped once the \
         ability resolves` -- the LKI half, quoted in full because #3 on its own reads as \
         an argument against the fallback. The bonus goes to \
         the creature equipped AT RESOLUTION). Measured body: {at_res:?}"
    );
    let live_at = at_res.find(".objects.get(&source_id)").unwrap();
    let lki_at = at_res.find("lki_object_snapshot(").unwrap();
    assert!(
        live_at < lki_at,
        "PB-DX39 r5b: `source_view_at_resolution` consults the LKI store BEFORE the live \
         object. CR 608.2h: 'the effect uses the current information of that object if it's \
         in the public zone it was expected to be in; IF IT'S NO LONGER IN THAT ZONE ... the \
         effect uses the object's last known information.' The order is the rule."
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// r6 — capture and clear are coupled
// ─────────────────────────────────────────────────────────────────────────────

const STATE_MOD_RS: &str = "crates/engine/src/state/mod.rs";

/// SR-13 / PB-DX39: a snapshot captured because an ability is pending must live exactly as
/// long as that ability.
///
/// `capture_lki_snapshot`'s second disjunct stores when the departing object is the source
/// of something in `stack_objects` OR in `pending_triggers`. `maybe_clear_lki_objects`
/// discards the store only when `stack_objects` AND `pending_triggers` are both empty. The
/// two conditions are complements over the same two collections, so a snapshot cannot be
/// cleared while the ability that caused it to be captured is still pending. Drop either
/// collection from either side and that stops being true.
#[test]
fn r6_clear_condition_covers_the_capture_condition() {
    let capture = squeeze(&fn_body(STATE_MOD_RS, "is_source_of_a_pending_ability"));
    let clear = squeeze(&fn_body(STATE_MOD_RS, "maybe_clear_lki_objects"));
    for collection in ["stack_objects", "pending_triggers"] {
        assert!(
            capture.contains(collection),
            "PB-DX39 r6: `is_source_of_a_pending_ability` no longer consults \
             `{collection}`. Both queues must be consulted: an ability can be ON the stack \
             (CR 113.7a) or QUEUED as a pending trigger (CR 603.3b), and Umezawa's Jitte is \
             the first case while a death trigger is the second."
        );
        assert!(
            clear.contains(collection),
            "PB-DX39 r6: `maybe_clear_lki_objects` no longer waits on `{collection}`, but \
             `is_source_of_a_pending_ability` still captures for it. A snapshot would be \
             discarded while the ability that needs it is still pending, and the CR 608.2h \
             read would silently answer `None` -- reopening `OOS-DX5-3`."
        );
    }
    assert!(
        capture.contains("stack_registry::source_of("),
        "PB-DX39 r6: `is_source_of_a_pending_ability` no longer delegates to \
         `stack_registry::source_of`, which is exhaustive over every `StackObjectKind` with \
         NO wildcard arm. A hand-rolled match here means a new stack-object kind silently \
         loses its source's LKI instead of failing to compile."
    );
}

/// PB-DX39: the activation-cost clause is wired at every self-move cost site.
///
/// `rules::abilities` pays `Cost::SacrificeSelf` / `Cost::ExileSelf` / `Cost::DiscardSelf`
/// BEFORE pushing the ability onto the stack (CR 601.2h, reached for an activated
/// ability by CR 602.2b), so
/// `capture_lki_snapshot`'s pending-ability disjunct cannot see the ability yet and
/// declines. Each of those three blocks must therefore capture explicitly. Mardu Ascendancy
/// (`OOS-DX5-7`) is the sacrifice case, and it was wrong in **every** game.
/// Every first argument `handle_activate_ability` passes to `move_object_to_zone`, as a
/// SORTED MULTISET.
///
/// Three are the self-moves this row is about. The other four are cost payments that move
/// something else — a card from hand (`Cost::Discard`), another permanent
/// (`Cost::Sacrifice`), a Food token, an exiled card — and they are pinned here **only** so
/// that the total is accounted for. That is the `/review`'s fix: `r6b`'s first draft keyed
/// on the literal `move_object_to_zone(source,`, so
///
/// ```text
/// let src_id = source;
/// let (_new, _) = state.move_object_to_zone(src_id, dest)?;
/// ```
///
/// — a one-line rebinding — was invisible to it, which is **PB-DX51's `r1` failure
/// verbatim**: a gate written for one variant measures that variant. Pinning every first
/// argument means a fourth self-move cannot arrive under a new name.
const ACTIVATE_ABILITY_MOVE_ARGS: &[&str] = &[
    "card_to_discard",
    "food_id",
    "id",
    "sac_id",
    "source",
    "source",
    "source",
];

#[test]
fn r6b_every_self_move_activation_cost_captures_first() {
    // The `/review`'s fix, first: pin every `move_object_to_zone` call in
    // `handle_activate_ability` by its FIRST ARGUMENT, not just the ones spelled `source`.
    let activate_body = fn_body(
        "crates/engine/src/rules/abilities.rs",
        "handle_activate_ability",
    );
    let squeezed_body: String = activate_body
        .chars()
        .filter(|c| !c.is_whitespace())
        .collect();
    let mut live_args: Vec<String> = Vec::new();
    let mut from = 0usize;
    while let Some(rel) = squeezed_body[from..].find("move_object_to_zone(") {
        let at = from + rel + "move_object_to_zone(".len();
        let arg: String = squeezed_body[at..]
            .chars()
            .take_while(|c| *c != ',' && *c != ')')
            .collect();
        live_args.push(arg);
        from = at;
    }
    live_args.sort();
    let pinned_args: Vec<String> = ACTIVATE_ABILITY_MOVE_ARGS
        .iter()
        .map(|s| s.to_string())
        .collect();
    assert_eq!(
        live_args, pinned_args,
        "PB-DX39 r6b: the multiset of first arguments `handle_activate_ability` passes to \
         `move_object_to_zone` has changed (7 at HEAD: 3 self-moves plus 4 cost payments \
         that move something OTHER than the source). If the new one moves the ability's own \
         source -- under ANY spelling, including a local rebinding of `source` -- it must \
         call `capture_source_lki_for_pending_ability(source)` immediately before it, or a \
         source-relative continuous effect from that ability resolves at nobody \
         (`OOS-DX5-7`, Mardu Ascendancy). If it moves something else, add it here with that \
         reason."
    );

    let src = strip_comments(&read_engine_file("crates/engine/src/rules/abilities.rs"));
    let squeezed: String = src.chars().filter(|c| !c.is_whitespace()).collect();
    let moves = squeezed.matches("move_object_to_zone(source,").count();
    assert_eq!(
        moves, 3,
        "PB-DX39 r6b: `rules/abilities.rs` has {moves} self-moves of `source` (3 at HEAD: \
         discard_self, sacrifice_self, exile_self). A FOURTH self-move activation cost must \
         also call `capture_source_lki_for_pending_ability(source)` immediately before it, \
         or a source-relative continuous effect from that ability resolves at nobody."
    );
    let captures = squeezed
        .matches("capture_source_lki_for_pending_ability(source)")
        .count();
    assert_eq!(
        captures, 3,
        "PB-DX39 r6b: found {captures} `capture_source_lki_for_pending_ability(source)` \
         calls against {moves} self-moves. Every self-move cost block needs one."
    );
    // The ORDER is the whole point: capture must precede the move, because the move retires
    // the id (CR 400.7) and resets the object's fields.
    for (i, _) in squeezed.match_indices("move_object_to_zone(source,") {
        let head = &squeezed[..i];
        let cap = head.rfind("capture_source_lki_for_pending_ability(source)");
        assert!(
            cap.is_some_and(|c| head[c..].matches("move_object_to_zone(source,").count() == 0),
            "PB-DX39 r6b: a `move_object_to_zone(source, ..)` at byte {i} has no \
             `capture_source_lki_for_pending_ability(source)` between it and the previous \
             self-move. The capture must run BEFORE the move: `move_object_to_zone` retires \
             the id (CR 400.7) and resets `attached_to` / `controller`."
        );
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// r7 — the corpus census the scoping rests on
// ─────────────────────────────────────────────────────────────────────────────

/// A `ContinuousEffectDef` registered by a **static ability** (CR 611.3a), i.e. one that
/// takes the LIVE path and gets `affected_set: None`.
struct LiveRegistration {
    card: String,
    holder: &'static str,
    filter: String,
    duration: String,
}

/// The JSON variant name of an enum value: `"Unit"` for a unit variant, the single key for
/// a newtype/struct variant.
fn variant_name(v: &Value) -> String {
    match v {
        Value::String(s) => s.clone(),
        Value::Object(m) if m.len() == 1 => m.keys().next().cloned().unwrap_or_default(),
        other => format!("<unrecognised:{other}>"),
    }
}

fn collect_under_key<'a>(v: &'a Value, key: &str, out: &mut Vec<&'a Value>) {
    match v {
        Value::Object(m) => {
            for (k, child) in m {
                if k == key {
                    out.push(child);
                }
                collect_under_key(child, key, out);
            }
        }
        Value::Array(a) => {
            for child in a {
                collect_under_key(child, key, out);
            }
        }
        _ => {}
    }
}

fn all_ability_lists(def: &CardDefinition) -> Vec<&[AbilityDefinition]> {
    let mut out: Vec<&[AbilityDefinition]> = vec![&def.abilities];
    if let Some(f) = def.back_face.as_ref() {
        out.push(&f.abilities);
    }
    if let Some(f) = def.adventure_face.as_ref() {
        out.push(&f.abilities);
    }
    out
}

/// Every card-def `ContinuousEffectDef` that reaches the engine on the LIVE path.
///
/// Two holders, both enumerated by walking `all_cards()` and never by grepping card source
/// (SR-36):
/// * `AbilityDefinition::Static { continuous_effect }` — registered by `rules/replacement.rs`
///   and by `rules/resolution.rs`'s `StackObjectKind::ClassLevelAbility` arm (CR 716.2a),
///   both of which forward the def's own `duration` verbatim.
/// * `Effect::CreateEmblem { static_effects }` — `effects/mod.rs`'s emblem loop, which uses
///   `EffectDuration::Indefinite` regardless of what the def says.
///
/// Depth-agnostic on both: a `CreateEmblem` can sit inside a `Sequence` inside a mode inside
/// a loyalty ability, and a walk keyed on the parent key measures the parent key.
fn live_path_registrations() -> Vec<LiveRegistration> {
    let mut out = Vec::new();
    for def in all_cards() {
        for abilities in all_ability_lists(&def) {
            for ability in abilities {
                let json = serde_json::to_value(ability).expect("AbilityDefinition serialises");
                let mut defs: Vec<(&'static str, &Value)> = Vec::new();
                let mut found = Vec::new();
                collect_under_key(&json, "continuous_effect", &mut found);
                for f in found {
                    defs.push(("AbilityDefinition::Static", f));
                }
                let mut emblem = Vec::new();
                collect_under_key(&json, "static_effects", &mut emblem);
                for group in emblem {
                    if let Value::Array(items) = group {
                        for item in items {
                            defs.push(("Effect::CreateEmblem", item));
                        }
                    }
                }
                for (holder, ced) in defs {
                    let Some(obj) = ced.as_object() else { continue };
                    let (Some(filter), Some(duration)) = (obj.get("filter"), obj.get("duration"))
                    else {
                        continue;
                    };
                    out.push(LiveRegistration {
                        card: def.name.clone(),
                        holder,
                        filter: variant_name(filter),
                        duration: variant_name(duration),
                    });
                }
            }
        }
    }
    out
}

/// The population an UNCONDITIONAL LKI fallback would have changed the behaviour of --
/// **measured, not argued, and NOT zero.**
///
/// The coordinator's design note predicted this would come out at zero. It does not: the
/// walk finds **4 registrations across 3 cards**, and all four are `Effect::CreateEmblem`
/// static effects with `EffectDuration::Indefinite` and a source-relative filter (Elspeth,
/// Sun's Champion ×2; Kaito, Bane of Nightmares; Wrenn and Seven). Reported rather than
/// rounded to the prediction.
///
/// Splitting the ratchet by HOLDER is what makes the number mean something, because the two
/// holders have different exposure:
///
/// * **`AbilityDefinition::Static` — ratchet 0.** This is the dangerous class. Such a
///   registration's source is a PERMANENT, which can leave the battlefield at any moment,
///   and its duration is forwarded verbatim by `rules/replacement.rs` and by
///   `rules/resolution.rs`'s `StackObjectKind::ClassLevelAbility` arm (CR 716.2a). With an
///   unconditional LKI fallback, a member of this class whose duration is not
///   `WhileSourceOnBattlefield` would START APPLYING from the graveyard, forever. There are
///   none today and there must not be one without someone reading this.
/// * **`Effect::CreateEmblem` — ratchet 4.** CR 114.5: an emblem *"is neither a card nor a
///   permanent"*, and CR 114.2 puts it into the command zone. **The half that makes these
///   four harmless is an ENGINE MEASUREMENT and not a rule, and the `/review` was right to
///   force the distinction**: no CR rule says an emblem never leaves the command zone
///   (CR 114.1 defines what an emblem is, CR 114.3 that it has no other characteristics,
///   CR 114.4 that its abilities function there — none of them says it cannot move). What
///   is true is measurable: `effects/mod.rs`'s emblem construction places it in
///   `ZoneId::Command(controller)` and **nothing in the engine ever moves it out**, so its
///   `ObjectId` is never retired (CR 400.7 never fires on it), `source_view_live`'s lookup
///   always succeeds, and the fallback is unreachable for these four **whichever
///   constructor they used**. They are the SHAPE without the exposure — and if a later
///   batch teaches the engine to move an emblem, that measurement expires and this ratchet
///   is the thing that should stop being trusted.
///
/// So this row is not evidence that the scoping saved a live defect today. It is evidence
/// that the shape exists in the corpus, that the only thing keeping it harmless is a
/// property of emblems rather than anything about the filter, and that a fifth member
/// arriving under the other holder would be a real one.
const MAX_UNPROTECTED_STATIC_REGISTRATIONS: usize = 0;
const MAX_UNPROTECTED_EMBLEM_REGISTRATIONS: usize = 4;

/// Source-relative + live path + a duration `is_effect_active` does NOT already refuse.
///
/// `WhileSourceOnBattlefield` members are excluded because `is_effect_active` returns
/// `false` for them the moment the source leaves, so no source view of any kind is ever
/// consulted. That exclusion is *why* the residual is the interesting set: it is exactly
/// what `is_effect_active` does not protect.
fn unprotected_live_registrations() -> Vec<(&'static str, String)> {
    let source_relative: BTreeSet<String> =
        SOURCE_RELATIVE_ARMS.iter().map(|s| s.to_string()).collect();
    live_path_registrations()
        .into_iter()
        .filter(|r| source_relative.contains(&r.filter) && r.duration != "WhileSourceOnBattlefield")
        .map(|r| {
            (
                r.holder,
                format!("{} [{}] {} / {}", r.card, r.holder, r.filter, r.duration),
            )
        })
        .collect()
}

/// CR 611.3a / CR 114.5: the population the two-constructor split protects, ratcheted per
/// holder.
#[test]
fn r7_no_unprotected_live_path_source_relative_registration() {
    let members = unprotected_live_registrations();
    let statics: Vec<&String> = members
        .iter()
        .filter(|(h, _)| *h == "AbilityDefinition::Static")
        .map(|(_, m)| m)
        .collect();
    let emblems: Vec<&String> = members
        .iter()
        .filter(|(h, _)| *h == "Effect::CreateEmblem")
        .map(|(_, m)| m)
        .collect();

    // `==` rather than `<=`: the ratchet is zero, so `<=` is an absurd comparison (clippy
    // says so, and it is right). Equality is also the stronger statement -- it fails in
    // BOTH directions, and from zero the downward direction cannot occur.
    assert!(
        statics.len() == MAX_UNPROTECTED_STATIC_REGISTRATIONS,
        "PB-DX39 r7: {} card def(s) register a SOURCE-RELATIVE continuous effect from an \
         `AbilityDefinition::Static` (CR 611.3a) with a duration other than \
         `WhileSourceOnBattlefield`, above the ratchet of {}. That source is a PERMANENT and \
         can leave the battlefield, and `is_effect_active` will not refuse the effect once \
         it has -- so this is the class for which `source_view_live` having NO \
         last-known-information fallback is load-bearing. With an unconditional fallback \
         each of these would keep applying from the graveyard for the rest of the game. \
         Members: {statics:#?}",
        statics.len(),
        MAX_UNPROTECTED_STATIC_REGISTRATIONS
    );
    assert!(
        emblems.len() <= MAX_UNPROTECTED_EMBLEM_REGISTRATIONS,
        "PB-DX39 r7: {} emblem static effect(s) pair a source-relative filter with a \
         non-`WhileSourceOnBattlefield` duration, above the ratchet of {}. These are \
         harmless only because NOTHING IN THE ENGINE ever moves an emblem out of the \
         command zone (a measurement, not a rule -- CR 114 says an emblem is put there and \
         that its abilities function there, and says nothing about it staying), so its \
         `ObjectId` is never retired. Confirm that still holds for the new member (an \
         emblem that can leave would be the first real instance of this class) and then \
         raise the ratchet with that measurement stated. Members: {emblems:#?}",
        emblems.len(),
        MAX_UNPROTECTED_EMBLEM_REGISTRATIONS
    );
    // The emblem ratchet is a CEILING, and a ceiling with slack is where a regression hides
    // (PB-DX49's lesson). Pin the floor too, so a member silently LEAVING this set -- which
    // would mean the corpus changed under the reasoning above -- is also visible.
    assert_eq!(
        emblems.len(),
        MAX_UNPROTECTED_EMBLEM_REGISTRATIONS,
        "PB-DX39 r7: the emblem population moved DOWN to {}. That is not a problem, but the \
         reasoning in this row's doc names these members explicitly; re-take the figure and \
         lower the ratchet rather than leaving slack. Members: {emblems:#?}",
        emblems.len()
    );

    // Non-vacuity floor: the walk must find live-path registrations at all, or the filters
    // above are selecting from an empty set and both ratchets measure nothing. Measured at
    // HEAD: 209 registrations, 188 of them source-relative.
    let all = live_path_registrations();
    assert!(
        all.len() >= 100,
        "PB-DX39 r7: the `all_cards()` walk found only {} live-path continuous-effect \
         registrations (209 at HEAD); the walk has gone vacuous",
        all.len()
    );
    let source_relative: BTreeSet<String> =
        SOURCE_RELATIVE_ARMS.iter().map(|s| s.to_string()).collect();
    assert!(
        all.iter()
            .filter(|r| source_relative.contains(&r.filter))
            .count()
            >= 100,
        "PB-DX39 r7: fewer than 100 of the live-path registrations are source-relative (188 \
         at HEAD); either the corpus moved a great deal or the filter-name extraction has \
         broken and both ratchets are selecting from noise"
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// Census report
// ─────────────────────────────────────────────────────────────────────────────

/// PB-DX8's rule: a figure that no test prints is a figure that was transcribed. Run with
/// `-- --nocapture`.
#[test]
fn t_census_report() {
    let arms = filter_arms();
    let src_rel = source_relative_arm_names();
    println!("\n=== PB-DX39 census (printed, never transcribed) ===");
    println!(
        "effect_applies_to_inner filter arms          : {}",
        arms.len()
    );
    println!(
        "  of which source-relative (consume SourceView): {}",
        src_rel.len()
    );
    for name in &src_rel {
        println!("    - {name}");
    }
    let lki = live_lki_sites();
    println!(
        "LKI store sites (workspace-wide)             : {}",
        lki.len()
    );
    for ((f, n), count) in &lki {
        println!("    - {f} :: {n}  (x{count})");
    }
    let callers = live_at_resolution_callers();
    println!(
        "source_view_at_resolution callers            : {}",
        callers.len()
    );
    for (f, n) in &callers {
        println!("    - {f} :: {n}");
    }
    let all = live_path_registrations();
    println!(
        "live-path (CR 611.3a) registrations in corpus: {}",
        all.len()
    );
    let mut by_filter: BTreeMap<String, usize> = BTreeMap::new();
    for r in &all {
        *by_filter.entry(r.filter.clone()).or_default() += 1;
    }
    let sr: usize = all.iter().filter(|r| src_rel.contains(&r.filter)).count();
    println!("  of which source-relative                   : {sr}");
    let unprotected = unprotected_live_registrations();
    println!(
        "  source-relative AND duration != WhileSourceOnBattlefield (r7's ratchet): {}",
        unprotected.len()
    );
    for (holder, m) in &unprotected {
        println!("    - [{holder}] {m}");
    }
    println!("live-path registrations by filter variant:");
    for (k, v) in &by_filter {
        println!("    {v:>4}  {k}");
    }
    println!("=== end PB-DX39 census ===\n");
}
