//! PB-DX39 (`OOS-DX5-3` + `OOS-DX5-7`'s residual) corpus census — **source-relative
//! `EffectFilter`s and the last-known-information hole underneath them.**
//!
//! `rules/layers.rs::effect_applies_to` answers ~20 of its `EffectFilter` arms by
//! reading the effect's SOURCE object out of `state.objects` — its `controller`, its
//! `attached_to`, its `chosen_creature_type`, its `chosen_color`. Every one of those
//! arms answers `false` unconditionally when `state.objects.get(&source_id)` returns
//! `None`, i.e. once the source has left the battlefield.
//!
//! For a continuous effect generated by the RESOLUTION of a spell or ability
//! (CR 611.2c), the affected set is snapshotted at resolution by
//! `rules/layers.rs::snapshot_affected_set`. If the source is already gone by then,
//! that set comes out EMPTY and the effect does nothing at all. CR 608.2h and
//! CR 113.7a say it must instead answer from the source's **last known information**:
//! the ability exists independently of its source, and the source's characteristics
//! are those it last had on the battlefield.
//!
//! Two subjects this file exists to size:
//!
//! * `umezawas_jitte` — mode 0 is `EffectFilter::AttachedCreature` on an ACTIVATED
//!   ability. Gatherer ruling 2005-02-01: *"If the Jitte leaves the battlefield after
//!   the '+2/+2' mode is announced but before it resolves, the bonus is given to the
//!   creature that was most recently equipped once the ability resolves."*
//! * `mardu_ascendancy` — `Cost::SacrificeSelf` plus `EffectFilter::CreaturesYouControl`.
//!   The source sacrifices ITSELF as the cost, so it is *always* gone at resolution:
//!   the printed +0/+3 currently applies to NOBODY, every time.
//!
//! ## What this file measures
//!
//! | row | what it pins |
//! |---|---|
//! | R1 | the source-relative filter set, DERIVED from `layers.rs` rather than listed |
//! | R2 | every declared `EffectFilter` variant is classified by exactly one match arm |
//! | R3 | axis (i) — SACRIFICE-SELF: source-relative filter under a source-moving cost |
//! | R4 | axis (ii) — ATTACHED, split into resolution-time (in scope) and static (not) |
//! | R5 | axis (iii) — CONTROL: `AbilityDefinition::Spell` members, which must NOT move |
//! | R6 | the INVERSE ORACLE axis, and how far it fails to nest with the structural one |
//! | R7 | source gate: the three `ContinuousEffectDef` sites the walk must reach |
//! | R8 | source gate: the `Effect` nesting forms, recorded rather than relied upon |
//!
//! ## SR-36, and how the walk is enumerated
//!
//! Every population here is derived by enumerating `mtg_engine::all_cards()`. Nothing
//! is grepped out of `crates/card-defs/`: a variant named only inside a `// TODO`
//! comment is counted by a grep and is not in the corpus, which is the failure mode
//! `OOS-CARDS2-7`, `OOS-DX47-2`, PB-DX48 and PB-DX49 each recorded in turn.
//!
//! **The `Effect` nesting sites are not hand-listed, and deliberately so.** PB-DX26's
//! `/review` found an eleventh nesting site (`Effect::RollDice`'s
//! `Vec<(u32, u32, Effect)>`) that a hand-written `Box`/`Vec` count had missed, and
//! PB-DX26's walk carried a `_ => false` arm that could go shallow in silence. This
//! file walks the SERIALIZED form instead: each `AbilityDefinition` is turned into a
//! `serde_json::Value` and the resulting tree is walked generically, recording every
//! node that is shaped like a `ContinuousEffectDef` (an object carrying all four of
//! `layer` / `modification` / `filter` / `duration`). A generic JSON walk is total by
//! construction — it reaches a new `Effect` variant, a new `Vec<(..., Effect)>` tuple
//! form and a new `ContinuousEffectDef` site on the day each is added, with no arm to
//! forget. R8 records the source-level nesting forms as EVIDENCE of the enumeration,
//! not as the mechanism.
//!
//! ## CR citations (Architecture Invariant 8)
//!
//! * CR 611.2c — a continuous effect from a resolving spell or ability affects a set of
//!   objects determined when the effect begins; the set does not change afterwards.
//! * CR 608.2h — if an effect requires information about the game, it uses the current
//!   information, or last known information where the object has left the zone.
//! * CR 113.7a — an ability on the stack exists independently of its source.
//! * CR 611.3a — a continuous effect from a STATIC ability is not locked in; it applies
//!   continuously while the source is on the battlefield, so it has no LKI problem.
//!
//! **What membership asserts, and does NOT assert** (PB-DX4's `BASELINE` lesson):
//! membership means only that this def carries this shape. It says nothing about
//! whether the def is otherwise oracle-correct.

use mtg_engine::{all_cards, CardDefinition};
use serde_json::{Map, Value};
use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

// ─────────────────────────────────────────────────────────────────────────────
// Non-vacuity floor
// ─────────────────────────────────────────────────────────────────────────────

/// The corpus size floor. Every assertion in this file could be satisfied by an
/// empty scan, so each one asserts this first: a walk that returns nothing must
/// not be able to pass by reporting an empty set.
const CORPUS_FLOOR: usize = 1_800;

fn assert_denominator() -> usize {
    let n = all_cards().len();
    assert!(
        n >= CORPUS_FLOOR,
        "non-vacuity floor: all_cards() returned {n} defs, expected >= {CORPUS_FLOOR}. \
         A broken walk that scans nothing must not be able to satisfy the roster pins."
    );
    n
}

// ─────────────────────────────────────────────────────────────────────────────
// The source-relative filter set
// ─────────────────────────────────────────────────────────────────────────────

/// The `EffectFilter` variants whose `effect_applies_to` arm reads `effect.source`.
///
/// This list is PINNED here and DERIVED in R1 from `rules/layers.rs` itself, so the
/// definition of "source-relative" is the code's own, not this file's guess: a filter
/// is source-relative **iff** its match arm reads `effect.source`. R1 fails if the two
/// disagree in either direction.
const SOURCE_RELATIVE: &[&str] = &[
    "ArtifactsYouControl",
    "AttachedCreature",
    "AttachedLand",
    "AttachedPermanent",
    "AttackingCreaturesYouControl",
    "AttackingCreaturesYouControlWithSubtype",
    "CreaturesOpponentsControl",
    "CreaturesYouControl",
    "CreaturesYouControlExcludingSubtype",
    "CreaturesYouControlOfChosenColor",
    "CreaturesYouControlOfChosenType",
    "CreaturesYouControlWithColor",
    "CreaturesYouControlWithSubtype",
    "CreaturesYouControlWithSupertype",
    "LandsYouControl",
    "OtherCreaturesYouControl",
    "OtherCreaturesYouControlExcludingSubtype",
    "OtherCreaturesYouControlOfChosenType",
    "OtherCreaturesYouControlWithSubtype",
    "OtherCreaturesYouControlWithSubtypes",
];

/// The three `EffectFilter` variants that read the source's `attached_to` field —
/// axis (ii)'s subject (CR 301.5 Equipment, CR 301.6 Fortification, CR 303.4 Aura).
const ATTACHED_FILTERS: &[&str] = &["AttachedCreature", "AttachedLand", "AttachedPermanent"];

/// `Cost` variants that MOVE the source out of the battlefield as part of paying the
/// activation cost (CR 601.2h, reached for an activated ability by CR 602.2b). A
/// source-relative filter under any of these is *guaranteed* to resolve with the source
/// gone — it is not a race, it is certain.
///
/// **Not CR 118.12**, which the `/review` corrected: that rule is about a cost *"paid when
/// the spell or ability **resolves**"* (its own words), which is the opposite end of the
/// timeline from an activation cost and would have made the sentence above false.
///
/// The four are read off `pub enum Cost`; R3 prints which of them the corpus actually
/// uses, rather than assuming that "sacrifice" is the only shape in play.
const SOURCE_MOVING_COSTS: &[&str] = &[
    "SacrificeSelf",
    "ExileSelf",
    "DiscardSelf",
    "ExileSelfFromHand",
];

// ─────────────────────────────────────────────────────────────────────────────
// Generic JSON walk — total by construction
// ─────────────────────────────────────────────────────────────────────────────

/// The four keys every serialized `ContinuousEffectDef` carries. `condition` is
/// deliberately NOT required: it is `#[serde(default)]` and a future
/// `skip_serializing_if` would drop it, which must not blind the walk.
const CED_KEYS: &[&str] = &["layer", "modification", "filter", "duration"];

fn looks_like_ced(m: &Map<String, Value>) -> bool {
    CED_KEYS.iter().all(|k| m.contains_key(*k))
}

/// The variant name of an externally-tagged serde enum value.
///
/// Unit variants serialize to a bare string (`"CreaturesYouControl"`); every other
/// variant serializes to a one-key object (`{"CreaturesYouControlWithSubtype": ...}`).
fn variant_name(v: &Value) -> String {
    match v {
        Value::String(s) => s.clone(),
        Value::Object(m) if m.len() == 1 => m.keys().next().expect("len == 1").clone(),
        other => format!("<not-an-enum:{other}>"),
    }
}

/// Collect every `ContinuousEffectDef`-shaped node in a JSON tree, with the '/'-joined
/// key path that reached it.
///
/// Recursion continues THROUGH a matched node: a `LayerModification::AddActivatedAbility`
/// carries an `ActivatedAbility` whose own effect may itself apply a continuous effect,
/// and stopping at the first match would lose it.
fn collect_ced(v: &Value, path: &mut Vec<String>, out: &mut Vec<(String, String)>) {
    match v {
        Value::Object(m) => {
            if looks_like_ced(m) {
                out.push((path.join("/"), variant_name(&m["filter"])));
            }
            for (k, child) in m {
                path.push(k.clone());
                collect_ced(child, path, out);
                path.pop();
            }
        }
        Value::Array(a) => {
            for (i, child) in a.iter().enumerate() {
                path.push(i.to_string());
                collect_ced(child, path, out);
                path.pop();
            }
        }
        _ => {}
    }
}

/// Every string leaf in a JSON tree — used to spot unit-variant `Cost`s at any nesting
/// depth, so `Cost::Sequence([Mana, SacrificeSelf])` is found without a `Sequence` arm.
fn string_leaves(v: &Value, out: &mut BTreeSet<String>) {
    match v {
        Value::String(s) => {
            out.insert(s.clone());
        }
        Value::Object(m) => {
            for child in m.values() {
                string_leaves(child, out);
            }
        }
        Value::Array(a) => {
            for child in a {
                string_leaves(child, out);
            }
        }
        _ => {}
    }
}

/// Which `ContinuousEffectDef` site a JSON path landed on.
///
/// The three sites in `card_definition.rs` (R7 pins that there are exactly three):
/// * `AbilityDefinition::Static { continuous_effect }` — CR 611.3a, NOT locked in.
/// * `Effect::ApplyContinuousEffect { effect_def }` — CR 611.2c, locked in at resolution.
/// * `Effect::CreateEmblem { static_effects }` — CR 114.5: an emblem *"is neither a card
///   nor a permanent"*, and CR 114.2 puts it into the command zone. **That an emblem never
///   LEAVES the command zone is an engine measurement, not a rule** — no CR rule says it,
///   and the `/review` was right to refuse the claim: what is true is that nothing in
///   `effects/mod.rs` ever moves an emblem out, so CR 400.7 never retires its `ObjectId`
///   and its source cannot go missing. Recorded separately, not in scope.
fn site_of(path: &str) -> &'static str {
    let segs: Vec<&str> = path.split('/').collect();
    if segs.contains(&"effect_def") {
        "resolution"
    } else if segs.contains(&"static_effects") {
        "emblem"
    } else if path == "Static/continuous_effect" {
        "static"
    } else {
        "unclassified"
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// The census
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Occurrence {
    card_name: String,
    card_id: String,
    completeness: String,
    deck_legal: bool,
    face: String,
    ability_index: usize,
    ability_kind: String,
    /// Which of `SOURCE_MOVING_COSTS` this ability's cost carries, if any.
    source_moving_costs: Vec<String>,
    cost: String,
    filter: String,
    site: &'static str,
    path: String,
}

impl Occurrence {
    fn legal_tag(&self) -> &'static str {
        if self.deck_legal {
            "DECK-LEGAL"
        } else {
            "not-legal "
        }
    }
}

fn faces_of(def: &CardDefinition) -> Vec<(&'static str, &Vec<mtg_engine::AbilityDefinition>)> {
    let mut v: Vec<(&'static str, &Vec<mtg_engine::AbilityDefinition>)> =
        vec![("front", &def.abilities)];
    if let Some(f) = &def.back_face {
        v.push(("back", &f.abilities));
    }
    if let Some(f) = &def.adventure_face {
        v.push(("adventure", &f.abilities));
    }
    v
}

/// Every `(def, ability, source-relative filter)` triple in the corpus.
fn census() -> Vec<Occurrence> {
    let mut out = Vec::new();
    let source_relative: BTreeSet<&str> = SOURCE_RELATIVE.iter().copied().collect();

    for def in all_cards() {
        for (face, abilities) in faces_of(&def) {
            for (ability_index, ability) in abilities.iter().enumerate() {
                let json =
                    serde_json::to_value(ability).expect("AbilityDefinition derives Serialize");
                let ability_kind = variant_name(&json);

                // The ability's own cost field, if the variant has one.
                let cost_value: Option<&Value> = match &json {
                    Value::Object(m) if m.len() == 1 => {
                        m.values().next().and_then(|inner| inner.get("cost"))
                    }
                    _ => None,
                };
                let mut cost_strings = BTreeSet::new();
                if let Some(c) = cost_value {
                    string_leaves(c, &mut cost_strings);
                }
                let source_moving_costs: Vec<String> = SOURCE_MOVING_COSTS
                    .iter()
                    .filter(|m| cost_strings.contains(**m))
                    .map(|m| (*m).to_string())
                    .collect();
                let cost = cost_value
                    .map(|c| {
                        let s = serde_json::to_string(c).unwrap_or_default();
                        if s.len() > 70 {
                            format!("{}…", &s[..70])
                        } else {
                            s
                        }
                    })
                    .unwrap_or_else(|| "-".to_string());

                let mut found = Vec::new();
                collect_ced(&json, &mut Vec::new(), &mut found);
                for (path, filter) in found {
                    if !source_relative.contains(filter.as_str()) {
                        continue;
                    }
                    out.push(Occurrence {
                        card_name: def.name.clone(),
                        card_id: def.card_id.0.clone(),
                        completeness: def.completeness.kind().to_string(),
                        deck_legal: def.completeness.is_complete(),
                        face: face.to_string(),
                        ability_index,
                        ability_kind: ability_kind.clone(),
                        source_moving_costs: source_moving_costs.clone(),
                        cost: cost.clone(),
                        filter,
                        site: site_of(&path),
                        path,
                    });
                }
            }
        }
    }
    out.sort();
    out
}

fn names(occ: &[&Occurrence]) -> Vec<String> {
    let mut v: Vec<String> = occ.iter().map(|o| o.card_name.clone()).collect();
    v.sort();
    v.dedup();
    v
}

fn print_rows(label: &str, rows: &[&Occurrence]) {
    println!("\n── {label} ── ({} occurrences)", rows.len());
    if rows.is_empty() {
        println!("   (none)");
        return;
    }
    for o in rows {
        println!(
            "   {name:<34} [{legal}] {comp:<11} {face:<9} ab#{idx} {kind:<10} filter={filter:<42} site={site:<11} cost={cost}",
            name = o.card_name,
            legal = o.legal_tag(),
            comp = o.completeness,
            face = o.face,
            idx = o.ability_index,
            kind = o.ability_kind,
            filter = o.filter,
            site = o.site,
            cost = o.cost,
        );
        println!("      card_id={} path={}", o.card_id, o.path);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Axis selectors
// ─────────────────────────────────────────────────────────────────────────────

/// Axis (i): a source-relative filter reached at RESOLUTION time under a cost that
/// moves the source. Always live-wrong — the source is gone by construction.
fn axis_sacrifice_self(c: &[Occurrence]) -> Vec<&Occurrence> {
    c.iter()
        .filter(|o| !o.source_moving_costs.is_empty())
        .collect()
}

/// Axis (ii), in-scope half: an attached-to filter reached at RESOLUTION time.
fn axis_attached_resolution(c: &[Occurrence]) -> Vec<&Occurrence> {
    c.iter()
        .filter(|o| ATTACHED_FILTERS.contains(&o.filter.as_str()) && o.site == "resolution")
        .collect()
}

/// Axis (ii), out-of-scope half: the same filters on a STATIC ability.
///
/// CR 611.3a: a static ability's continuous effect is not locked in, and its source is
/// on the battlefield by construction — **CR 611.3b**, *"the effect applies at all times
/// that the permanent generating it is on the battlefield"*, which is the rule for a
/// STATIC ability. (CR 611.2b, which this line cited until the `/review`, is about the
/// *"for as long as"* durations of an effect generated by a RESOLUTION.) These are
/// printed so the distinction is visible, and asserted so they cannot drift into scope
/// unnoticed.
fn axis_attached_static(c: &[Occurrence]) -> Vec<&Occurrence> {
    c.iter()
        .filter(|o| ATTACHED_FILTERS.contains(&o.filter.as_str()) && o.site == "static")
        .collect()
}

/// Axis (iii): the CONTROL population — a spell's own resolution effect.
///
/// PB-DX5 already fixed these by snapshotting the affected set during resolution while
/// the spell is still in `state.objects`. They must stay green; the census prints them
/// so a future batch can see the class did not move.
fn axis_control_spell(c: &[Occurrence]) -> Vec<&Occurrence> {
    c.iter().filter(|o| o.ability_kind == "Spell").collect()
}

// ─────────────────────────────────────────────────────────────────────────────
// Inverse oracle axis
// ─────────────────────────────────────────────────────────────────────────────

/// Every oracle text a def carries — front face, back face AND adventure half.
///
/// PB-DX8 measured that reading `def.oracle_text` alone is blind to every transformed
/// face and every Adventure half, so all three are read here.
fn oracle_texts(def: &CardDefinition) -> Vec<(&'static str, String)> {
    let mut v = vec![("front", def.oracle_text.clone())];
    if let Some(f) = &def.back_face {
        v.push(("back", f.oracle_text.clone()));
    }
    if let Some(f) = &def.adventure_face {
        v.push(("adventure", f.oracle_text.clone()));
    }
    v
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct OracleHit {
    card_name: String,
    completeness: String,
    deck_legal: bool,
    face: String,
    line: String,
    cue: String,
}

/// The INVERSE axis: printed text that promises an "until end of turn" pump on an
/// ability whose cost sacrifices something or equips something.
///
/// Matched case-insensitively, per oracle LINE (oracle text puts one ability per line),
/// so "sacrifice" in one ability and "until end of turn" in another do not pair up.
///
/// This axis and the structural one **do not nest**, in either direction — PB-DX26,
/// PB-DX43 and PB-DX15a each recorded a batch that reported one as if it contained the
/// other. R6 prints both differences rather than a single overlap count.
fn oracle_axis() -> Vec<OracleHit> {
    let mut out = Vec::new();
    for def in all_cards() {
        for (face, text) in oracle_texts(&def) {
            for line in text.split('\n') {
                let lc = line.to_lowercase();
                if !lc.contains("until end of turn") {
                    continue;
                }
                let cue = if lc.contains("sacrifice") {
                    "sacrifice"
                } else if lc.contains("equip") {
                    "equip"
                } else {
                    continue;
                };
                out.push(OracleHit {
                    card_name: def.name.clone(),
                    completeness: def.completeness.kind().to_string(),
                    deck_legal: def.completeness.is_complete(),
                    face: face.to_string(),
                    line: line.trim().to_string(),
                    cue: cue.to_string(),
                });
            }
        }
    }
    out.sort();
    out.dedup();
    out
}

// ─────────────────────────────────────────────────────────────────────────────
// Source-file helpers (R1 / R2 / R7 / R8)
// ─────────────────────────────────────────────────────────────────────────────

fn workspace_root() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    // crates/engine -> crates -> workspace root
    p.pop();
    p.pop();
    p
}

/// Strip `//`-style line comments. Deliberately crude: it exists so a comment that
/// *mentions* `effect.source` cannot make a non-source-relative arm look source-relative.
fn strip_line_comments(src: &str) -> String {
    src.lines()
        .map(|l| match l.find("//") {
            Some(i) => &l[..i],
            None => l,
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// The matching `}` for the `{` at byte offset `open`.
fn matching_brace(src: &str, open: usize) -> Option<usize> {
    let bytes = src.as_bytes();
    assert_eq!(bytes[open], b'{');
    let mut depth = 0usize;
    for (i, b) in bytes.iter().enumerate().skip(open) {
        match b {
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return Some(i);
                }
            }
            _ => {}
        }
    }
    None
}

/// The `match &effect.filter { .. }` arms of `layers.rs::effect_applies_to`, as
/// `(variant name, arm text)`.
///
/// Arms are found by their indentation: the `match` sits at 4 spaces inside a free
/// function, so every top-level arm head starts at exactly 8. Anything deeper is inside
/// an arm body, and the `EffectFilter::SingleObject(_)` in the phased-out guard above
/// the match is outside the extracted body entirely.
fn effect_applies_to_arms() -> Vec<(String, String)> {
    let path = workspace_root().join("crates/engine/src/rules/layers.rs");
    let raw = std::fs::read_to_string(&path).expect("rules/layers.rs is readable");
    let src = strip_line_comments(&raw);

    let fn_at = src
        .find("\nfn effect_applies_to(")
        .expect("fn effect_applies_to( not found in layers.rs");
    let match_at = src[fn_at..]
        .find("match &effect.filter {")
        .map(|i| i + fn_at)
        .expect("match &effect.filter { not found inside effect_applies_to");
    let open = src[match_at..].find('{').expect("brace") + match_at;
    let close = matching_brace(&src, open).expect("unbalanced match body");
    let body = &src[open + 1..close];

    const HEAD: &str = "\n        EffectFilter::";
    let mut heads: Vec<usize> = Vec::new();
    let mut from = 0usize;
    while let Some(i) = body[from..].find(HEAD) {
        heads.push(from + i);
        from += i + HEAD.len();
    }
    assert!(
        !heads.is_empty(),
        "no `EffectFilter::` match arms found — the arm-head indentation convention in \
         layers.rs::effect_applies_to changed, and this gate is measuring nothing."
    );

    let mut arms = Vec::new();
    for (n, &start) in heads.iter().enumerate() {
        let end = heads.get(n + 1).copied().unwrap_or(body.len());
        let text = &body[start..end];
        let name_start = start + HEAD.len();
        let name: String = body[name_start..]
            .chars()
            .take_while(|c| c.is_alphanumeric() || *c == '_')
            .collect();
        arms.push((name, text.to_string()));
    }
    arms
}

/// Every variant name declared by `pub enum EffectFilter`.
fn declared_effect_filter_variants() -> BTreeSet<String> {
    let path = workspace_root().join("crates/card-types/src/state/continuous_effect.rs");
    let raw = std::fs::read_to_string(&path).expect("continuous_effect.rs is readable");
    let src = strip_line_comments(&raw);
    let at = src
        .find("pub enum EffectFilter {")
        .expect("pub enum EffectFilter not found");
    let open = src[at..].find('{').expect("brace") + at;
    let close = matching_brace(&src, open).expect("unbalanced enum body");
    let body = &src[open + 1..close];

    let mut out = BTreeSet::new();
    for line in body.lines() {
        // Variant heads are the only lines at exactly 4 spaces of indentation.
        if !line.starts_with("    ") || line.starts_with("     ") {
            continue;
        }
        let t = line.trim();
        let name: String = t
            .chars()
            .take_while(|c| c.is_alphanumeric() || *c == '_')
            .collect();
        if name.is_empty() {
            continue;
        }
        if !name.chars().next().expect("non-empty").is_uppercase() {
            continue;
        }
        out.insert(name);
    }
    out
}

/// Does this match arm name the effect's SOURCE at all?
///
/// The needle is the lowercase identifier `source` with a non-identifier byte in front of
/// it, so `effect.source`, `source_id`, `source_controller`, `source_view_at_resolution`
/// and a bare `source` binding all hit, while `resource` and the CAPITALISED
/// `EffectFilter::Source` arm head do not.
///
/// **The needle is deliberately about the SOURCE, not about one spelling of reaching it.**
/// PB-DX39's own fix replaces `state.objects.get(&effect.source)` with an LKI-aware
/// `SourceView` lookup (CR 608.2h), so a gate keyed on the literal `effect.source` would
/// have gone from 20 hits to 5 mid-refactor and reported the *classification* as changed
/// when only the *mechanism* had. Measured: it did exactly that, on this batch's own tree,
/// which is why this row is keyed one level up. *A gate written for one variant measures
/// that variant* — PB-DX26 -> PB-DX43 -> PB-DX45 -> PB-DX47 -> PB-DX51, and here.
///
/// What is being classified is a property of the FILTER, not of today's code: a filter is
/// source-relative when answering it requires the source object's own characteristics.
/// The membership must therefore survive the fix; only the mechanism changes.
fn names_the_source_identifier(arm_text: &str) -> bool {
    let bytes = arm_text.as_bytes();
    let mut from = 0usize;
    while let Some(i) = arm_text[from..].find("source") {
        let at = from + i;
        let prev_ok = at == 0 || {
            let p = bytes[at - 1];
            !(p.is_ascii_alphanumeric() || p == b'_')
        };
        if prev_ok {
            return true;
        }
        from = at + "source".len();
    }
    false
}

// ─────────────────────────────────────────────────────────────────────────────
// R1 — the source-relative set is DERIVED, not guessed
// ─────────────────────────────────────────────────────────────────────────────

/// A filter is source-relative **iff** its `effect_applies_to` arm reads
/// `effect.source` (CR 608.2h: that read is the last-known-information hole).
///
/// **Revert to watch red**: delete `effect.source` from any arm in `layers.rs`, or add
/// a name to / remove a name from `SOURCE_RELATIVE`.
#[test]
fn r1_source_relative_set_is_derived_from_layers_rs() {
    assert_denominator();
    let arms = effect_applies_to_arms();

    let derived: Vec<String> = arms
        .iter()
        .filter(|(_, text)| names_the_source_identifier(text))
        .map(|(name, _)| name.clone())
        .collect();
    let mut derived_sorted = derived.clone();
    derived_sorted.sort();

    let pinned: Vec<String> = SOURCE_RELATIVE.iter().map(|s| s.to_string()).collect();

    println!(
        "R1: {} match arms in effect_applies_to, {} of them read `effect.source`",
        arms.len(),
        derived_sorted.len()
    );
    for name in &derived_sorted {
        println!("    source-relative: {name}");
    }

    assert_eq!(
        derived_sorted, pinned,
        "the set of EffectFilter arms reading `effect.source` in layers.rs has changed. \
         PB-DX39's whole population is derived from this set — re-derive the census before \
         re-pinning it."
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// R2 — every declared filter variant is classified exactly once
// ─────────────────────────────────────────────────────────────────────────────

/// The census denominator: if a new `EffectFilter` variant is declared and its
/// `effect_applies_to` arm is added, this file must decide whether it is source-relative
/// before the census can be trusted.
///
/// **Revert to watch red**: add a variant to `pub enum EffectFilter` (the arm becomes a
/// compile error, so the honest revert is to add BOTH and leave it out of
/// `SOURCE_RELATIVE` — R1 then fires; delete an arm here and R2 fires).
#[test]
fn r2_every_declared_effect_filter_variant_has_a_match_arm() {
    assert_denominator();
    let declared = declared_effect_filter_variants();
    let arms = effect_applies_to_arms();
    let matched: BTreeSet<String> = arms.iter().map(|(n, _)| n.clone()).collect();

    println!(
        "R2: {} EffectFilter variants declared, {} match arms in effect_applies_to",
        declared.len(),
        matched.len()
    );
    let unmatched: Vec<&String> = declared.difference(&matched).collect();
    let unknown: Vec<&String> = matched.difference(&declared).collect();
    println!("    declared-but-unmatched: {unmatched:?}");
    println!("    matched-but-undeclared: {unknown:?}");

    assert_eq!(
        declared, matched,
        "the EffectFilter declaration and effect_applies_to's arm list disagree. \
         Every variant must be classified, or the source-relative census has a blind spot."
    );
    let source_relative: BTreeSet<String> = SOURCE_RELATIVE.iter().map(|s| s.to_string()).collect();
    assert!(
        source_relative.is_subset(&declared),
        "SOURCE_RELATIVE names a variant that is not declared: {:?}",
        source_relative.difference(&declared).collect::<Vec<_>>()
    );
}

// ─────────────────────────────────────────────────────────────────────────────
// R3 — axis (i), SACRIFICE-SELF
// ─────────────────────────────────────────────────────────────────────────────

/// Axis (i): every def whose source-relative filter sits under a cost that MOVES the
/// source. These are not races — the source is guaranteed gone at resolution, so the
/// effect applies to nobody, always (CR 608.2h is the rule being violated).
///
/// The member NAME SET is pinned, not a count: a count assertion passes when one member
/// leaves and another joins.
///
/// **Revert to watch red**: change `mardu_ascendancy`'s cost, or its filter.
///
/// **Disclosed, because it was measured rather than assumed**: R3 is the one roster row in
/// this file that does NOT discriminate the depth of the JSON walk. Executed — deleting
/// `collect_ced`'s `Value::Array` recursion reddens R4, R5, R6 and R9 and leaves R3
/// **GREEN**, because `mardu_ascendancy`'s only path is
/// `Activated/effect/ApplyContinuousEffect/effect_def` and carries no array segment at all.
/// A shallow walk would satisfy axis (i) completely. That is a fact about this axis's single
/// member, not about the walk, and it is stated here so nobody reads R3's green as evidence
/// the census reached anything nested.
#[test]
fn r3_sacrifice_self_axis_membership() {
    assert_denominator();
    let c = census();
    let rows = axis_sacrifice_self(&c);
    print_rows("AXIS (i) SACRIFICE-SELF", &rows);

    let cost_kinds: BTreeSet<&str> = rows
        .iter()
        .flat_map(|o| o.source_moving_costs.iter().map(|s| s.as_str()))
        .collect();
    println!("    source-moving cost kinds actually used by this axis: {cost_kinds:?}");
    println!(
        "    deck-legal `Complete`: {} occurrences / {} defs",
        rows.iter().filter(|o| o.deck_legal).count(),
        names(
            &rows
                .iter()
                .filter(|o| o.deck_legal)
                .copied()
                .collect::<Vec<_>>()
        )
        .len()
    );

    let expected: Vec<String> = AXIS_I_MEMBERS.iter().map(|s| s.to_string()).collect();
    assert_eq!(names(&rows), expected, "axis (i) membership moved");

    let expected_legal: Vec<String> = AXIS_I_DECK_LEGAL.iter().map(|s| s.to_string()).collect();
    let legal_rows: Vec<&Occurrence> = rows.iter().filter(|o| o.deck_legal).copied().collect();
    assert_eq!(
        names(&legal_rows),
        expected_legal,
        "axis (i) deck-legal (`Complete`) membership moved — this is the live blast radius"
    );
}

/// Axis (i) membership, taken from `t_dx39_census_report`'s own output.
///
/// **One member, and it is `partial`, so the axis's deck-legal blast radius is ZERO.**
/// That is reported rather than rounded away: `mardu_ascendancy` is live-wrong exactly as
/// the seed says, and it cannot appear in a legal deck today (`validate_deck` rejects
/// every non-`Complete` marker), so the axis is a CORRECTNESS defect with no *current*
/// player-facing exposure. `AXIS_I_DECK_LEGAL` is deliberately empty and is pinned that
/// way so that the day a `Complete` member arrives, this row goes red rather than quiet.
const AXIS_I_MEMBERS: &[&str] = &["Mardu Ascendancy"];
const AXIS_I_DECK_LEGAL: &[&str] = &[];

// ─────────────────────────────────────────────────────────────────────────────
// R4 — axis (ii), ATTACHED
// ─────────────────────────────────────────────────────────────────────────────

/// Axis (ii): `AttachedCreature` / `AttachedLand` / `AttachedPermanent`, split by site.
///
/// * RESOLUTION-time (CR 611.2c) — in scope. The equipment can leave in response to the
///   ability, and the snapshot then comes out empty.
/// * STATIC (CR 611.3a) — NOT in scope. A static ability's effect is not locked in and
///   its source is on the battlefield by construction.
///
/// Both sub-populations are pinned so the distinction cannot blur.
///
/// **Revert to watch red**: move `umezawas_jitte`'s mode-0 filter, or turn any static
/// equipment grant into an `Effect::ApplyContinuousEffect`.
#[test]
fn r4_attached_axis_membership_split_by_site() {
    assert_denominator();
    let c = census();
    let res = axis_attached_resolution(&c);
    let stat = axis_attached_static(&c);
    print_rows(
        "AXIS (ii) ATTACHED — resolution-time (IN SCOPE, CR 611.2c)",
        &res,
    );
    println!(
        "    deck-legal `Complete`: {} occurrences / {} defs",
        res.iter().filter(|o| o.deck_legal).count(),
        names(
            &res.iter()
                .filter(|o| o.deck_legal)
                .copied()
                .collect::<Vec<_>>()
        )
        .len()
    );
    println!(
        "\n── AXIS (ii) ATTACHED — static abilities (OUT OF SCOPE, CR 611.3a) ── ({} occurrences, {} defs)",
        stat.len(),
        names(&stat).len()
    );
    println!("    {:?}", names(&stat));

    let expected: Vec<String> = AXIS_II_RESOLUTION.iter().map(|s| s.to_string()).collect();
    assert_eq!(
        names(&res),
        expected,
        "axis (ii) resolution-time membership moved"
    );

    assert_eq!(
        names(&stat).len(),
        AXIS_II_STATIC_DEF_COUNT,
        "the static (CR 611.3a) attached population moved; it is the control for axis (ii) \
         and must not silently drift into or out of the resolution-time set"
    );
}

/// Axis (ii): exactly one resolution-time member, and it IS deck-legal `Complete` —
/// `umezawas_jitte`, the Gatherer ruling quoted in this module's header.
const AXIS_II_RESOLUTION: &[&str] = &["Umezawa's Jitte"];

/// The static (CR 611.3a) control population, as a DEF count.
///
/// A def count rather than a name set on purpose: this is a control, and pinning 44 names
/// would make every unrelated Equipment authoring commit edit this file. The count still
/// catches the movement that matters here — a def crossing between the static and the
/// resolution-time halves changes both numbers at once, and the resolution half is pinned
/// by name.
const AXIS_II_STATIC_DEF_COUNT: usize = 44;

// ─────────────────────────────────────────────────────────────────────────────
// R5 — axis (iii), CONTROL
// ─────────────────────────────────────────────────────────────────────────────

/// Axis (iii): source-relative filters on `AbilityDefinition::Spell` — an instant or
/// sorcery's own resolution effect.
///
/// PB-DX5 closed this class by snapshotting the affected set during resolution, while
/// the spell object is still in `state.objects` (CR 611.2c). **These must stay green.**
/// The census prints them so a later batch can see that PB-DX39 did not move the class.
///
/// **Revert to watch red**: add or remove a source-relative filter on any `Spell` ability.
#[test]
fn r5_control_axis_spell_membership() {
    assert_denominator();
    let c = census();
    let rows = axis_control_spell(&c);
    print_rows(
        "AXIS (iii) CONTROL — Spell resolution (PB-DX5, must NOT move)",
        &rows,
    );
    println!(
        "    deck-legal `Complete`: {} occurrences / {} defs",
        rows.iter().filter(|o| o.deck_legal).count(),
        names(
            &rows
                .iter()
                .filter(|o| o.deck_legal)
                .copied()
                .collect::<Vec<_>>()
        )
        .len()
    );

    let expected: Vec<String> = AXIS_III_MEMBERS.iter().map(|s| s.to_string()).collect();
    assert_eq!(
        names(&rows),
        expected,
        "axis (iii) CONTROL membership moved"
    );
}

/// Axis (iii): the CONTROL population. 7 defs, of which 4 are deck-legal `Complete`.
const AXIS_III_MEMBERS: &[&str] = &[
    "Finale of Devastation",
    "Goblin Surprise",
    "Goblin War Party",
    "Return of the Wildspeaker",
    "Triumph of the Hordes",
    "Unbreakable Formation",
    "You See a Pair of Goblins",
];

// ─────────────────────────────────────────────────────────────────────────────
// R9 — the whole exposed class, and the residual the three axes do not name
// ─────────────────────────────────────────────────────────────────────────────

/// Axis (iv), unnamed by the criterion and recorded anyway: every OTHER resolution-time
/// source-relative occurrence — an `Activated` / `Triggered` / `LoyaltyAbility` /
/// `SagaChapter` ability whose cost does NOT move the source and whose filter is not an
/// attached-to one.
///
/// These are not "always wrong" like axis (i) and they are not already fixed like axis
/// (iii): they are RACES. CR 608.2h still governs — if the source leaves the battlefield
/// in response to the ability (bounce, sacrifice outlet, removal), `snapshot_affected_set`
/// runs with `state.objects.get(&source_id) == None` and the affected set comes out empty.
/// The three named axes are a subset of this class, so pinning the whole class by def name
/// is what stops a fourth shape arriving unseen.
fn axis_other_resolution(c: &[Occurrence]) -> Vec<&Occurrence> {
    c.iter()
        .filter(|o| {
            o.site == "resolution"
                && o.source_moving_costs.is_empty()
                && !ATTACHED_FILTERS.contains(&o.filter.as_str())
                && o.ability_kind != "Spell"
        })
        .collect()
}

/// Pins the FULL resolution-time exposed class by def name — the union of axes (i), (ii,
/// resolution half), (iii) and (iv).
///
/// **Revert to watch red**: move any resolution-time source-relative filter onto or off a
/// def, or convert one of these abilities to `AbilityDefinition::Static`.
#[test]
fn r9_the_whole_resolution_time_class_is_pinned_by_name() {
    assert_denominator();
    let c = census();
    let all_res: Vec<&Occurrence> = c.iter().filter(|o| o.site == "resolution").collect();
    let other = axis_other_resolution(&c);
    print_rows(
        "AXIS (iv) OTHER resolution-time — races, not certainties (CR 608.2h)",
        &other,
    );
    println!(
        "    axis (iv): {} occurrences / {} defs / {} deck-legal defs",
        other.len(),
        names(&other).len(),
        names(
            &other
                .iter()
                .filter(|o| o.deck_legal)
                .copied()
                .collect::<Vec<_>>()
        )
        .len()
    );
    println!(
        "\nR9: whole resolution-time class = {} occurrences / {} defs / {} deck-legal defs",
        all_res.len(),
        names(&all_res).len(),
        names(
            &all_res
                .iter()
                .filter(|o| o.deck_legal)
                .copied()
                .collect::<Vec<_>>()
        )
        .len()
    );

    let expected: Vec<String> = RESOLUTION_CLASS_DEFS
        .iter()
        .map(|s| s.to_string())
        .collect();
    assert_eq!(
        names(&all_res),
        expected,
        "the resolution-time source-relative class moved. This is PB-DX39's whole blast \
         radius — re-derive it before re-pinning."
    );

    // The three named axes plus axis (iv) must exhaust the class: a fifth shape would
    // otherwise sit in the census, be counted in `all_res`, and be described by nothing.
    let named = axis_sacrifice_self(&c).len()
        + axis_attached_resolution(&c).len()
        + axis_control_spell(&c).len()
        + other.len();
    assert_eq!(
        named,
        all_res.len(),
        "the four axes do not partition the resolution-time class; some occurrence is \
         counted twice or not at all"
    );
}

/// Every def carrying a source-relative filter reached at RESOLUTION time (CR 611.2c),
/// taken from `r9`'s own output. 29 defs; 21 of them deck-legal `Complete`.
const RESOLUTION_CLASS_DEFS: &[&str] = &[
    "Battle Cry Goblin",
    "Binding the Old Gods",
    "Castle Embereth",
    "Crashing Drawbridge",
    "Craterhoof Behemoth",
    "Elspeth, Storm Slayer",
    "Elvish Warmaster",
    "Ezuri, Renegade Leader",
    "Felidar Retreat",
    "Finale of Devastation",
    "Goblin Bushwhacker",
    "Goblin Surprise",
    "Goblin War Party",
    "Goldnight Commander",
    "Goro-Goro, Disciple of Ryusei",
    "Kolaghan, the Storm's Fury",
    "Lathliss, Dragon Queen",
    "Mardu Ascendancy",
    "Massacre Wurm",
    "Mirror Entity",
    "Purphoros, God of the Forge",
    "Return of the Wildspeaker",
    "Sarkhan Vol",
    "Triumph of the Hordes",
    "Umezawa's Jitte",
    "Unbreakable Formation",
    "Vault of the Archangel",
    "Vito, Thorn of the Dusk Rose",
    "You See a Pair of Goblins",
];

// ─────────────────────────────────────────────────────────────────────────────
// R6 — the inverse oracle axis
// ─────────────────────────────────────────────────────────────────────────────

/// The two axes do not nest, and R6 prints BOTH differences rather than an overlap.
///
/// **Revert to watch red**: change either needle, or author a matching def.
#[test]
fn r6_inverse_oracle_axis_does_not_nest_with_the_structural_one() {
    assert_denominator();
    let hits = oracle_axis();
    let c = census();
    let structural: BTreeSet<String> = c.iter().map(|o| o.card_name.clone()).collect();

    println!("\n── INVERSE ORACLE AXIS ── ({} printed lines)", hits.len());
    for h in &hits {
        let tag = if structural.contains(&h.card_name) {
            "IN-STRUCTURAL"
        } else {
            "oracle-only  "
        };
        println!(
            "   [{tag}] {name:<34} [{legal}] {comp:<11} {face:<9} cue={cue:<9} | {line}",
            name = h.card_name,
            legal = if h.deck_legal {
                "DECK-LEGAL"
            } else {
                "not-legal "
            },
            comp = h.completeness,
            face = h.face,
            cue = h.cue,
            line = h.line,
        );
    }

    let oracle_names: BTreeSet<String> = hits.iter().map(|h| h.card_name.clone()).collect();
    let oracle_only: Vec<String> = oracle_names.difference(&structural).cloned().collect();
    let structural_only: Vec<String> = structural.difference(&oracle_names).cloned().collect();
    println!(
        "\n   oracle-axis defs NOT in the structural population ({}): {oracle_only:?}",
        oracle_only.len()
    );
    println!(
        "   structural defs NOT on the oracle axis ({}): {structural_only:?}",
        structural_only.len()
    );

    assert!(
        !hits.is_empty(),
        "non-vacuity: the inverse oracle axis matched nothing at all, which means the \
         needle is broken rather than that the corpus is clean"
    );
    assert_eq!(
        oracle_only,
        ORACLE_ONLY
            .iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>(),
        "the oracle-only half of the inverse axis moved"
    );
}

/// The half of the inverse oracle axis the STRUCTURAL census cannot see.
///
/// 13 of the 16 oracle-axis defs are not in the structural population at all — they print
/// an "until end of turn" pump on a sacrifice or equip ability and reach it through a
/// filter that is NOT source-relative (`Source`, `SingleObject`, `DeclaredTarget`,
/// `AllCreaturesWithSubtype`), or do not lower the clause at all. The reverse difference is
/// larger still (144 structural defs are not on this axis), so the two axes do not nest in
/// EITHER direction. Reporting one as if it contained the other is the error PB-DX26,
/// PB-DX43 and PB-DX15a each recorded.
const ORACLE_ONLY: &[&str] = &[
    "Ainok Strike Leader",
    "Alseid of Life's Bounty",
    "Boromir, Warden of the Tower",
    "Captain Lannery Storm",
    "Goblin Lookout",
    "Goblin Sledder",
    "Grim Hireling",
    "Lena, Selfless Champion",
    "Prossh, Skyraider of Kher",
    "Skemfar Elderhall",
    "Torch Courier",
    "Umbral Mantle",
    "Yahenni, Undying Partisan",
];

// ─────────────────────────────────────────────────────────────────────────────
// R7 — source gate: the ContinuousEffectDef sites the walk must reach
// ─────────────────────────────────────────────────────────────────────────────

/// The walk must be able to reach every place a `ContinuousEffectDef` can be authored.
/// The generic JSON walk reaches all of them by construction; this row RECORDS how many
/// there are, so a fourth site arrives loudly rather than as a silent zero in the census.
///
/// **Revert to watch red**: add a `ContinuousEffectDef` field anywhere in
/// `card_definition.rs`, or delete one.
#[test]
fn r7_continuous_effect_def_sites_are_recorded() {
    assert_denominator();
    let path = workspace_root().join("crates/card-types/src/cards/card_definition.rs");
    let raw = std::fs::read_to_string(&path).expect("card_definition.rs is readable");
    let src = strip_line_comments(&raw);
    let occurrences = src.matches("ContinuousEffectDef").count();
    println!(
        "R7: {occurrences} non-comment occurrences of `ContinuousEffectDef` in card_definition.rs"
    );

    let c = census();
    let sites: BTreeMap<&str, usize> = c.iter().fold(BTreeMap::new(), |mut m, o| {
        *m.entry(o.site).or_insert(0) += 1;
        m
    });
    println!("R7: census site histogram: {sites:?}");

    assert_eq!(
        occurrences, CED_SOURCE_OCCURRENCES,
        "the number of `ContinuousEffectDef` mentions in card_definition.rs moved — a new \
         authoring site may have appeared that the census now reaches but nobody classified"
    );
    assert!(
        !c.iter().any(|o| o.site == "unclassified"),
        "the census reached a ContinuousEffectDef by a path `site_of` cannot classify: {:?}",
        c.iter()
            .filter(|o| o.site == "unclassified")
            .map(|o| (&o.card_name, &o.path))
            .collect::<Vec<_>>()
    );
}

/// Three authoring sites plus the `pub struct` declaration itself.
const CED_SOURCE_OCCURRENCES: usize = 4;

// ─────────────────────────────────────────────────────────────────────────────
// R8 — source gate: the Effect nesting forms, as evidence
// ─────────────────────────────────────────────────────────────────────────────

/// How the nesting sites were enumerated, recorded rather than relied upon.
///
/// The census does NOT walk `Effect` with a hand-written `match` — it walks the
/// serialized JSON, which is total by construction and therefore cannot go shallow when
/// a twelfth nesting form is added (PB-DX26's `Vec<(u32, u32, Effect)>` was exactly that
/// twelfth form, and its hand-written walk and its own gate were blind to it together).
///
/// This row prints the source-level forms so the enumeration is auditable, and asserts
/// the total so that a NEW form is visible in the record even though it cannot break the
/// walk. It is EVIDENCE, not the mechanism — stated so nobody reads it as the safety net.
#[test]
fn r8_effect_nesting_forms_report() {
    assert_denominator();
    let path = workspace_root().join("crates/card-types/src/cards/card_definition.rs");
    let raw = std::fs::read_to_string(&path).expect("card_definition.rs is readable");
    let src = strip_line_comments(&raw);
    let at = src
        .find("pub enum Effect {")
        .expect("pub enum Effect not found");
    let open = src[at..].find('{').expect("brace") + at;
    let close = matching_brace(&src, open).expect("unbalanced Effect body");
    let body = &src[open + 1..close];

    let boxed = body.matches("Box<Effect>").count();
    let vecs = body.matches("Vec<Effect>").count();
    let tuple_vecs = body
        .lines()
        .filter(|l| l.contains("Vec<(") && l.contains("Effect)"))
        .count();
    println!(
        "R8: `Effect` enum body nesting forms — Box<Effect>: {boxed}, Vec<Effect>: {vecs}, \
         Vec<(.., Effect)>: {tuple_vecs}, total {}",
        boxed + vecs + tuple_vecs
    );
    println!(
        "R8: the census does NOT depend on this count — it walks serialized JSON, which is \
         total by construction. This row is evidence of the enumeration, not the mechanism."
    );

    assert_eq!(
        boxed + vecs + tuple_vecs,
        EFFECT_NESTING_FORMS,
        "the `Effect` enum gained or lost a nesting form. The JSON walk still covers it; \
         re-take this record and re-read the census."
    );
}

/// 8 `Box<Effect>` + 2 `Vec<Effect>` + 1 `Vec<(u32, u32, Effect)>` — the eleven forms
/// PB-DX26's `/review` arrived at, reproduced here by measurement rather than inherited.
const EFFECT_NESTING_FORMS: usize = 11;

// ─────────────────────────────────────────────────────────────────────────────
// The census report
// ─────────────────────────────────────────────────────────────────────────────

/// PRINTS the whole census. Every figure PB-DX39 publishes comes from this test's own
/// output — PB-DX8's rule, broken by its own author and again by PB-DX35: publish the
/// figure, never transcribe it.
///
/// Run with:
/// `cargo test -p mtg-engine --test core pb_dx39 -- --nocapture`
#[test]
fn t_dx39_census_report() {
    let denom = assert_denominator();
    let c = census();

    println!("\n════════════════════════════════════════════════════════════════════");
    println!("PB-DX39 source-relative EffectFilter census");
    println!("════════════════════════════════════════════════════════════════════");
    println!("scanned denominator (all_cards()):            {denom}");
    println!(
        "source-relative filter variants (from R1):    {}",
        SOURCE_RELATIVE.len()
    );
    println!("total source-relative occurrences:            {}", c.len());
    println!("distinct defs carrying one:                   {}", {
        let s: BTreeSet<&String> = c.iter().map(|o| &o.card_name).collect();
        s.len()
    });
    println!("of those, deck-legal `Complete`:              {}", {
        let s: BTreeSet<&String> = c
            .iter()
            .filter(|o| o.deck_legal)
            .map(|o| &o.card_name)
            .collect();
        s.len()
    });

    let by_site: BTreeMap<&str, usize> = c.iter().fold(BTreeMap::new(), |mut m, o| {
        *m.entry(o.site).or_insert(0) += 1;
        m
    });
    println!("\noccurrences by ContinuousEffectDef site:      {by_site:?}");

    let by_kind: BTreeMap<&str, usize> = c.iter().fold(BTreeMap::new(), |mut m, o| {
        *m.entry(o.ability_kind.as_str()).or_insert(0) += 1;
        m
    });
    println!("occurrences by AbilityDefinition kind:        {by_kind:?}");

    let by_filter: BTreeMap<&str, usize> = c.iter().fold(BTreeMap::new(), |mut m, o| {
        *m.entry(o.filter.as_str()).or_insert(0) += 1;
        m
    });
    println!("\noccurrences by filter variant:");
    for (f, n) in &by_filter {
        println!("   {f:<44} {n}");
    }

    let ax1 = axis_sacrifice_self(&c);
    let ax2r = axis_attached_resolution(&c);
    let ax2s = axis_attached_static(&c);
    let ax3 = axis_control_spell(&c);

    print_rows(
        "AXIS (i) SACRIFICE-SELF — always live-wrong (CR 608.2h)",
        &ax1,
    );
    print_rows(
        "AXIS (ii) ATTACHED — resolution-time, IN SCOPE (CR 611.2c)",
        &ax2r,
    );
    print_rows(
        "AXIS (ii) ATTACHED — static ability, OUT OF SCOPE (CR 611.3a)",
        &ax2s,
    );
    print_rows(
        "AXIS (iii) CONTROL — Spell resolution, fixed by PB-DX5, must NOT move",
        &ax3,
    );

    println!("\n── ALL resolution-time source-relative occurrences (the whole exposed class) ──");
    let all_res: Vec<&Occurrence> = c.iter().filter(|o| o.site == "resolution").collect();
    print_rows("resolution-site occurrences", &all_res);

    println!("\n── per-axis deck-legal `Complete` counts ──");
    println!(
        "   axis (i)  sacrifice-self:        {} occurrences / {} defs / {} deck-legal defs",
        ax1.len(),
        names(&ax1).len(),
        names(
            &ax1.iter()
                .filter(|o| o.deck_legal)
                .copied()
                .collect::<Vec<_>>()
        )
        .len()
    );
    println!(
        "   axis (ii) attached resolution:   {} occurrences / {} defs / {} deck-legal defs",
        ax2r.len(),
        names(&ax2r).len(),
        names(
            &ax2r
                .iter()
                .filter(|o| o.deck_legal)
                .copied()
                .collect::<Vec<_>>()
        )
        .len()
    );
    println!(
        "   axis (ii) attached static:       {} occurrences / {} defs / {} deck-legal defs",
        ax2s.len(),
        names(&ax2s).len(),
        names(
            &ax2s
                .iter()
                .filter(|o| o.deck_legal)
                .copied()
                .collect::<Vec<_>>()
        )
        .len()
    );
    println!(
        "   axis (iii) control (Spell):      {} occurrences / {} defs / {} deck-legal defs",
        ax3.len(),
        names(&ax3).len(),
        names(
            &ax3.iter()
                .filter(|o| o.deck_legal)
                .copied()
                .collect::<Vec<_>>()
        )
        .len()
    );

    // The inverse axis is printed by R6; its summary is repeated here so one run of this
    // test carries the whole published table.
    let hits = oracle_axis();
    let structural: BTreeSet<String> = c.iter().map(|o| o.card_name.clone()).collect();
    let oracle_names: BTreeSet<String> = hits.iter().map(|h| h.card_name.clone()).collect();
    println!("\n── INVERSE ORACLE AXIS summary ──");
    println!(
        "   printed lines matched:                    {}",
        hits.len()
    );
    println!(
        "   distinct defs:                            {}",
        oracle_names.len()
    );
    println!(
        "   already in the structural population:     {}",
        oracle_names.intersection(&structural).count()
    );
    println!(
        "   ORACLE-ONLY (not structural):             {:?}",
        oracle_names.difference(&structural).collect::<Vec<_>>()
    );
    println!("════════════════════════════════════════════════════════════════════\n");
}
