//! PB-DX5 roster sweep: which card defs generate a continuous effect at *resolution*
//! (`Effect::ApplyContinuousEffect`), and with which `EffectFilter`.
//!
//! CR **611.2c**: "If a continuous effect generated by the resolution of a spell or ability
//! modifies the characteristics or changes the controller of any objects, the set of objects
//! it affects is determined when that continuous effect begins. After that point, the set
//! won't change."
//!
//! Every `LayerModification` variant either modifies characteristics or is `SetController`,
//! so CR 611.2c applies to *every* effect this sweep finds -- the filter variant only
//! changes how visible the bug is, not whether the rule applies.
//!
//! **Enumerated from `all_cards()`, not grep (SR-34/36).** The dispatch brief's roster came
//! from a per-file grep conjunction ("file mentions `ApplyContinuousEffect`" AND "file
//! mentions `EffectFilter::All*`"), which can pair an effect in one ability with a filter in
//! a different one. This walk reads each `ApplyContinuousEffect`'s *own* `effect_def.filter`,
//! so the pairing is real by construction.

use mtg_engine::all_cards;
use std::collections::{BTreeMap, BTreeSet};

/// Serde variant name of an `EffectFilter` value: unit variants serialize as a bare string
/// (`"AllCreatures"`), struct/newtype variants as a single-key object (`{"SingleObject": 7}`).
/// PB-DP10's gate-integrity finding is exactly this: an object-key-only walk is blind to the
/// unit-variant shape, so both are handled here.
fn variant_name(v: &serde_json::Value) -> Option<String> {
    match v {
        serde_json::Value::String(s) => Some(s.clone()),
        serde_json::Value::Object(m) if m.len() == 1 => m.keys().next().cloned(),
        _ => None,
    }
}

/// Recursively collect the filter-variant name of every `ApplyContinuousEffect` in the tree.
fn collect_filters(v: &serde_json::Value, out: &mut Vec<String>) {
    match v {
        serde_json::Value::Object(m) => {
            if let Some(inner) = m.get("ApplyContinuousEffect") {
                if let Some(f) = inner.get("effect_def").and_then(|d| d.get("filter")) {
                    if let Some(name) = variant_name(f) {
                        out.push(name);
                    }
                }
            }
            for val in m.values() {
                collect_filters(val, out);
            }
        }
        serde_json::Value::Array(a) => {
            for val in a {
                collect_filters(val, out);
            }
        }
        _ => {}
    }
}

/// Reports the full roster of resolution-generated continuous effects by filter variant.
///
/// Diagnostic + non-vacuity floor, deliberately not an exact pin: routine card authoring
/// adds members to this class constantly, and the PB-DX5 engine fix is filter-agnostic, so
/// an exact count would be a flaky gate that guards nothing the fix depends on.
#[test]
fn pb_dx5_resolution_continuous_effect_roster() {
    let defs = all_cards();

    // filter variant -> set of card names
    let mut by_filter: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    let mut all_names: BTreeSet<String> = BTreeSet::new();

    for def in &defs {
        let json = serde_json::to_value(def).expect("CardDefinition serializes");
        let mut filters = Vec::new();
        collect_filters(&json, &mut filters);
        for f in filters {
            by_filter.entry(f).or_default().insert(def.name.clone());
            all_names.insert(def.name.clone());
        }
    }

    eprintln!("PB-DX5 roster (from all_cards(), not grep) -- CR 611.2c affected sets:");
    for (filter, names) in &by_filter {
        eprintln!("  {filter}: {} defs", names.len());
        for n in names {
            eprintln!("      {n}");
        }
    }
    eprintln!("  TOTAL distinct defs: {}", all_names.len());

    assert!(
        !all_names.is_empty(),
        "PB-DX5 roster walk found nothing -- the walk went vacuous (serde rename or a new \
         nesting site the recursion misses)"
    );
}

/// A filter is "mass" (multi-object -- the class CR 611.2c is visible on) unless it
/// resolves to a single object at `Effect::ApplyContinuousEffect` execution time.
/// `SingleObject` needs no resolution; `DeclaredTarget`/`Source`/`TriggeringCreature`/
/// `CreaturesControlledByDefendingPlayer`/`AllCreaturesExcludingChosenSubtype` are all
/// substituted into `SingleObject` (the first three) or a concrete mass filter (the last
/// two) before storage -- see `effects/mod.rs`'s `match &effect_def.filter` block at the
/// top of the `ApplyContinuousEffect` arm. `CreaturesControlledByDefendingPlayer` and
/// `AllCreaturesExcludingChosenSubtype` substitute INTO a mass filter
/// (`CreaturesControlledBy`/`AllCreaturesExcludingSubtype`), so a def whose `filter` field
/// literally reads one of those two placeholder names is *itself* a mass-filter def by the
/// time the effect is stored, and is counted as mass here.
fn is_mass_filter(name: &str) -> bool {
    !matches!(
        name,
        "SingleObject" | "DeclaredTarget" | "Source" | "TriggeringCreature"
    )
}

/// PB-DX5 §9 (test): the mass-filter roster, split by `Completeness`, re-reported by
/// completeness rather than pinned to an exact count -- routine authoring changes both
/// numbers constantly, and the engine fix is filter-agnostic, so an exact pin would guard
/// nothing the fix depends on. The plan's "37 (28/8/1)" was itself wrong -- its own table
/// already listed 38 rows summing to 29 `Complete`, an arithmetic slip nobody re-added.
/// Measured here: **38 mass-filter defs, 29 `Complete`, 8 `partial`, 1 `known_wrong`**. This
/// test re-measures it every run and prints the actual numbers so the close notes quote a
/// live count, not a number in prose.
#[test]
fn pb_dx5_mass_filter_roster_by_completeness() {
    let defs = all_cards();

    let mut mass_by_completeness: BTreeMap<&'static str, BTreeSet<String>> = BTreeMap::new();

    for def in &defs {
        let json = serde_json::to_value(def).expect("CardDefinition serializes");
        let mut filters = Vec::new();
        collect_filters(&json, &mut filters);
        if filters.iter().any(|f| is_mass_filter(f)) {
            let bucket = match &def.completeness {
                mtg_engine::Completeness::Complete => "Complete",
                mtg_engine::Completeness::Partial(_) => "Partial",
                mtg_engine::Completeness::KnownWrong(_) => "KnownWrong",
                mtg_engine::Completeness::Inert(_) => "Inert",
            };
            mass_by_completeness
                .entry(bucket)
                .or_default()
                .insert(def.name.clone());
        }
    }

    let total: usize = mass_by_completeness.values().map(|s| s.len()).sum();
    eprintln!("PB-DX5 mass-filter roster by completeness (measured, not asserted exact):");
    for (bucket, names) in &mass_by_completeness {
        eprintln!("  {bucket}: {} defs", names.len());
        for n in names {
            eprintln!("      {n}");
        }
    }
    eprintln!("  TOTAL mass-filter defs: {total}");

    assert!(
        !mass_by_completeness
            .get("Complete")
            .map(|s| s.is_empty())
            .unwrap_or(true),
        "PB-DX5's whole premise is that at least one Complete, deck-legal def uses a mass \
         filter -- this floor guards against the walk going vacuous, not against the count \
         changing"
    );
}
