//! PB-DX5 roster sweep: which card defs generate a continuous effect at *resolution*
//! (`Effect::ApplyContinuousEffect`), and with which `EffectFilter`.
//!
//! CR **611.2c**: "If a continuous effect generated by the resolution of a spell or ability
//! modifies the characteristics or changes the controller of any objects, the set of objects
//! it affects is determined when that continuous effect begins. After that point, the set
//! won't change."
//!
//! Every `LayerModification` variant either modifies characteristics or is `SetController`,
//! so CR 611.2c applies to *every* effect this sweep finds -- the filter variant only
//! changes how visible the bug is, not whether the rule applies.
//!
//! **Enumerated from `all_cards()`, not grep (SR-34/36).** The dispatch brief's roster came
//! from a per-file grep conjunction ("file mentions `ApplyContinuousEffect`" AND "file
//! mentions `EffectFilter::All*`"), which can pair an effect in one ability with a filter in
//! a different one. This walk reads each `ApplyContinuousEffect`'s *own* `effect_def.filter`,
//! so the pairing is real by construction.

use mtg_engine::all_cards;
use std::collections::{BTreeMap, BTreeSet};

/// Serde variant name of an `EffectFilter` value: unit variants serialize as a bare string
/// (`"AllCreatures"`), struct/newtype variants as a single-key object (`{"SingleObject": 7}`).
/// PB-DP10's gate-integrity finding is exactly this: an object-key-only walk is blind to the
/// unit-variant shape, so both are handled here.
fn variant_name(v: &serde_json::Value) -> Option<String> {
    match v {
        serde_json::Value::String(s) => Some(s.clone()),
        serde_json::Value::Object(m) if m.len() == 1 => m.keys().next().cloned(),
        _ => None,
    }
}

/// Recursively collect the filter-variant name of every `ApplyContinuousEffect` in the tree.
fn collect_filters(v: &serde_json::Value, out: &mut Vec<String>) {
    match v {
        serde_json::Value::Object(m) => {
            if let Some(inner) = m.get("ApplyContinuousEffect") {
                if let Some(f) = inner.get("effect_def").and_then(|d| d.get("filter")) {
                    if let Some(name) = variant_name(f) {
                        out.push(name);
                    }
                }
            }
            for val in m.values() {
                collect_filters(val, out);
            }
        }
        serde_json::Value::Array(a) => {
            for val in a {
                collect_filters(val, out);
            }
        }
        _ => {}
    }
}

/// Reports the full roster of resolution-generated continuous effects by filter variant.
///
/// Diagnostic + non-vacuity floor, deliberately not an exact pin: routine card authoring
/// adds members to this class constantly, and the PB-DX5 engine fix is filter-agnostic, so
/// an exact count would be a flaky gate that guards nothing the fix depends on.
#[test]
fn pb_dx5_resolution_continuous_effect_roster() {
    let defs = all_cards();

    // filter variant -> set of card names
    let mut by_filter: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    let mut all_names: BTreeSet<String> = BTreeSet::new();

    for def in &defs {
        let json = serde_json::to_value(def).expect("CardDefinition serializes");
        let mut filters = Vec::new();
        collect_filters(&json, &mut filters);
        for f in filters {
            by_filter.entry(f).or_default().insert(def.name.clone());
            all_names.insert(def.name.clone());
        }
    }

    eprintln!("PB-DX5 roster (from all_cards(), not grep) -- CR 611.2c affected sets:");
    for (filter, names) in &by_filter {
        eprintln!("  {filter}: {} defs", names.len());
        for n in names {
            eprintln!("      {n}");
        }
    }
    eprintln!("  TOTAL distinct defs: {}", all_names.len());

    assert!(
        !all_names.is_empty(),
        "PB-DX5 roster walk found nothing -- the walk went vacuous (serde rename or a new \
         nesting site the recursion misses)"
    );
}
