//! PB-DX39 (`OOS-DX5-3` + `OOS-DX5-7`'s residual): a source-relative
//! `EffectFilter` must survive the departure of its own source.
//!
//! **The defect.** `rules/layers.rs::effect_applies_to` has ~20 arms for
//! source-relative `EffectFilter` variants (`AttachedCreature`,
//! `AttachedLand`, `AttachedPermanent`, `CreaturesYouControl`,
//! `OtherCreaturesYouControl`, `CreaturesOpponentsControl`, …). Every one of
//! them opens with `state.objects.get(&source_id)` and answers `false`
//! unconditionally when that lookup is `None`:
//!
//! ```ignore
//! EffectFilter::AttachedCreature => { ...
//!     state.objects.get(&source_id).and_then(|src| src.attached_to)
//!         .map(|attached| attached == object_id).unwrap_or(false) }
//! ```
//!
//! For a continuous effect generated by the RESOLUTION of an ability
//! (CR 611.2c), the affected set is locked in by
//! `rules/layers.rs::snapshot_affected_set`, called from the
//! `Effect::ApplyContinuousEffect` arm in `effects/mod.rs`. That snapshot runs
//! `effect_applies_to` once per candidate. If the source has left the
//! battlefield by resolution time, every arm answers `false`, the locked set
//! comes out **EMPTY**, and the effect does nothing at all.
//!
//! * **CR 608.2h** — *"If the effect requires information from a specific
//!   object, including the source of the ability itself, the effect uses the
//!   current information of that object if it's in the public zone it was
//!   expected to be in; if it's no longer in that zone … the effect uses the
//!   object's last known information."*
//! * **CR 113.7a** — *"Once activated or triggered, an ability exists on the
//!   stack independently of its source. Destruction or removal of the source
//!   after that time won't affect the ability."*
//!
//! # The two subjects
//!
//! **Umezawa's Jitte** (`OOS-DX5-3`), mode 0 —
//! *"Equipped creature gets +2/+2 until end of turn"*, encoded as
//! `EffectFilter::AttachedCreature` + `LayerModification::ModifyBoth(2)`.
//! Gatherer ruling 2005-02-01: *"If the Jitte leaves the battlefield after the
//! '+2/+2' mode is announced but before it resolves, the bonus is given to the
//! creature that was most recently equipped once the ability resolves."*
//!
//! The SAME ruling block also says: *"Choosing the 'Equipped creature gets
//! +2/+2 until end of turn' mode does nothing if the Jitte isn't equipped to a
//! creature when the ability resolves."* So an empty set is **LEGAL** when the
//! Jitte is on the battlefield and unequipped, and **ILLEGAL** when the Jitte
//! has left the battlefield with a last-known attachment. A fix that made
//! `AttachedCreature` fall back to "anything" on an empty set would fix the
//! second and break the first. `t2` is the control for that direction.
//!
//! **Mardu Ascendancy** (`OOS-DX5-7` residual) —
//! *"Sacrifice this enchantment: Creatures you control get +0/+3 until end of
//! turn"*, encoded as `Cost::SacrificeSelf` + `EffectFilter::CreaturesYouControl`
//! + `LayerModification::ModifyToughness(3)`. The source sacrifices **itself**
//! as the activation cost, which `rules/abilities.rs` pays *before* the ability
//! is pushed to the stack — so the source is ALWAYS gone at resolution and the
//! +0/+3 currently applies to **nobody, in every game, every time**.
//!
//! # Fail-before evidence, EXECUTED at the unfixed merge base
//!
//! Every "RED" below was **observed**, not reasoned to: this whole file was run
//! against the tree before `rules::layers::source_view_at_resolution` existed,
//! and the reported `left` value is recorded beside each probe. It is quoted in
//! the batch's execution notes verbatim.
//!
//! | probe | subject | before the fix | after |
//! |-------|---------|----------------|-------|
//! | `dx39_t1_jitte_bonus_survives_the_jitte_being_destroyed_in_response` | Jitte | **RED — `left: Some(1)`, `right: Some(3)`** | green |
//! | `dx39_t2_jitte_unequipped_on_the_battlefield_pumps_nobody` | Jitte | GREEN — **CONTROL** | green |
//! | `dx39_t3_jitte_live_attachment_wins_while_the_source_is_alive` | Jitte | GREEN — **CONTROL** | green |
//! | `dx39_t4_mardu_sacrifice_self_pumps_every_creature_you_control` | Mardu | **RED — `left: Some(2)`, `right: Some(5)`** | green |
//! | `dx39_t5_mardu_does_not_pump_an_opponents_creature` | Mardu | **RED — `left: Some(2)`, `right: Some(5)`** on its "you control" half; the opponent half is a CONTROL | green |
//! | `dx39_t6_mardu_set_is_determined_at_resolution_not_activation` | Mardu | **RED — `left: Some(2)`, `right: Some(5)`** on its membership halves; the locked-in half is a CONTROL | green |
//!
//! **One coverage limit stated rather than left to be discovered.** `t6`'s third
//! leg (a creature that arrives AFTER resolution gets nothing — the CR 611.2c
//! "locked in" half) sits below two assertions that were RED before the fix, so
//! at the merge base that leg was **never reached**. It is a control that was
//! only ever executed against the fixed engine.
//!
//! Every probe carries a **non-vacuity floor**: it asserts the precondition it
//! depends on (the Jitte really was attached; the ability really did reach the
//! stack; the source really is gone from `state.objects`) so it cannot pass or
//! fail for a reason it does not describe (PB-DX15a: *"a probe passed VACUOUSLY
//! before it passed honestly"*).
//!
//! Assertions are on **layer-resolved P/T** (`calculate_characteristics`), never
//! on `ContinuousEffect::affected_set`: an assertion on the internal locked set
//! would be satisfied by a change that never reaches a player.
//!
//! # A note for whoever fixes this
//!
//! `GameState::capture_lki_snapshot` (`state/mod.rs`) gates the snapshot on
//! `LKI_RELEVANT_KEYWORDS = [Wither, Infect, Deathtouch, Lifelink]` — an SR-24
//! cost optimisation. Neither Umezawa's Jitte nor Mardu Ascendancy carries any
//! of the four, so **no LKI snapshot exists for either subject today**. Reading
//! `state.lki_object_snapshot(source_id)` alone will not make these green.
//! Stated as an observation about the tree, not as a prescription.

use mtg_engine::state::test_util;
use mtg_engine::state::GameStateError;
use mtg_engine::{
    all_cards, calculate_characteristics, card_name_to_id, enrich_spec_from_def, process_command,
    CardDefinition, CardRegistry, CounterType, GameEvent, GameState, GameStateBuilder, ObjectId,
    ObjectSpec, PlayerId, Step, Target, ZoneId,
};
use std::collections::HashMap;

// ── Helpers ───────────────────────────────────────────────────────────────────

fn p(n: u64) -> PlayerId {
    PlayerId(n)
}

fn load_defs() -> HashMap<String, CardDefinition> {
    all_cards()
        .into_iter()
        .map(|d| (d.name.clone(), d))
        .collect()
}

fn find_object(state: &GameState, name: &str) -> ObjectId {
    state
        .objects()
        .iter()
        .find(|(_, obj)| obj.characteristics.name == name)
        .map(|(id, _)| *id)
        .unwrap_or_else(|| panic!("object '{name}' not found"))
}

fn find_object_controlled_by(state: &GameState, name: &str, controller: PlayerId) -> ObjectId {
    state
        .objects()
        .iter()
        .find(|(_, obj)| {
            obj.characteristics.name == name
                && obj.controller == controller
                && obj.zone == ZoneId::Battlefield
        })
        .map(|(id, _)| *id)
        .unwrap_or_else(|| panic!("object '{name}' controlled by {controller:?} not found"))
}

fn find_in_zone(state: &GameState, name: &str, zone: ZoneId) -> ObjectId {
    state
        .objects()
        .iter()
        .find(|(_, obj)| obj.characteristics.name == name && obj.zone == zone)
        .map(|(id, _)| *id)
        .unwrap_or_else(|| panic!("object '{name}' not found in {zone:?}"))
}

fn power(state: &GameState, id: ObjectId) -> Option<i32> {
    calculate_characteristics(state, id).and_then(|c| c.power)
}

fn toughness(state: &GameState, id: ObjectId) -> Option<i32> {
    calculate_characteristics(state, id).and_then(|c| c.toughness)
}

fn activate(
    state: GameState,
    player: PlayerId,
    source: ObjectId,
    ability_index: usize,
    modes_chosen: Vec<usize>,
) -> Result<(GameState, Vec<GameEvent>), GameStateError> {
    process_command(
        state,
        mtg_engine::Command::ActivateAbility {
            player,
            source,
            ability_index,
            targets: Vec::<Target>::new(),
            discard_card: None,
            sacrifice_target: None,
            x_value: None,
            modes_chosen,
            hybrid_choices: vec![],
            phyrexian_life_payments: vec![],
        },
    )
}

fn pass_all(state: GameState, players: &[PlayerId]) -> GameState {
    let mut current = state;
    for &pl in players {
        let (s, _ev) = process_command(current, mtg_engine::Command::PassPriority { player: pl })
            .unwrap_or_else(|e| panic!("PassPriority by {pl:?} failed: {e:?}"));
        current = s;
    }
    current
}

/// The index a `Command::ActivateAbility` must name for the (single) MODAL
/// activated ability on `id`. Located by shape, never hardcoded — `OOS-DX26-3`
/// records that authoring another activated ability into a def silently
/// renumbers this.
fn modal_ability_index(state: &GameState, id: ObjectId) -> usize {
    calculate_characteristics(state, id)
        .unwrap_or_else(|| panic!("object {id:?} must have layer-resolved characteristics"))
        .activated_abilities
        .iter()
        .position(|a| a.modes.is_some())
        .unwrap_or_else(|| panic!("object {id:?} declares no modal activated ability"))
}

/// The index of the (single) activated ability on `id` whose cost sacrifices
/// the source itself. Same reason as [`modal_ability_index`].
fn sacrifice_self_ability_index(state: &GameState, id: ObjectId) -> usize {
    calculate_characteristics(state, id)
        .unwrap_or_else(|| panic!("object {id:?} must have layer-resolved characteristics"))
        .activated_abilities
        .iter()
        .position(|a| a.cost.sacrifice_self)
        .unwrap_or_else(|| panic!("object {id:?} declares no sacrifice-self activated ability"))
}

/// Two players, `card_name` enriched from the real corpus def and placed on
/// p1's battlefield with its static continuous effects registered, p1 holding
/// priority in its own precombat main. Mirrors `pb_dx26_equip_surface::setup`.
fn setup(card_name: &str, extra: Vec<ObjectSpec>) -> (GameState, ObjectId, PlayerId, PlayerId) {
    let p1 = p(1);
    let p2 = p(2);
    let defs = load_defs();

    let subject = enrich_spec_from_def(
        ObjectSpec::card(p1, card_name)
            .in_zone(ZoneId::Battlefield)
            .with_card_id(card_name_to_id(card_name)),
        &defs,
    );

    let mut builder = GameStateBuilder::new()
        .add_player(p1)
        .add_player(p2)
        .with_registry(CardRegistry::new(all_cards()))
        .object(subject);
    for spec in extra {
        builder = builder.object(spec);
    }
    let mut state = builder
        .active_player(p1)
        .at_step(Step::PreCombatMain)
        .build()
        .unwrap();

    state.turn_mut().priority_holder = Some(p1);

    let subject_id = find_object(&state, card_name);
    let card_id = state
        .objects()
        .get(&subject_id)
        .and_then(|o| o.card_id.clone());
    let registry = state.card_registry().clone();
    mtg_engine::rules::replacement::register_static_continuous_effects(
        &mut state,
        subject_id,
        card_id.as_ref(),
        &registry,
        false,
    );

    (state, subject_id, p1, p2)
}

// ── t1 — the Jitte defect ─────────────────────────────────────────────────────

#[test]
/// CR 608.2h / CR 113.7a / CR 611.2c + Gatherer ruling 2005-02-01: *"If the
/// Jitte leaves the battlefield after the '+2/+2' mode is announced but before
/// it resolves, the bonus is given to the creature that was most recently
/// equipped once the ability resolves."*
///
/// **RED at the unfixed merge base**, observed: `left: Some(1)`, `right:
/// Some(3)`. `EffectFilter::AttachedCreature`'s arm answered `false` for every
/// candidate once `state.objects.get(&jitte)` was `None`, so
/// `snapshot_affected_set` locked an EMPTY set and Creature A stayed 1/1.
fn dx39_t1_jitte_bonus_survives_the_jitte_being_destroyed_in_response() {
    let (mut state, jitte, p1, p2) = setup(
        "Umezawa's Jitte",
        vec![
            ObjectSpec::creature(p(1), "Creature A", 1, 1),
            ObjectSpec::creature(p(1), "Creature B", 1, 1),
        ],
    );
    let creature_a = find_object_controlled_by(&state, "Creature A", p1);
    let creature_b = find_object_controlled_by(&state, "Creature B", p1);

    // CR 301.5 / CR 702.6a: the Equipment is attached to Creature A.
    test_util::object_mut(&mut state, jitte)
        .unwrap()
        .attached_to = Some(creature_a);
    // CR 702.6a / the printed cost: "Remove a charge counter from Umezawa's Jitte:".
    test_util::object_mut(&mut state, jitte)
        .unwrap()
        .counters
        .insert(CounterType::Charge, 1);

    // ── non-vacuity floors ────────────────────────────────────────────────
    assert_eq!(
        state.objects().get(&jitte).and_then(|o| o.attached_to),
        Some(creature_a),
        "floor: the Jitte really is attached to Creature A before anything is activated"
    );
    assert_eq!(
        power(&state, creature_a),
        Some(1),
        "floor: Creature A starts 1/1, so a later Some(3) can only come from this ability"
    );

    let idx = modal_ability_index(&state, jitte);
    let (state2, _ev) = activate(state, p1, jitte, idx, vec![0]).expect("mode 0 activates");
    let mut state = state2;

    // ── non-vacuity floor: the ability really reached the stack ───────────
    assert_eq!(
        state.stack_objects().len(),
        1,
        "floor: the +2/+2 mode is on the stack (CR 602.2a) before the Jitte is destroyed"
    );

    // CR 400.7: destroying the Jitte moves it to its owner's graveyard and it
    // becomes a NEW object — the old ObjectId the stack entry names is retired.
    let (_new_id, _old) = test_util::move_object_to_zone(&mut state, jitte, ZoneId::Graveyard(p1))
        .expect("the Jitte can be put into its owner's graveyard");

    // ── non-vacuity floor: the source really is gone ──────────────────────
    assert!(
        state.objects().get(&jitte).is_none(),
        "floor: the ability's source ObjectId is no longer in state.objects — this is the \
         exact condition every source-relative EffectFilter arm answers `false` on"
    );
    assert_eq!(
        state.stack_objects().len(),
        1,
        "floor: CR 113.7a — the ability is still on the stack after its source is destroyed"
    );

    // Resolve the ability.
    let state = pass_all(state, &[p1, p2]);
    assert!(
        state.stack_objects().is_empty(),
        "floor: the ability resolved rather than being stranded on the stack"
    );

    assert_eq!(
        power(&state, creature_a),
        Some(3),
        "CR 608.2h + Jitte ruling 2005-02-01: the bonus goes to the creature that was most \
         recently equipped, even though the Jitte itself is gone"
    );
    assert_eq!(
        toughness(&state, creature_a),
        Some(3),
        "CR 608.2h: ModifyBoth(2) is +2/+2, not +2/+0"
    );
    assert_eq!(
        power(&state, creature_b),
        Some(1),
        "CR 301.5: Creature B was never the equipped creature and gets nothing — a fix that \
         widens AttachedCreature to 'anything' on an empty lookup is caught here"
    );
}

// ── t2 — CONTROL: the legal empty set ────────────────────────────────────────

#[test]
/// CR 301.5 + Gatherer ruling 2005-02-01: *"Choosing the 'Equipped creature
/// gets +2/+2 until end of turn' mode does nothing if the Jitte isn't equipped
/// to a creature when the ability resolves."*
///
/// **CONTROL — GREEN at the unfixed merge base and it must STAY green.** This is not
/// a gap. It is the direction a careless fix breaks: an `AttachedCreature` arm
/// that falls back to "every creature" (or to "the source's controller's
/// creatures") when the attachment lookup comes up empty would fix `t1` and
/// break this.
fn dx39_t2_jitte_unequipped_on_the_battlefield_pumps_nobody() {
    let (mut state, jitte, p1, p2) = setup(
        "Umezawa's Jitte",
        vec![
            ObjectSpec::creature(p(1), "Creature A", 1, 1),
            ObjectSpec::creature(p(1), "Creature B", 1, 1),
        ],
    );
    let creature_a = find_object_controlled_by(&state, "Creature A", p1);
    let creature_b = find_object_controlled_by(&state, "Creature B", p1);

    test_util::object_mut(&mut state, jitte)
        .unwrap()
        .counters
        .insert(CounterType::Charge, 1);

    // ── non-vacuity floors ────────────────────────────────────────────────
    assert_eq!(
        state.objects().get(&jitte).and_then(|o| o.attached_to),
        None,
        "floor: the Jitte is deliberately UNEQUIPPED"
    );
    assert!(
        state.objects().contains_key(&jitte),
        "floor: and it is still on the battlefield — the source is NOT gone, which is what \
         separates this control from t1"
    );

    let idx = modal_ability_index(&state, jitte);
    let (state, _ev) = activate(state, p1, jitte, idx, vec![0]).expect("mode 0 activates");
    assert_eq!(
        state.stack_objects().len(),
        1,
        "floor: the ability really reached the stack"
    );
    let state = pass_all(state, &[p1, p2]);
    assert!(
        state.stack_objects().is_empty(),
        "floor: the ability resolved"
    );

    assert_eq!(
        power(&state, creature_a),
        Some(1),
        "Jitte ruling 2005-02-01: an unequipped Jitte's +2/+2 mode does nothing"
    );
    assert_eq!(
        power(&state, creature_b),
        Some(1),
        "Jitte ruling 2005-02-01: ... to anybody"
    );
}

// ── t3 — CONTROL: the source is alive, the LIVE attachment wins ──────────────

#[test]
/// CR 611.2c + Gatherer ruling 2005-02-01: *"If the Jitte is moved after the
/// '+2/+2' mode is announced but before it resolves, the bonus is given to the
/// creature that is equipped WHEN THE ABILITY RESOLVES."*
///
/// **CONTROL — GREEN at the unfixed merge base and it must STAY green.** The Jitte is
/// on the battlefield at resolution, so CR 608.2h's *"uses the current
/// information of that object"* clause applies and no last-known information is
/// consulted at all. The Equipment is moved between activation and resolution
/// so that the live read and any captured-at-activation value genuinely
/// disagree: a fix that snapshots `attached_to` at ACTIVATION time instead of
/// falling back to LKI at RESOLUTION time is caught here.
fn dx39_t3_jitte_live_attachment_wins_while_the_source_is_alive() {
    let (mut state, jitte, p1, p2) = setup(
        "Umezawa's Jitte",
        vec![
            ObjectSpec::creature(p(1), "Creature A", 1, 1),
            ObjectSpec::creature(p(1), "Creature B", 1, 1),
        ],
    );
    let creature_a = find_object_controlled_by(&state, "Creature A", p1);
    let creature_b = find_object_controlled_by(&state, "Creature B", p1);

    test_util::object_mut(&mut state, jitte)
        .unwrap()
        .attached_to = Some(creature_a);
    test_util::object_mut(&mut state, jitte)
        .unwrap()
        .counters
        .insert(CounterType::Charge, 1);

    let idx = modal_ability_index(&state, jitte);
    let (mut state, _ev) = activate(state, p1, jitte, idx, vec![0]).expect("mode 0 activates");
    assert_eq!(
        state.stack_objects().len(),
        1,
        "floor: the ability really reached the stack"
    );

    // Move the Equipment to Creature B while the ability is still on the stack.
    // `Effect::AttachEquipment` is not used here deliberately: this probe is about
    // WHICH attachment the filter reads, not about the attach machinery.
    test_util::object_mut(&mut state, jitte)
        .unwrap()
        .attached_to = Some(creature_b);
    assert_eq!(
        state.objects().get(&jitte).and_then(|o| o.attached_to),
        Some(creature_b),
        "floor: the live attachment and the activation-time attachment genuinely disagree"
    );

    let state = pass_all(state, &[p1, p2]);
    assert!(
        state.stack_objects().is_empty(),
        "floor: the ability resolved"
    );

    assert_eq!(
        power(&state, creature_b),
        Some(3),
        "Jitte ruling 2005-02-01 (moved): the bonus goes to the creature equipped WHEN THE \
         ABILITY RESOLVES, because CR 608.2h reads current information while the source is \
         in the zone it was expected to be in"
    );
    assert_eq!(
        power(&state, creature_a),
        Some(1),
        "CR 611.2c: Creature A was equipped at ANNOUNCEMENT, which is not when the set is \
         determined"
    );
}

// ── t4 — the Mardu Ascendancy defect ─────────────────────────────────────────

#[test]
/// CR 608.2h / CR 113.7a / CR 611.2c. Mardu Ascendancy: *"Sacrifice this
/// enchantment: Creatures you control get +0/+3 until end of turn."*
/// `Cost::SacrificeSelf` is paid in `rules/abilities.rs` BEFORE the ability is
/// pushed to the stack (CR 601.2h/602.2b — costs are paid on activation), so
/// the source is gone from `state.objects` at every resolution of this ability,
/// in every game.
///
/// **RED at the unfixed merge base**, observed: `left: Some(2)`, `right:
/// Some(5)`. `EffectFilter::CreaturesYouControl`'s arm read
/// `state.objects.get(&source_id).map(|src| src.controller)`, got `None`, and
/// its `source_controller.is_some()` conjunct made every candidate `false` —
/// so the locked set was EMPTY and the +0/+3 reached nobody.
fn dx39_t4_mardu_sacrifice_self_pumps_every_creature_you_control() {
    let (state, mardu, p1, p2) = setup(
        "Mardu Ascendancy",
        vec![
            ObjectSpec::creature(p(1), "Bear One", 2, 2),
            ObjectSpec::creature(p(1), "Bear Two", 2, 2),
        ],
    );
    let bear_one = find_object_controlled_by(&state, "Bear One", p1);
    let bear_two = find_object_controlled_by(&state, "Bear Two", p1);

    // ── non-vacuity floors ────────────────────────────────────────────────
    assert_eq!(
        toughness(&state, bear_one),
        Some(2),
        "floor: Bear One starts 2/2, so a later Some(5) can only come from this ability"
    );
    assert_eq!(toughness(&state, bear_two), Some(2), "floor: and Bear Two");

    let idx = sacrifice_self_ability_index(&state, mardu);
    let (state, _ev) = activate(state, p1, mardu, idx, vec![]).expect("the ability activates");

    // ── non-vacuity floors: the cost was really paid and the ability is live ──
    assert!(
        state.objects().get(&mardu).is_none(),
        "floor: CR 601.2h — Cost::SacrificeSelf was paid, so the source ObjectId is retired \
         BEFORE the ability ever reaches the stack. This is the defect's precondition and it \
         is unconditional for this card."
    );
    assert_eq!(
        state.stack_objects().len(),
        1,
        "floor: CR 113.7a — the ability is on the stack even though its source is gone"
    );

    let state = pass_all(state, &[p1, p2]);
    assert!(
        state.stack_objects().is_empty(),
        "floor: the ability resolved"
    );

    assert_eq!(
        toughness(&state, bear_one),
        Some(5),
        "CR 608.2h: 'Creatures you control' is resolved from the source's last known \
         information, so Bear One gets +0/+3"
    );
    assert_eq!(
        toughness(&state, bear_two),
        Some(5),
        "CR 608.2h: ... and so does Bear Two"
    );
    assert_eq!(
        power(&state, bear_one),
        Some(2),
        "ModifyToughness(3) is +0/+3, not +3/+3"
    );
}

// ── t5 — the fix must not degenerate into "applies to everything" ────────────

#[test]
/// CR 608.2h + CR 109.5 ("you" = the source's controller). Both directions are
/// asserted on ONE board so that a fix which widens `CreaturesYouControl` into
/// `AllCreatures` when the source lookup fails is caught by the same drive that
/// proves the bonus applies at all.
///
/// **RED at the unfixed merge base** on its "you control" half (that half is
/// `t4`'s defect), observed: `left: Some(2)`, `right: Some(5)`. Its opponent
/// half is a **CONTROL**: it was green before the fix for the wrong reason (the
/// set was empty, so nobody was pumped) and must stay green for the right one.
fn dx39_t5_mardu_does_not_pump_an_opponents_creature() {
    let (state, mardu, p1, p2) = setup(
        "Mardu Ascendancy",
        vec![
            ObjectSpec::creature(p(1), "My Bear", 2, 2),
            ObjectSpec::creature(p(2), "Their Bear", 2, 2),
        ],
    );
    let mine = find_object_controlled_by(&state, "My Bear", p1);
    let theirs = find_object_controlled_by(&state, "Their Bear", p2);

    assert_eq!(toughness(&state, mine), Some(2), "floor: 2/2 to start");
    assert_eq!(toughness(&state, theirs), Some(2), "floor: 2/2 to start");
    assert_ne!(
        state.objects().get(&mine).map(|o| o.controller),
        state.objects().get(&theirs).map(|o| o.controller),
        "floor: the two creatures really are controlled by different players"
    );

    let idx = sacrifice_self_ability_index(&state, mardu);
    let (state, _ev) = activate(state, p1, mardu, idx, vec![]).expect("the ability activates");
    assert!(
        state.objects().get(&mardu).is_none(),
        "floor: the sacrifice-self cost was paid"
    );
    let state = pass_all(state, &[p1, p2]);
    assert!(
        state.stack_objects().is_empty(),
        "floor: the ability resolved"
    );

    assert_eq!(
        toughness(&state, mine),
        Some(5),
        "CR 608.2h + CR 109.5: 'you' is the source's controller, read from last known \
         information — p1's creature is in the set"
    );
    assert_eq!(
        toughness(&state, theirs),
        Some(2),
        "CR 109.5: p2's creature is NOT — a fix that answers `true` whenever the source \
         lookup fails is caught here"
    );
}

// ── t6 — CR 611.2c: the set is determined at RESOLUTION ──────────────────────

#[test]
/// CR 611.2c: *"a continuous effect generated by the resolution of a spell or
/// ability … The set of objects it affects is determined when that spell or
/// ability resolves"* — and then never changes.
///
/// Three legs on one board, all driven through the sacrifice-self ability so
/// the source is gone in every one of them:
///
/// * **Latecomer** enters the battlefield BETWEEN activation and resolution →
///   it IS a member, because the set is determined at RESOLUTION.
/// * **Departed** was on the battlefield at activation and LEFT before
///   resolution → it is NOT a member.
/// * **Afterwards** enters AFTER resolution → it is NOT a member, because the
///   set is locked in (this leg is the CONTROL and is green today).
///
/// **RED at the unfixed merge base**, observed on the `Present` assertion:
/// `left: Some(2)`, `right: Some(5)`. The Latecomer leg sits one assertion
/// below it and the `Afterwards` control leg two below, so at the merge base
/// neither was reached — stated rather than implied.
///
/// > **Correction to the dispatching brief.** The brief stated this probe as
/// > *"a creature that enters the battlefield BETWEEN activation and resolution
/// > is NOT a member"*. That is the ACTIVATION-time rule and CR 611.2c is
/// > explicit that the set is determined at RESOLUTION, so such a creature IS a
/// > member. The probe is written to CR, and the discrepancy is reported rather
/// > than silently followed.
fn dx39_t6_mardu_set_is_determined_at_resolution_not_activation() {
    let (mut state, mardu, p1, p2) = setup(
        "Mardu Ascendancy",
        vec![
            ObjectSpec::creature(p(1), "Present", 2, 2),
            ObjectSpec::creature(p(1), "Departed", 2, 2),
            // Staged in hand; each is moved onto the battlefield at its own
            // moment below with a real CR 400.7 zone change.
            ObjectSpec::creature(p(1), "Latecomer", 2, 2).in_zone(ZoneId::Hand(p(1))),
            ObjectSpec::creature(p(1), "Afterwards", 2, 2).in_zone(ZoneId::Hand(p(1))),
        ],
    );
    let present = find_object_controlled_by(&state, "Present", p1);
    let departed = find_object_controlled_by(&state, "Departed", p1);

    assert_eq!(toughness(&state, present), Some(2), "floor: 2/2 to start");
    assert_eq!(toughness(&state, departed), Some(2), "floor: 2/2 to start");

    let idx = sacrifice_self_ability_index(&state, mardu);
    let (state2, _ev) = activate(state, p1, mardu, idx, vec![]).expect("the ability activates");
    state = state2;
    assert!(
        state.objects().get(&mardu).is_none(),
        "floor: the sacrifice-self cost was paid"
    );
    assert_eq!(
        state.stack_objects().len(),
        1,
        "floor: ability on the stack"
    );

    // A creature enters the battlefield while the ability is on the stack.
    let latecomer_in_hand = find_in_zone(&state, "Latecomer", ZoneId::Hand(p1));
    let (latecomer, _) =
        test_util::move_object_to_zone(&mut state, latecomer_in_hand, ZoneId::Battlefield)
            .expect("the latecomer enters the battlefield");

    // CR 400.7: and one that was there at activation leaves before resolution.
    test_util::move_object_to_zone(&mut state, departed, ZoneId::Graveyard(p1))
        .expect("the departed creature can be put into its owner's graveyard");
    assert!(
        state.objects().get(&departed).is_none(),
        "floor: the departed creature really left before resolution"
    );
    assert_eq!(
        state
            .objects()
            .get(&latecomer)
            .map(|o| o.zone == ZoneId::Battlefield),
        Some(true),
        "floor: the latecomer really is on the battlefield before resolution"
    );

    let mut state = pass_all(state, &[p1, p2]);
    assert!(
        state.stack_objects().is_empty(),
        "floor: the ability resolved"
    );

    assert_eq!(
        toughness(&state, present),
        Some(5),
        "CR 611.2c: on the battlefield at resolution — a member"
    );
    assert_eq!(
        toughness(&state, latecomer),
        Some(5),
        "CR 611.2c: the set is determined at RESOLUTION, and the latecomer was on the \
         battlefield by then — it IS a member"
    );

    // Leg 3 (CONTROL): a creature that arrives AFTER resolution is not a member.
    let afterwards_in_hand = find_in_zone(&state, "Afterwards", ZoneId::Hand(p1));
    let (afterwards, _) =
        test_util::move_object_to_zone(&mut state, afterwards_in_hand, ZoneId::Battlefield)
            .expect("the post-resolution creature enters the battlefield");
    assert_eq!(
        toughness(&state, afterwards),
        Some(2),
        "CR 611.2c: the set never changes after the effect begins, so a creature that \
         entered after resolution gets nothing"
    );
}
