//! State-Based Actions (CR 704).
//!
//! SBAs are checked as a simultaneous batch immediately before any player
//! would receive priority (CR 704.3). They never use the stack — they happen
//! instantaneously. Triggers generated by SBAs are queued into
//! `pending_triggers` and will be flushed to the stack by
//! `abilities::flush_pending_triggers` after all SBAs complete.
//!
//! The SBA check is a fixed-point loop: apply all applicable SBAs at once,
//! then repeat until no SBAs fire (CR 704.3: "... performed again, and this
//! process is repeated until no state-based actions are performed").
//!
//! Implemented SBAs (all from CR 704.5):
//! - 704.5a: Player at 0 or less life → loses.
//! - 704.5c: Player has 10 or more poison counters → loses.
//! - 704.5d: Token in a non-battlefield zone → ceases to exist.
//! - 704.5f: Creature with toughness ≤ 0 → put into owner's graveyard.
//! - 704.5g: Creature with lethal damage (damage ≥ toughness) → destroyed.
//! - 704.5h: Creature dealt damage by a deathtouch source → destroyed.
//! - 704.5i: Planeswalker with 0 loyalty counters → put into owner's graveyard.
//! - 704.5j: Legendary rule — multiple legendaries with same name → one kept.
//! - 704.5m: Aura attached to an illegal object → put into owner's graveyard.
//! - 704.5n: Equipment/fortification attached illegally → becomes unattached.
//! - 704.5q: +1/+1 and -1/-1 counter pairs annihilate each other.
//! - 704.5u: Commander — player received 21+ combat damage from one commander → loses.

use std::collections::HashMap;

use im::OrdMap;

use crate::state::game_object::{Characteristics, ObjectId};
use crate::state::player::PlayerId;
use crate::state::replacement_effect::PendingZoneChange;
use crate::state::types::{
    CardType, CounterType, EnchantTarget, KeywordAbility, SubType, SuperType,
};
use crate::state::zone::{ZoneId, ZoneType};
use crate::state::GameState;

use super::abilities;
use super::commander;
use super::events::{GameEvent, LossReason};
use super::layers::calculate_characteristics;
use super::replacement;

// ── Public interface ────────────────────────────────────────────────────────

/// CR 704.3: Check and apply all applicable state-based actions as a fixed-point loop.
///
/// Called before any player would receive priority. Runs until no SBAs apply.
/// Triggers generated by SBAs are queued into `state.pending_triggers`; the
/// caller must flush them to the stack via `flush_pending_triggers`.
///
/// CR 603.6c / CR 700.4 / CR 704.5d: Trigger checking is performed inside the
/// loop, after each pass but before the next pass can clean up tokens. This
/// ensures that "when this dies" triggers on token creatures are correctly queued
/// before SBA 704.5d removes the token from `state.objects` in the following pass.
pub fn check_and_apply_sbas(state: &mut GameState) -> Vec<GameEvent> {
    let mut all_events = Vec::new();
    loop {
        let events = apply_sbas_once(state);
        if events.is_empty() {
            break;
        }
        // Check triggers on this pass's events NOW, before the next pass can
        // remove tokens from state.objects (CR 704.5d). This is what allows
        // "when this dies" triggers on tokens to fire correctly.
        let pass_triggers = abilities::check_triggers(state, &events);
        for t in pass_triggers {
            state.pending_triggers.push_back(t);
        }
        all_events.extend(events);
    }
    all_events
}

// ── CR 702.131b: Ascend check ────────────────────────────────────────────────

/// CR 702.131b: Ascend on a permanent is a static ability.
/// "Any time you control ten or more permanents and you don't have the city's
/// blessing, you get the city's blessing for the rest of the game."
///
/// This check must run FIRST in each SBA pass, before permanents are removed
/// by other SBAs (e.g., legendary rule, creature death). This ensures the
/// ruling: "If your tenth permanent enters the battlefield and then a permanent
/// leaves the battlefield immediately afterwards (most likely due to the Legend
/// Rule or 0-toughness), you get the city's blessing before it leaves."
///
/// Uses `chars_map` (layer-computed keywords) so effects that remove all
/// abilities (e.g., Humility) correctly suppress Ascend on affected permanents.
fn check_ascend(
    state: &mut GameState,
    chars_map: &HashMap<ObjectId, Characteristics>,
) -> Vec<GameEvent> {
    let mut events = Vec::new();

    let player_ids: Vec<PlayerId> = state.players.keys().copied().collect();
    for pid in player_ids {
        // Skip players who already have the city's blessing (CR 702.131c: permanent).
        let already_has = state
            .players
            .get(&pid)
            .map(|p| p.has_citys_blessing)
            .unwrap_or(true); // treat missing player as already having it (skip)
        if already_has {
            continue;
        }

        // CR 702.131b: Player must control a permanent with Ascend.
        let has_ascend_permanent = state.objects.iter().any(|(id, obj)| {
            obj.zone == ZoneId::Battlefield
                && obj.controller == pid
                && chars_map
                    .get(id)
                    .map(|chars| chars.keywords.contains(&KeywordAbility::Ascend))
                    .unwrap_or(false)
        });
        if !has_ascend_permanent {
            continue;
        }

        // Count all permanents controlled by this player (tokens and non-tokens alike).
        // CR 702.131 ruling: "A permanent is any object on the battlefield, including tokens."
        let permanent_count = state
            .objects
            .values()
            .filter(|obj| obj.zone == ZoneId::Battlefield && obj.controller == pid)
            .count();

        if permanent_count >= 10 {
            if let Some(p) = state.players.get_mut(&pid) {
                p.has_citys_blessing = true;
            }
            events.push(GameEvent::CitysBlessingGained { player: pid });
        }
    }

    events
}

// ── One pass of SBA checking ────────────────────────────────────────────────

/// Apply all applicable SBAs simultaneously in one pass.
/// Returns events produced; empty means nothing fired.
fn apply_sbas_once(state: &mut GameState) -> Vec<GameEvent> {
    // MR-M5-02: Build a characteristics snapshot for all battlefield objects at the
    // start of each SBA pass using the layer system. This ensures SBAs see effective
    // characteristics (after continuous effects) rather than raw printed values.
    // For example: a creature reduced to 0 toughness by a -3/-3 aura dies to 704.5f,
    // and an indestructible creature whose keyword was removed by Humility dies to 704.5g.
    //
    // The snapshot is built once per pass (not per check) because all SBAs within a
    // single pass are evaluated simultaneously (CR 704.3). After any SBAs fire, the
    // loop in `check_and_apply_sbas` calls us again with a fresh snapshot.
    let battlefield_ids: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(_, obj)| obj.zone == ZoneId::Battlefield)
        .map(|(id, _)| *id)
        .collect();
    let chars_map: HashMap<ObjectId, Characteristics> = battlefield_ids
        .iter()
        .filter_map(|&id| {
            let chars = calculate_characteristics(state, id)?;
            Some((id, chars))
        })
        .collect();

    let mut events = Vec::new();

    // CR 702.131b: Ascend check runs FIRST so the player gets the city's blessing
    // before other SBAs (legend rule, creature death) may remove permanents in the
    // same pass. This enforces the ruling: "If your tenth permanent enters and then
    // leaves immediately (e.g., legend rule), you still get the city's blessing."
    let ascend_events = check_ascend(state, &chars_map);

    // CR 702.131d: "After a player gets the city's blessing, continuous effects are
    // reapplied before the game checks to see if the game state or preceding events
    // have matched any trigger conditions."
    //
    // If any blessing was granted, rebuild chars_map so that blessing-dependent
    // continuous effects (e.g., "+1/+1 to your creatures as long as you have the
    // city's blessing") are reflected in the remaining SBA checks within this pass.
    // This is only relevant when a card has a blessing-conditional continuous effect
    // that changes characteristics checked by later SBAs in the same pass (narrow
    // edge case, but CR-required).
    let chars_map = if ascend_events
        .iter()
        .any(|e| matches!(e, GameEvent::CitysBlessingGained { .. }))
    {
        battlefield_ids
            .iter()
            .filter_map(|&id| {
                let chars = calculate_characteristics(state, id)?;
                Some((id, chars))
            })
            .collect()
    } else {
        chars_map
    };

    events.extend(ascend_events);

    // Collect events from each SBA category. Order matches CR 704.5 numbering
    // but all are treated as simultaneous within a pass.
    events.extend(check_player_sbas(state));
    events.extend(check_token_sbas(state));
    events.extend(check_creature_sbas(state, &chars_map));
    events.extend(check_planeswalker_sbas(state, &chars_map));
    events.extend(check_legendary_rule(state));
    events.extend(check_aura_sbas(state));
    events.extend(check_equipment_sbas(state, &chars_map));
    events.extend(check_counter_annihilation(state));
    // CR 903.9a / CR 704.6d: check for commanders in graveyard or exile and
    // return them to the command zone. Called after counter annihilation per
    // the plan (704.6d runs after 704.5 SBAs).
    events.extend(commander::check_commander_zone_return_sba(state));

    events
}

// ── CR 704.5a / 704.5c / 704.5u ─────────────────────────────────────────────

/// CR 704.5a: Player at 0 or less life loses.
/// CR 704.5c: Player with 10+ poison counters loses.
/// CR 704.5u (Commander): Player who received 21+ combat damage from one commander loses.
fn check_player_sbas(state: &mut GameState) -> Vec<GameEvent> {
    let mut events = Vec::new();

    let player_ids: Vec<PlayerId> = state.players.keys().copied().collect();
    for id in player_ids {
        let Some(player) = state.players.get(&id) else {
            continue;
        };
        if player.has_lost || player.has_conceded {
            continue; // Already eliminated — skip.
        }

        // CR 704.5a: life total ≤ 0.
        if player.life_total <= 0 {
            if let Some(p) = state.players.get_mut(&id) {
                p.has_lost = true;
            }
            events.push(GameEvent::PlayerLost {
                player: id,
                reason: LossReason::LifeTotal,
            });
            continue; // Only emit one loss event per player per pass.
        }

        // CR 704.5c: 10+ poison counters.
        if player.poison_counters >= 10 {
            if let Some(p) = state.players.get_mut(&id) {
                p.has_lost = true;
            }
            events.push(GameEvent::PlayerLost {
                player: id,
                reason: LossReason::PoisonCounters,
            });
            continue;
        }

        // CR 704.5u (Commander): 21+ combat damage from a single commander.
        // MR-M4-01: use if-let instead of unwrap — player may have been removed mid-pass.
        let Some(player_ref) = state.players.get(&id) else {
            continue;
        };
        let lost_to_cmdr = player_ref
            .commander_damage_received
            .values()
            .any(|by_card| by_card.values().any(|&dmg| dmg >= 21));
        if lost_to_cmdr {
            if let Some(p) = state.players.get_mut(&id) {
                p.has_lost = true;
            }
            events.push(GameEvent::PlayerLost {
                player: id,
                reason: LossReason::CommanderDamage,
            });
        }
    }

    events
}

// ── CR 704.5d ────────────────────────────────────────────────────────────────

/// CR 704.5d: If a token is in a zone other than the battlefield, it ceases to exist.
///
/// Tokens are never put into any zone during SBA checks themselves (tokens die
/// via 704.5f/g/h like normal creatures). But if a token somehow ended up in
/// the graveyard, library, exile, hand, or stack by some other means, it is
/// removed here.
fn check_token_sbas(state: &mut GameState) -> Vec<GameEvent> {
    let mut events = Vec::new();

    let token_ids: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(_, obj)| obj.is_token && obj.zone != ZoneId::Battlefield)
        .map(|(id, _)| *id)
        .collect();

    for id in token_ids {
        // Remove from its zone and from the objects map.
        if let Some(obj) = state.objects.get(&id) {
            let zone_id = obj.zone;
            // Remove from zone.
            if let Some(zone) = state.zones.get_mut(&zone_id) {
                zone.remove(&id);
            }
        }
        state.objects.remove(&id);
        events.push(GameEvent::TokenCeasedToExist { object_id: id });
    }

    events
}

// ── CR 704.5f / 704.5g / 704.5h ─────────────────────────────────────────────

/// CR 704.5f: Creature with toughness ≤ 0 → owner's graveyard.
/// CR 704.5g: Creature with lethal damage (damage_marked ≥ toughness > 0) → destroyed.
/// CR 704.5h: Creature that was dealt damage by a deathtouch source → destroyed.
///
/// "Destroyed" in 704.5g/h means moved to the owner's graveyard. Indestructible
/// creatures are not destroyed by 704.5g/h (CR 702.12a). Indestructibility (and other
/// characteristics) is evaluated via `chars_map` — the layer-computed snapshot — so
/// continuous effects that remove indestructible or lower toughness are correctly seen.
fn check_creature_sbas(
    state: &mut GameState,
    chars_map: &HashMap<ObjectId, Characteristics>,
) -> Vec<GameEvent> {
    let mut events = Vec::new();

    // Collect creatures on the battlefield that need to die.
    // MR-M5-02: use `chars_map` (layer-computed) instead of raw `obj.characteristics`.
    // damage_marked and deathtouch_damage remain on the GameObject (not in chars).
    //
    // The bool in each tuple is `is_destruction`: true for 704.5g/h (can be regenerated),
    // false for 704.5f zero-toughness (not destruction — regeneration does not apply,
    // CR 701.19a: "destroyed" vs zero-toughness state replacement).
    let dying: Vec<(ObjectId, bool)> = state
        .objects
        .iter()
        .filter_map(|(id, obj)| {
            if obj.zone != ZoneId::Battlefield {
                return None;
            }

            // Use layer-computed characteristics so continuous effects are visible.
            let chars = chars_map.get(id)?;

            if !chars.card_types.contains(&CardType::Creature) {
                return None;
            }

            // CR 704.5f/g/h only apply to creatures with a defined toughness.
            // A creature without toughness (e.g., a test card) is skipped.
            let toughness = chars.toughness?;

            // MR-M5-02: indestructible is now read from layer-computed keywords —
            // an effect that removes Indestructible (e.g., Humility) is correctly seen.
            let is_indestructible = chars.keywords.contains(&KeywordAbility::Indestructible);

            // CR 704.5f: toughness ≤ 0. Indestructible does NOT prevent this
            // (CR 702.12a only prevents "destroy"; zero-toughness is a state replacement).
            // is_destruction = false: regeneration cannot prevent this (CR 701.19a).
            if toughness <= 0 {
                return Some((*id, false));
            }

            // CR 704.5g: lethal damage (damage ≥ toughness > 0).
            // CR 702.12a: Indestructible creatures cannot be destroyed — skip.
            // MR-M4-04: compare in u32 space to avoid u32→i32 wrapping on large damage values.
            // toughness > 0 is guaranteed by the check above, so the cast is safe.
            if !is_indestructible && obj.damage_marked > 0 && obj.damage_marked >= toughness as u32
            {
                return Some((*id, true)); // is_destruction = true
            }

            // CR 704.5h: any damage from a deathtouch source.
            // CR 702.12a: Indestructible creatures cannot be destroyed — skip.
            if !is_indestructible && obj.deathtouch_damage && obj.damage_marked > 0 {
                return Some((*id, true)); // is_destruction = true
            }

            None
        })
        .collect();

    for (id, is_destruction) in dying {
        // Skip objects that already have a pending replacement choice.
        if state.pending_zone_changes.iter().any(|p| p.object_id == id) {
            continue;
        }

        // CR 701.19a/614.8: Check regeneration shields before destruction (704.5g/h only).
        // CR 704.5f (zero toughness) is NOT destruction -- regeneration cannot prevent it.
        if is_destruction {
            if let Some(shield_id) = replacement::check_regeneration_shield(state, id) {
                let regen_events = replacement::apply_regeneration(state, id, shield_id);
                events.extend(regen_events);
                continue; // Skip destruction -- permanent stays on battlefield
            }
        }

        let (owner, pre_death_controller, pre_death_counters) = match state.objects.get(&id) {
            Some(obj) => (obj.owner, obj.controller, obj.counters.clone()),
            None => continue, // Already removed in a previous SBA this pass.
        };

        // CR 614: Check replacement effects before moving to graveyard.
        let action = replacement::check_zone_change_replacement(
            state,
            id,
            ZoneType::Battlefield,
            ZoneType::Graveyard,
            owner,
            &std::collections::HashSet::new(),
        );

        match action {
            replacement::ZoneChangeAction::Proceed => {
                // No replacement — move to graveyard normally.
                if let Ok((new_id, _)) = state.move_object_to_zone(id, ZoneId::Graveyard(owner)) {
                    events.push(GameEvent::CreatureDied {
                        object_id: id,
                        new_grave_id: new_id,
                        // CR 603.3a: capture controller before move_object_to_zone resets it.
                        controller: pre_death_controller,
                        // CR 702.79a: capture counters before move_object_to_zone resets them.
                        pre_death_counters: pre_death_counters.clone(),
                    });
                }
            }
            replacement::ZoneChangeAction::Redirect {
                to,
                events: repl_events,
                ..
            } => {
                // Single replacement auto-applied — redirect zone.
                events.extend(repl_events);
                if let Ok((new_id, _)) = state.move_object_to_zone(id, to) {
                    match to {
                        ZoneId::Exile => {
                            events.push(GameEvent::ObjectExiled {
                                player: owner,
                                object_id: id,
                                new_exile_id: new_id,
                            });
                        }
                        ZoneId::Command(_) => {
                            // Commander redirected to command zone — no CreatureDied.
                        }
                        _ => {
                            events.push(GameEvent::CreatureDied {
                                object_id: id,
                                new_grave_id: new_id,
                                // CR 603.3a: capture controller before move_object_to_zone resets it.
                                controller: pre_death_controller,
                                // CR 702.79a: capture counters before move_object_to_zone resets them.
                                pre_death_counters: pre_death_counters.clone(),
                            });
                        }
                    }
                }
            }
            replacement::ZoneChangeAction::ChoiceRequired {
                player,
                choices,
                event_description,
            } => {
                // Multiple replacements — defer until player chooses.
                state.pending_zone_changes.push_back(PendingZoneChange {
                    object_id: id,
                    original_from: ZoneType::Battlefield,
                    original_destination: ZoneType::Graveyard,
                    affected_player: player,
                    already_applied: Vec::new(),
                });
                events.push(GameEvent::ReplacementChoiceRequired {
                    player,
                    event_description,
                    choices,
                });
            }
        }
    }

    events
}

// ── CR 704.5i ────────────────────────────────────────────────────────────────

/// CR 704.5i: Planeswalker with 0 loyalty counters → owner's graveyard.
///
/// Loyalty is tracked in two ways (M4 supports both):
/// - `Characteristics.loyalty`: base loyalty set at construction (standard for M4 tests).
/// - `CounterType::Loyalty` counters: added/removed by loyalty abilities (M7+).
///
/// A planeswalker dies if its effective loyalty is ≤ 0. Effective loyalty =
/// Loyalty counter total if present, otherwise `Characteristics.loyalty`.
fn check_planeswalker_sbas(
    state: &mut GameState,
    chars_map: &HashMap<ObjectId, Characteristics>,
) -> Vec<GameEvent> {
    let mut events = Vec::new();

    // MR-M5-02: use layer-computed characteristics so continuous effects are visible.
    let dying: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(id, obj)| {
            if obj.zone != ZoneId::Battlefield {
                return false;
            }
            let Some(chars) = chars_map.get(id) else {
                return false;
            };
            if !chars.card_types.contains(&CardType::Planeswalker) {
                return false;
            }
            // Effective loyalty: use Loyalty counter if present, else Characteristics.loyalty.
            // MR-M4-05: compare in the natural type of each branch to avoid u32→i32 wrapping.
            // Loyalty counters are u32 — dead when the counter reaches 0.
            // Base loyalty (i32) can start at 0 or be set negative by effects.
            let loyalty_counter = obj.counters.get(&CounterType::Loyalty).copied();
            match loyalty_counter {
                Some(counter_value) => counter_value == 0,
                // MR-M4-11: unwrap_or(0) — a planeswalker with no printed loyalty
                // and no loyalty counter has effective loyalty 0 and dies (CR 704.5i).
                // unwrap_or(1) was incorrect: it allowed misconfigured planeswalkers to survive.
                None => chars.loyalty.unwrap_or(0) <= 0,
            }
        })
        .map(|(id, _)| *id)
        .collect();

    for id in dying {
        // Skip objects that already have a pending replacement choice.
        if state.pending_zone_changes.iter().any(|p| p.object_id == id) {
            continue;
        }

        let owner = match state.objects.get(&id) {
            Some(obj) => obj.owner,
            None => continue,
        };

        // CR 614: Check replacement effects before moving to graveyard.
        let action = replacement::check_zone_change_replacement(
            state,
            id,
            ZoneType::Battlefield,
            ZoneType::Graveyard,
            owner,
            &std::collections::HashSet::new(),
        );

        match action {
            replacement::ZoneChangeAction::Proceed => {
                if let Ok((new_id, _)) = state.move_object_to_zone(id, ZoneId::Graveyard(owner)) {
                    events.push(GameEvent::PlaneswalkerDied {
                        object_id: id,
                        new_grave_id: new_id,
                    });
                }
            }
            replacement::ZoneChangeAction::Redirect {
                to,
                events: repl_events,
                ..
            } => {
                events.extend(repl_events);
                if let Ok((new_id, _)) = state.move_object_to_zone(id, to) {
                    match to {
                        ZoneId::Exile => {
                            events.push(GameEvent::ObjectExiled {
                                player: owner,
                                object_id: id,
                                new_exile_id: new_id,
                            });
                        }
                        ZoneId::Command(_) => {}
                        _ => {
                            events.push(GameEvent::PlaneswalkerDied {
                                object_id: id,
                                new_grave_id: new_id,
                            });
                        }
                    }
                }
            }
            replacement::ZoneChangeAction::ChoiceRequired {
                player,
                choices,
                event_description,
            } => {
                state.pending_zone_changes.push_back(PendingZoneChange {
                    object_id: id,
                    original_from: ZoneType::Battlefield,
                    original_destination: ZoneType::Graveyard,
                    affected_player: player,
                    already_applied: Vec::new(),
                });
                events.push(GameEvent::ReplacementChoiceRequired {
                    player,
                    event_description,
                    choices,
                });
            }
        }
    }

    events
}

// ── CR 704.5j ────────────────────────────────────────────────────────────────

/// CR 704.5j: If a player controls two or more legendary permanents with the
/// same name, that player keeps one and the rest go to their owners' graveyards.
///
/// Auto-choice policy (M4): keep the permanent with the highest ObjectId
/// (most recently entered the battlefield). Real player choice is M7+.
fn check_legendary_rule(state: &mut GameState) -> Vec<GameEvent> {
    let mut events = Vec::new();

    // Gather all legendary battlefield permanents, grouped by (controller, name).
    // Key: (PlayerId, name) → Vec<ObjectId> sorted ascending (lowest = oldest).
    let mut by_controller_name: OrdMap<(PlayerId, String), Vec<ObjectId>> = OrdMap::new();

    for (id, obj) in &state.objects {
        if obj.zone != ZoneId::Battlefield {
            continue;
        }
        if !obj
            .characteristics
            .supertypes
            .contains(&SuperType::Legendary)
        {
            continue;
        }
        let key = (obj.controller, obj.characteristics.name.clone());
        by_controller_name.entry(key).or_default().push(*id);
    }

    for ((controller, _name), mut ids) in by_controller_name {
        if ids.len() < 2 {
            continue; // No violation.
        }

        // Sort by ObjectId: highest = most recently entered. Keep the last one.
        // MR-M4-03: let-else instead of unwrap (ids.len() >= 2 is checked above).
        ids.sort();
        let Some(&kept) = ids.last() else {
            continue;
        };
        let to_remove = &ids[..ids.len() - 1];

        let mut graves: Vec<(ObjectId, ObjectId)> = Vec::new();

        for &old_id in to_remove {
            let owner = match state.objects.get(&old_id) {
                Some(obj) => obj.owner,
                None => continue,
            };
            // Use owner of the object, not the controller (could differ).
            if let Ok((new_id, _)) = state.move_object_to_zone(old_id, ZoneId::Graveyard(owner)) {
                graves.push((old_id, new_id));
            }
        }

        if !graves.is_empty() {
            events.push(GameEvent::LegendaryRuleApplied {
                kept_id: kept,
                put_to_graveyard: graves,
            });

            // Suppress unused variable warning: controller is used as the map key above.
            let _ = controller;
        }
    }

    events
}

// ── CR 704.5m ────────────────────────────────────────────────────────────────

/// CR 702.5a: Extract the EnchantTarget from an Aura's computed keywords.
///
/// Returns the first `Enchant(target)` keyword found, or `None` if the
/// object has no Enchant keyword.
pub(crate) fn get_enchant_target(keywords: &im::OrdSet<KeywordAbility>) -> Option<EnchantTarget> {
    keywords.iter().find_map(|kw| {
        if let KeywordAbility::Enchant(target) = kw {
            Some(target.clone())
        } else {
            None
        }
    })
}

/// CR 702.5a: Check if a target's characteristics satisfy the Enchant restriction.
///
/// Used both at cast time (CR 303.4a) and in the Aura SBA (CR 704.5m).
pub(crate) fn matches_enchant_target(
    enchant: &EnchantTarget,
    target_chars: &crate::state::game_object::Characteristics,
) -> bool {
    match enchant {
        EnchantTarget::Creature => target_chars.card_types.contains(&CardType::Creature),
        EnchantTarget::Land => target_chars.card_types.contains(&CardType::Land),
        EnchantTarget::Artifact => target_chars.card_types.contains(&CardType::Artifact),
        EnchantTarget::Enchantment => target_chars.card_types.contains(&CardType::Enchantment),
        EnchantTarget::Planeswalker => target_chars.card_types.contains(&CardType::Planeswalker),
        EnchantTarget::Permanent => true, // any permanent type is legal
        EnchantTarget::Player => false,   // can't be attached to an object (needs player)
        EnchantTarget::CreatureOrPlaneswalker => {
            target_chars.card_types.contains(&CardType::Creature)
                || target_chars.card_types.contains(&CardType::Planeswalker)
        }
    }
}

/// CR 704.5m: If an Aura is attached to an object or player it can't legally
/// be attached to, put it into its owner's graveyard.
///
/// Checks:
/// 1. Aura is not attached to anything → always illegal (CR 704.5m).
/// 2. Target object has left the battlefield → illegal (CR 704.5m).
/// 3. Enchant restriction mismatch: target no longer matches the Aura's Enchant keyword
///    (e.g., "Enchant creature" aura on a non-creature) → illegal (CR 704.5m / 303.4c).
/// 4. CR 702.16c: target has protection from a quality the aura matches → illegal.
fn check_aura_sbas(state: &mut GameState) -> Vec<GameEvent> {
    let mut events = Vec::new();
    // MR-M4-10: hoist SubType to avoid per-object-per-SBA-pass String allocation.
    let subtype_aura = SubType("Aura".to_string());

    let illegal_auras: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(aura_id, obj)| {
            if obj.zone != ZoneId::Battlefield {
                return false;
            }
            if !obj.characteristics.subtypes.contains(&subtype_aura) {
                return false;
            }
            // CR 303.4d: An Aura that's also a creature can't enchant anything.
            // Check layer-computed characteristics so type-changing effects apply
            // (e.g., a global "all permanents are creatures" effect).
            let aura_card_types = calculate_characteristics(state, **aura_id)
                .map(|c| c.card_types)
                .unwrap_or_default();
            if aura_card_types.contains(&CardType::Creature) {
                return true;
            }
            // Aura is illegal if it's not attached to anything on the battlefield.
            match obj.attached_to {
                None => true, // Unattached aura — always illegal on battlefield.
                Some(target_id) => {
                    // CR 303.4d: An Aura can't enchant itself.
                    if target_id == **aura_id {
                        return true;
                    }
                    // Illegal if the target is gone or not on the battlefield.
                    let target_gone = state
                        .objects
                        .get(&target_id)
                        .map(|t| t.zone != ZoneId::Battlefield)
                        .unwrap_or(true);
                    if target_gone {
                        return true;
                    }
                    // CR 704.5m / 303.4c: if this Aura has an Enchant keyword, check
                    // that the attached object still satisfies the restriction
                    // (layer-computed characteristics, so type-change effects apply).
                    let aura_keywords = calculate_characteristics(state, **aura_id)
                        .map(|c| c.keywords)
                        .unwrap_or_default();
                    if let Some(enchant_target) = get_enchant_target(&aura_keywords) {
                        let target_chars =
                            calculate_characteristics(state, target_id).or_else(|| {
                                state
                                    .objects
                                    .get(&target_id)
                                    .map(|o| o.characteristics.clone())
                            });
                        if let Some(tc) = target_chars {
                            if !matches_enchant_target(&enchant_target, &tc) {
                                return true;
                            }
                        }
                    }
                    // CR 702.16c: the aura is illegal if the target has protection from
                    // a quality that the aura's characteristics match.
                    let target_keywords = calculate_characteristics(state, target_id)
                        .map(|c| c.keywords)
                        .unwrap_or_default();
                    let aura_chars = calculate_characteristics(state, **aura_id);
                    if let Some(ac) = &aura_chars {
                        if super::protection::attachment_is_illegal_due_to_protection(
                            &target_keywords,
                            ac,
                        ) {
                            return true;
                        }
                    }
                    false
                }
            }
        })
        .map(|(id, _)| *id)
        .collect();

    // CR 702.103f: Separate bestowed Auras from normal illegal Auras.
    // Bestowed Auras revert to creatures instead of going to the graveyard.
    // Normal illegal Auras go to the graveyard (CR 704.5m).
    let (bestowed_auras, normal_auras): (Vec<ObjectId>, Vec<ObjectId>) =
        illegal_auras.into_iter().partition(|id| {
            state
                .objects
                .get(id)
                .map(|obj| obj.is_bestowed)
                .unwrap_or(false)
        });

    // CR 702.103f: For bestowed Auras — clear attachment, revert to creature.
    for aura_id in bestowed_auras {
        // Clear the attachment link on the target.
        if let Some(obj) = state.objects.get(&aura_id) {
            if let Some(target_id) = obj.attached_to {
                if let Some(target) = state.objects.get_mut(&target_id) {
                    target.attachments.retain(|id| *id != aura_id);
                }
            }
        }
        // Revert the bestowed Aura to an enchantment creature.
        if let Some(obj) = state.objects.get_mut(&aura_id) {
            obj.attached_to = None;
            obj.is_bestowed = false;
            // Remove Aura subtype and enchant creature keyword.
            obj.characteristics.subtypes.remove(&subtype_aura);
            obj.characteristics
                .keywords
                .remove(&KeywordAbility::Enchant(EnchantTarget::Creature));
            // Restore Creature card type.
            obj.characteristics.card_types.insert(CardType::Creature);
        }
        events.push(GameEvent::BestowReverted { object_id: aura_id });
    }

    // CR 704.5m: Normal illegal Auras go to the graveyard.
    for id in normal_auras {
        let owner = match state.objects.get(&id) {
            Some(obj) => obj.owner,
            None => continue,
        };

        if let Ok((new_id, _)) = state.move_object_to_zone(id, ZoneId::Graveyard(owner)) {
            events.push(GameEvent::AuraFellOff {
                object_id: id,
                new_grave_id: new_id,
            });
        }
    }

    events
}

// ── CR 704.5n ────────────────────────────────────────────────────────────────

/// CR 704.5n: If an Equipment or Fortification is attached to an illegal
/// permanent, it becomes unattached.
///
/// Equipment must be attached to a creature. Fortification must be attached
/// to a land. For M4: an equipment is illegal if its `attached_to` references
/// an object that is not on the battlefield or not a creature.
fn check_equipment_sbas(
    state: &mut GameState,
    chars_map: &HashMap<ObjectId, Characteristics>,
) -> Vec<GameEvent> {
    let mut events = Vec::new();
    // MR-M4-10: hoist SubType values to avoid per-object-per-SBA-pass String allocations.
    let subtype_equipment = SubType("Equipment".to_string());
    let subtype_fortification = SubType("Fortification".to_string());

    // MR-M5-02: use layer-computed characteristics for both the equipment's own
    // subtypes (could be added by effects) and the target's card types (e.g., a
    // creature that lost Creature type due to a continuous effect).
    let illegal_equip: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(id, obj)| {
            if obj.zone != ZoneId::Battlefield {
                return false;
            }
            let Some(chars) = chars_map.get(id) else {
                return false;
            };
            let is_equipment = chars.subtypes.contains(&subtype_equipment);
            let is_fortification = chars.subtypes.contains(&subtype_fortification);
            if !is_equipment && !is_fortification {
                return false;
            }
            match obj.attached_to {
                None => false, // Unequipped equipment on battlefield is fine.
                Some(target_id) => {
                    let target = state.objects.get(&target_id);
                    match target {
                        None => true, // Target gone — unattach.
                        Some(t) => {
                            if t.zone != ZoneId::Battlefield {
                                return true; // Target left battlefield.
                            }
                            // Use layer-computed characteristics for the target's type.
                            let target_chars = chars_map.get(&target_id);
                            match target_chars {
                                None => true, // No characteristics — treat as illegal.
                                Some(tc) => {
                                    if is_equipment {
                                        // Equipment must be on a creature.
                                        if !tc.card_types.contains(&CardType::Creature) {
                                            return true;
                                        }
                                    } else {
                                        // Fortification must be on a land.
                                        if !tc.card_types.contains(&CardType::Land) {
                                            return true;
                                        }
                                    }
                                    // CR 702.16d: equipment is illegal if the equipped
                                    // permanent has protection from a quality the equipment
                                    // matches.
                                    let equipment_chars = chars_map.get(id);
                                    if let Some(ec) = equipment_chars {
                                        if super::protection::attachment_is_illegal_due_to_protection(
                                            &tc.keywords,
                                            ec,
                                        ) {
                                            return true;
                                        }
                                    }
                                    false
                                }
                            }
                        }
                    }
                }
            }
        })
        .map(|(id, _)| *id)
        .collect();

    for id in illegal_equip {
        // Unattach: clear attached_to on equipment and remove from target's attachments.
        let target_id = state.objects.get(&id).and_then(|obj| obj.attached_to);

        if let Some(obj) = state.objects.get_mut(&id) {
            obj.attached_to = None;
        }

        if let Some(target_id) = target_id {
            if let Some(target) = state.objects.get_mut(&target_id) {
                target.attachments.retain(|&x| x != id);
            }
        }

        events.push(GameEvent::EquipmentUnattached { object_id: id });
    }

    events
}

// ── CR 704.5q ────────────────────────────────────────────────────────────────

/// CR 704.5q: If a permanent has both a +1/+1 counter and a -1/-1 counter on it,
/// N pairs are removed, where N = min(+1/+1 count, -1/-1 count).
fn check_counter_annihilation(state: &mut GameState) -> Vec<GameEvent> {
    let mut events = Vec::new();

    let ids: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(_, obj)| {
            obj.zone == ZoneId::Battlefield
                && obj
                    .counters
                    .get(&CounterType::PlusOnePlusOne)
                    .copied()
                    .unwrap_or(0)
                    > 0
                && obj
                    .counters
                    .get(&CounterType::MinusOneMinusOne)
                    .copied()
                    .unwrap_or(0)
                    > 0
        })
        .map(|(id, _)| *id)
        .collect();

    for id in ids {
        let Some(obj) = state.objects.get_mut(&id) else {
            continue;
        };

        let plus = obj
            .counters
            .get(&CounterType::PlusOnePlusOne)
            .copied()
            .unwrap_or(0);
        let minus = obj
            .counters
            .get(&CounterType::MinusOneMinusOne)
            .copied()
            .unwrap_or(0);
        let remove = plus.min(minus);

        if remove == 0 {
            continue;
        }

        let new_plus = plus - remove;
        let new_minus = minus - remove;

        if new_plus == 0 {
            obj.counters.remove(&CounterType::PlusOnePlusOne);
        } else {
            obj.counters.insert(CounterType::PlusOnePlusOne, new_plus);
        }

        if new_minus == 0 {
            obj.counters.remove(&CounterType::MinusOneMinusOne);
        } else {
            obj.counters
                .insert(CounterType::MinusOneMinusOne, new_minus);
        }

        events.push(GameEvent::CountersAnnihilated {
            object_id: id,
            amount: remove,
        });
    }

    events
}

// ── Helpers ──────────────────────────────────────────────────────────────────

/// Check if a `KeywordAbility` is present on an object's effective characteristics.
///
/// Uses `calculate_characteristics` (layer system) rather than raw `obj.characteristics`
/// so that continuous effects granting or removing the keyword are correctly reflected.
/// Used by 704.5h deathtouch check and similar keyword-gated SBAs.
#[allow(dead_code)]
pub fn has_keyword(state: &GameState, id: ObjectId, keyword: KeywordAbility) -> bool {
    calculate_characteristics(state, id)
        .map(|chars| chars.keywords.contains(&keyword))
        .unwrap_or(false)
}
