//! State-Based Actions (CR 704).
//!
//! SBAs are checked as a simultaneous batch immediately before any player
//! would receive priority (CR 704.3). They never use the stack — they happen
//! instantaneously. Triggers generated by SBAs are queued into
//! `pending_triggers` and will be flushed to the stack by
//! `abilities::flush_pending_triggers` after all SBAs complete.
//!
//! The SBA check is a fixed-point loop: apply all applicable SBAs at once,
//! then repeat until no SBAs fire (CR 704.3: "... performed again, and this
//! process is repeated until no state-based actions are performed").
//!
//! Implemented SBAs (all from CR 704.5):
//! - 704.5a: Player at 0 or less life → loses.
//! - 704.5c: Player has 10 or more poison counters → loses.
//! - 704.5d: Token in a non-battlefield zone → ceases to exist.
//! - 704.5f: Creature with toughness ≤ 0 → put into owner's graveyard.
//! - 704.5g: Creature with lethal damage (damage ≥ toughness) → destroyed.
//! - 704.5h: Creature dealt damage by a deathtouch source → destroyed.
//! - 704.5i: Planeswalker with 0 loyalty counters → put into owner's graveyard.
//! - 704.5j: Legendary rule — multiple legendaries with same name → one kept.
//! - 704.5m: Aura attached to an illegal object → put into owner's graveyard.
//! - 704.5n: Equipment/fortification attached illegally → becomes unattached.
//! - 704.5q: +1/+1 and -1/-1 counter pairs annihilate each other.
//! - 704.5u: Commander — player received 21+ combat damage from one commander → loses.

use std::collections::HashMap;

use im::OrdMap;

use crate::state::game_object::{Characteristics, ObjectId};
use crate::state::player::PlayerId;
use crate::state::replacement_effect::PendingZoneChange;
use crate::state::types::{CardType, CounterType, KeywordAbility, SubType, SuperType};
use crate::state::zone::{ZoneId, ZoneType};
use crate::state::GameState;

use super::events::{GameEvent, LossReason};
use super::layers::calculate_characteristics;
use super::replacement;

// ── Public interface ────────────────────────────────────────────────────────

/// CR 704.3: Check and apply all applicable state-based actions as a fixed-point loop.
///
/// Called before any player would receive priority. Runs until no SBAs apply.
/// Triggers generated by SBAs are queued into `state.pending_triggers`; the
/// caller must flush them to the stack via `flush_pending_triggers`.
pub fn check_and_apply_sbas(state: &mut GameState) -> Vec<GameEvent> {
    let mut all_events = Vec::new();
    loop {
        let events = apply_sbas_once(state);
        if events.is_empty() {
            break;
        }
        all_events.extend(events);
    }
    all_events
}

// ── One pass of SBA checking ────────────────────────────────────────────────

/// Apply all applicable SBAs simultaneously in one pass.
/// Returns events produced; empty means nothing fired.
fn apply_sbas_once(state: &mut GameState) -> Vec<GameEvent> {
    // MR-M5-02: Build a characteristics snapshot for all battlefield objects at the
    // start of each SBA pass using the layer system. This ensures SBAs see effective
    // characteristics (after continuous effects) rather than raw printed values.
    // For example: a creature reduced to 0 toughness by a -3/-3 aura dies to 704.5f,
    // and an indestructible creature whose keyword was removed by Humility dies to 704.5g.
    //
    // The snapshot is built once per pass (not per check) because all SBAs within a
    // single pass are evaluated simultaneously (CR 704.3). After any SBAs fire, the
    // loop in `check_and_apply_sbas` calls us again with a fresh snapshot.
    let battlefield_ids: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(_, obj)| obj.zone == ZoneId::Battlefield)
        .map(|(id, _)| *id)
        .collect();
    let chars_map: HashMap<ObjectId, Characteristics> = battlefield_ids
        .iter()
        .filter_map(|&id| {
            let chars = calculate_characteristics(state, id)?;
            Some((id, chars))
        })
        .collect();

    let mut events = Vec::new();

    // Collect events from each SBA category. Order matches CR 704.5 numbering
    // but all are treated as simultaneous within a pass.
    events.extend(check_player_sbas(state));
    events.extend(check_token_sbas(state));
    events.extend(check_creature_sbas(state, &chars_map));
    events.extend(check_planeswalker_sbas(state, &chars_map));
    events.extend(check_legendary_rule(state));
    events.extend(check_aura_sbas(state));
    events.extend(check_equipment_sbas(state, &chars_map));
    events.extend(check_counter_annihilation(state));

    events
}

// ── CR 704.5a / 704.5c / 704.5u ─────────────────────────────────────────────

/// CR 704.5a: Player at 0 or less life loses.
/// CR 704.5c: Player with 10+ poison counters loses.
/// CR 704.5u (Commander): Player who received 21+ combat damage from one commander loses.
fn check_player_sbas(state: &mut GameState) -> Vec<GameEvent> {
    let mut events = Vec::new();

    let player_ids: Vec<PlayerId> = state.players.keys().copied().collect();
    for id in player_ids {
        let Some(player) = state.players.get(&id) else {
            continue;
        };
        if player.has_lost || player.has_conceded {
            continue; // Already eliminated — skip.
        }

        // CR 704.5a: life total ≤ 0.
        if player.life_total <= 0 {
            if let Some(p) = state.players.get_mut(&id) {
                p.has_lost = true;
            }
            events.push(GameEvent::PlayerLost {
                player: id,
                reason: LossReason::LifeTotal,
            });
            continue; // Only emit one loss event per player per pass.
        }

        // CR 704.5c: 10+ poison counters.
        if player.poison_counters >= 10 {
            if let Some(p) = state.players.get_mut(&id) {
                p.has_lost = true;
            }
            events.push(GameEvent::PlayerLost {
                player: id,
                reason: LossReason::PoisonCounters,
            });
            continue;
        }

        // CR 704.5u (Commander): 21+ combat damage from a single commander.
        // MR-M4-01: use if-let instead of unwrap — player may have been removed mid-pass.
        let Some(player_ref) = state.players.get(&id) else {
            continue;
        };
        let lost_to_cmdr = player_ref
            .commander_damage_received
            .values()
            .any(|by_card| by_card.values().any(|&dmg| dmg >= 21));
        if lost_to_cmdr {
            if let Some(p) = state.players.get_mut(&id) {
                p.has_lost = true;
            }
            events.push(GameEvent::PlayerLost {
                player: id,
                reason: LossReason::CommanderDamage,
            });
        }
    }

    events
}

// ── CR 704.5d ────────────────────────────────────────────────────────────────

/// CR 704.5d: If a token is in a zone other than the battlefield, it ceases to exist.
///
/// Tokens are never put into any zone during SBA checks themselves (tokens die
/// via 704.5f/g/h like normal creatures). But if a token somehow ended up in
/// the graveyard, library, exile, hand, or stack by some other means, it is
/// removed here.
fn check_token_sbas(state: &mut GameState) -> Vec<GameEvent> {
    let mut events = Vec::new();

    let token_ids: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(_, obj)| obj.is_token && obj.zone != ZoneId::Battlefield)
        .map(|(id, _)| *id)
        .collect();

    for id in token_ids {
        // Remove from its zone and from the objects map.
        if let Some(obj) = state.objects.get(&id) {
            let zone_id = obj.zone;
            // Remove from zone.
            if let Some(zone) = state.zones.get_mut(&zone_id) {
                zone.remove(&id);
            }
        }
        state.objects.remove(&id);
        events.push(GameEvent::TokenCeasedToExist { object_id: id });
    }

    events
}

// ── CR 704.5f / 704.5g / 704.5h ─────────────────────────────────────────────

/// CR 704.5f: Creature with toughness ≤ 0 → owner's graveyard.
/// CR 704.5g: Creature with lethal damage (damage_marked ≥ toughness > 0) → destroyed.
/// CR 704.5h: Creature that was dealt damage by a deathtouch source → destroyed.
///
/// "Destroyed" in 704.5g/h means moved to the owner's graveyard. Indestructible
/// creatures are not destroyed by 704.5g/h (CR 702.12a). Indestructibility (and other
/// characteristics) is evaluated via `chars_map` — the layer-computed snapshot — so
/// continuous effects that remove indestructible or lower toughness are correctly seen.
fn check_creature_sbas(
    state: &mut GameState,
    chars_map: &HashMap<ObjectId, Characteristics>,
) -> Vec<GameEvent> {
    let mut events = Vec::new();

    // Collect creatures on the battlefield that need to die.
    // MR-M5-02: use `chars_map` (layer-computed) instead of raw `obj.characteristics`.
    // damage_marked and deathtouch_damage remain on the GameObject (not in chars).
    let dying: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(id, obj)| {
            if obj.zone != ZoneId::Battlefield {
                return false;
            }

            // Use layer-computed characteristics so continuous effects are visible.
            let Some(chars) = chars_map.get(id) else {
                return false;
            };

            if !chars.card_types.contains(&CardType::Creature) {
                return false;
            }

            // CR 704.5f/g/h only apply to creatures with a defined toughness.
            // A creature without toughness (e.g., a test card) is skipped.
            let Some(toughness) = chars.toughness else {
                return false;
            };

            // MR-M5-02: indestructible is now read from layer-computed keywords —
            // an effect that removes Indestructible (e.g., Humility) is correctly seen.
            let is_indestructible = chars.keywords.contains(&KeywordAbility::Indestructible);

            // CR 704.5f: toughness ≤ 0. Indestructible does NOT prevent this
            // (CR 702.12a only prevents "destroy"; zero-toughness is a state replacement).
            if toughness <= 0 {
                return true;
            }

            // CR 704.5g: lethal damage (damage ≥ toughness > 0).
            // CR 702.12a: Indestructible creatures cannot be destroyed — skip.
            // MR-M4-04: compare in u32 space to avoid u32→i32 wrapping on large damage values.
            // toughness > 0 is guaranteed by the check above, so the cast is safe.
            if !is_indestructible && obj.damage_marked > 0 && obj.damage_marked >= toughness as u32
            {
                return true;
            }

            // CR 704.5h: any damage from a deathtouch source.
            // CR 702.12a: Indestructible creatures cannot be destroyed — skip.
            if !is_indestructible && obj.deathtouch_damage && obj.damage_marked > 0 {
                return true;
            }

            false
        })
        .map(|(id, _)| *id)
        .collect();

    for id in dying {
        // Skip objects that already have a pending replacement choice.
        if state.pending_zone_changes.iter().any(|p| p.object_id == id) {
            continue;
        }

        let owner = match state.objects.get(&id) {
            Some(obj) => obj.owner,
            None => continue, // Already removed in a previous SBA this pass.
        };

        // CR 614: Check replacement effects before moving to graveyard.
        let action = replacement::check_zone_change_replacement(
            state,
            id,
            ZoneType::Battlefield,
            ZoneType::Graveyard,
            owner,
            &std::collections::HashSet::new(),
        );

        match action {
            replacement::ZoneChangeAction::Proceed => {
                // No replacement — move to graveyard normally.
                if let Ok((new_id, _)) = state.move_object_to_zone(id, ZoneId::Graveyard(owner)) {
                    events.push(GameEvent::CreatureDied {
                        object_id: id,
                        new_grave_id: new_id,
                    });
                }
            }
            replacement::ZoneChangeAction::Redirect {
                to,
                events: repl_events,
                ..
            } => {
                // Single replacement auto-applied — redirect zone.
                events.extend(repl_events);
                if let Ok((new_id, _)) = state.move_object_to_zone(id, to) {
                    match to {
                        ZoneId::Exile => {
                            events.push(GameEvent::ObjectExiled {
                                player: owner,
                                object_id: id,
                                new_exile_id: new_id,
                            });
                        }
                        ZoneId::Command(_) => {
                            // Commander redirected to command zone — no CreatureDied.
                        }
                        _ => {
                            events.push(GameEvent::CreatureDied {
                                object_id: id,
                                new_grave_id: new_id,
                            });
                        }
                    }
                }
            }
            replacement::ZoneChangeAction::ChoiceRequired {
                player,
                choices,
                event_description,
            } => {
                // Multiple replacements — defer until player chooses.
                state.pending_zone_changes.push_back(PendingZoneChange {
                    object_id: id,
                    original_from: ZoneType::Battlefield,
                    original_destination: ZoneType::Graveyard,
                    affected_player: player,
                    already_applied: Vec::new(),
                });
                events.push(GameEvent::ReplacementChoiceRequired {
                    player,
                    event_description,
                    choices,
                });
            }
        }
    }

    events
}

// ── CR 704.5i ────────────────────────────────────────────────────────────────

/// CR 704.5i: Planeswalker with 0 loyalty counters → owner's graveyard.
///
/// Loyalty is tracked in two ways (M4 supports both):
/// - `Characteristics.loyalty`: base loyalty set at construction (standard for M4 tests).
/// - `CounterType::Loyalty` counters: added/removed by loyalty abilities (M7+).
///
/// A planeswalker dies if its effective loyalty is ≤ 0. Effective loyalty =
/// Loyalty counter total if present, otherwise `Characteristics.loyalty`.
fn check_planeswalker_sbas(
    state: &mut GameState,
    chars_map: &HashMap<ObjectId, Characteristics>,
) -> Vec<GameEvent> {
    let mut events = Vec::new();

    // MR-M5-02: use layer-computed characteristics so continuous effects are visible.
    let dying: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(id, obj)| {
            if obj.zone != ZoneId::Battlefield {
                return false;
            }
            let Some(chars) = chars_map.get(id) else {
                return false;
            };
            if !chars.card_types.contains(&CardType::Planeswalker) {
                return false;
            }
            // Effective loyalty: use Loyalty counter if present, else Characteristics.loyalty.
            // MR-M4-05: compare in the natural type of each branch to avoid u32→i32 wrapping.
            // Loyalty counters are u32 — dead when the counter reaches 0.
            // Base loyalty (i32) can start at 0 or be set negative by effects.
            let loyalty_counter = obj.counters.get(&CounterType::Loyalty).copied();
            match loyalty_counter {
                Some(counter_value) => counter_value == 0,
                None => chars.loyalty.unwrap_or(1) <= 0,
            }
        })
        .map(|(id, _)| *id)
        .collect();

    for id in dying {
        // Skip objects that already have a pending replacement choice.
        if state.pending_zone_changes.iter().any(|p| p.object_id == id) {
            continue;
        }

        let owner = match state.objects.get(&id) {
            Some(obj) => obj.owner,
            None => continue,
        };

        // CR 614: Check replacement effects before moving to graveyard.
        let action = replacement::check_zone_change_replacement(
            state,
            id,
            ZoneType::Battlefield,
            ZoneType::Graveyard,
            owner,
            &std::collections::HashSet::new(),
        );

        match action {
            replacement::ZoneChangeAction::Proceed => {
                if let Ok((new_id, _)) = state.move_object_to_zone(id, ZoneId::Graveyard(owner)) {
                    events.push(GameEvent::PlaneswalkerDied {
                        object_id: id,
                        new_grave_id: new_id,
                    });
                }
            }
            replacement::ZoneChangeAction::Redirect {
                to,
                events: repl_events,
                ..
            } => {
                events.extend(repl_events);
                if let Ok((new_id, _)) = state.move_object_to_zone(id, to) {
                    match to {
                        ZoneId::Exile => {
                            events.push(GameEvent::ObjectExiled {
                                player: owner,
                                object_id: id,
                                new_exile_id: new_id,
                            });
                        }
                        ZoneId::Command(_) => {}
                        _ => {
                            events.push(GameEvent::PlaneswalkerDied {
                                object_id: id,
                                new_grave_id: new_id,
                            });
                        }
                    }
                }
            }
            replacement::ZoneChangeAction::ChoiceRequired {
                player,
                choices,
                event_description,
            } => {
                state.pending_zone_changes.push_back(PendingZoneChange {
                    object_id: id,
                    original_from: ZoneType::Battlefield,
                    original_destination: ZoneType::Graveyard,
                    affected_player: player,
                    already_applied: Vec::new(),
                });
                events.push(GameEvent::ReplacementChoiceRequired {
                    player,
                    event_description,
                    choices,
                });
            }
        }
    }

    events
}

// ── CR 704.5j ────────────────────────────────────────────────────────────────

/// CR 704.5j: If a player controls two or more legendary permanents with the
/// same name, that player keeps one and the rest go to their owners' graveyards.
///
/// Auto-choice policy (M4): keep the permanent with the highest ObjectId
/// (most recently entered the battlefield). Real player choice is M7+.
fn check_legendary_rule(state: &mut GameState) -> Vec<GameEvent> {
    let mut events = Vec::new();

    // Gather all legendary battlefield permanents, grouped by (controller, name).
    // Key: (PlayerId, name) → Vec<ObjectId> sorted ascending (lowest = oldest).
    let mut by_controller_name: OrdMap<(PlayerId, String), Vec<ObjectId>> = OrdMap::new();

    for (id, obj) in &state.objects {
        if obj.zone != ZoneId::Battlefield {
            continue;
        }
        if !obj
            .characteristics
            .supertypes
            .contains(&SuperType::Legendary)
        {
            continue;
        }
        let key = (obj.controller, obj.characteristics.name.clone());
        by_controller_name.entry(key).or_default().push(*id);
    }

    for ((controller, _name), mut ids) in by_controller_name {
        if ids.len() < 2 {
            continue; // No violation.
        }

        // Sort by ObjectId: highest = most recently entered. Keep the last one.
        // MR-M4-03: let-else instead of unwrap (ids.len() >= 2 is checked above).
        ids.sort();
        let Some(&kept) = ids.last() else {
            continue;
        };
        let to_remove = &ids[..ids.len() - 1];

        let mut graves: Vec<(ObjectId, ObjectId)> = Vec::new();

        for &old_id in to_remove {
            let owner = match state.objects.get(&old_id) {
                Some(obj) => obj.owner,
                None => continue,
            };
            // Use owner of the object, not the controller (could differ).
            if let Ok((new_id, _)) = state.move_object_to_zone(old_id, ZoneId::Graveyard(owner)) {
                graves.push((old_id, new_id));
            }
        }

        if !graves.is_empty() {
            events.push(GameEvent::LegendaryRuleApplied {
                kept_id: kept,
                put_to_graveyard: graves,
            });

            // Suppress unused variable warning: controller is used as the map key above.
            let _ = controller;
        }
    }

    events
}

// ── CR 704.5m ────────────────────────────────────────────────────────────────

/// CR 704.5m: If an Aura is attached to an object or player it can't legally
/// be attached to, put it into its owner's graveyard.
///
/// For M4: an aura is illegal if its `attached_to` references an object that
/// is no longer on the battlefield (the object moved zones). Full legality
/// checking (protection, shroud, color requirements) is M7+.
fn check_aura_sbas(state: &mut GameState) -> Vec<GameEvent> {
    let mut events = Vec::new();

    let illegal_auras: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(_, obj)| {
            if obj.zone != ZoneId::Battlefield {
                return false;
            }
            if !obj
                .characteristics
                .subtypes
                .contains(&SubType("Aura".to_string()))
            {
                return false;
            }
            // Aura is illegal if it's not attached to anything on the battlefield.
            match obj.attached_to {
                None => true, // Unattached aura — always illegal on battlefield.
                Some(target_id) => {
                    // Illegal if the target is gone or not on the battlefield.
                    state
                        .objects
                        .get(&target_id)
                        .map(|t| t.zone != ZoneId::Battlefield)
                        .unwrap_or(true)
                }
            }
        })
        .map(|(id, _)| *id)
        .collect();

    for id in illegal_auras {
        let owner = match state.objects.get(&id) {
            Some(obj) => obj.owner,
            None => continue,
        };

        if let Ok((new_id, _)) = state.move_object_to_zone(id, ZoneId::Graveyard(owner)) {
            events.push(GameEvent::AuraFellOff {
                object_id: id,
                new_grave_id: new_id,
            });
        }
    }

    events
}

// ── CR 704.5n ────────────────────────────────────────────────────────────────

/// CR 704.5n: If an Equipment or Fortification is attached to an illegal
/// permanent, it becomes unattached.
///
/// Equipment must be attached to a creature. Fortification must be attached
/// to a land. For M4: an equipment is illegal if its `attached_to` references
/// an object that is not on the battlefield or not a creature.
fn check_equipment_sbas(
    state: &mut GameState,
    chars_map: &HashMap<ObjectId, Characteristics>,
) -> Vec<GameEvent> {
    let mut events = Vec::new();

    // MR-M5-02: use layer-computed characteristics for both the equipment's own
    // subtypes (could be added by effects) and the target's card types (e.g., a
    // creature that lost Creature type due to a continuous effect).
    let illegal_equip: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(id, obj)| {
            if obj.zone != ZoneId::Battlefield {
                return false;
            }
            let Some(chars) = chars_map.get(id) else {
                return false;
            };
            let is_equipment = chars.subtypes.contains(&SubType("Equipment".to_string()));
            let is_fortification = chars
                .subtypes
                .contains(&SubType("Fortification".to_string()));
            if !is_equipment && !is_fortification {
                return false;
            }
            match obj.attached_to {
                None => false, // Unequipped equipment on battlefield is fine.
                Some(target_id) => {
                    let target = state.objects.get(&target_id);
                    match target {
                        None => true, // Target gone — unattach.
                        Some(t) => {
                            if t.zone != ZoneId::Battlefield {
                                return true; // Target left battlefield.
                            }
                            // Use layer-computed characteristics for the target's type.
                            let target_chars = chars_map.get(&target_id);
                            match target_chars {
                                None => true, // No characteristics — treat as illegal.
                                Some(tc) => {
                                    if is_equipment {
                                        // Equipment must be on a creature.
                                        !tc.card_types.contains(&CardType::Creature)
                                    } else {
                                        // Fortification must be on a land.
                                        !tc.card_types.contains(&CardType::Land)
                                    }
                                }
                            }
                        }
                    }
                }
            }
        })
        .map(|(id, _)| *id)
        .collect();

    for id in illegal_equip {
        // Unattach: clear attached_to on equipment and remove from target's attachments.
        let target_id = state.objects.get(&id).and_then(|obj| obj.attached_to);

        if let Some(obj) = state.objects.get_mut(&id) {
            obj.attached_to = None;
        }

        if let Some(target_id) = target_id {
            if let Some(target) = state.objects.get_mut(&target_id) {
                target.attachments.retain(|&x| x != id);
            }
        }

        events.push(GameEvent::EquipmentUnattached { object_id: id });
    }

    events
}

// ── CR 704.5q ────────────────────────────────────────────────────────────────

/// CR 704.5q: If a permanent has both a +1/+1 counter and a -1/-1 counter on it,
/// N pairs are removed, where N = min(+1/+1 count, -1/-1 count).
fn check_counter_annihilation(state: &mut GameState) -> Vec<GameEvent> {
    let mut events = Vec::new();

    let ids: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(_, obj)| {
            obj.zone == ZoneId::Battlefield
                && obj
                    .counters
                    .get(&CounterType::PlusOnePlusOne)
                    .copied()
                    .unwrap_or(0)
                    > 0
                && obj
                    .counters
                    .get(&CounterType::MinusOneMinusOne)
                    .copied()
                    .unwrap_or(0)
                    > 0
        })
        .map(|(id, _)| *id)
        .collect();

    for id in ids {
        let Some(obj) = state.objects.get_mut(&id) else {
            continue;
        };

        let plus = obj
            .counters
            .get(&CounterType::PlusOnePlusOne)
            .copied()
            .unwrap_or(0);
        let minus = obj
            .counters
            .get(&CounterType::MinusOneMinusOne)
            .copied()
            .unwrap_or(0);
        let remove = plus.min(minus);

        if remove == 0 {
            continue;
        }

        let new_plus = plus - remove;
        let new_minus = minus - remove;

        if new_plus == 0 {
            obj.counters.remove(&CounterType::PlusOnePlusOne);
        } else {
            obj.counters.insert(CounterType::PlusOnePlusOne, new_plus);
        }

        if new_minus == 0 {
            obj.counters.remove(&CounterType::MinusOneMinusOne);
        } else {
            obj.counters
                .insert(CounterType::MinusOneMinusOne, new_minus);
        }

        events.push(GameEvent::CountersAnnihilated {
            object_id: id,
            amount: remove,
        });
    }

    events
}

// ── Helpers ──────────────────────────────────────────────────────────────────

/// Check if a `KeywordAbility` is present on an object's effective characteristics.
///
/// Uses `calculate_characteristics` (layer system) rather than raw `obj.characteristics`
/// so that continuous effects granting or removing the keyword are correctly reflected.
/// Used by 704.5h deathtouch check and similar keyword-gated SBAs.
#[allow(dead_code)]
pub fn has_keyword(state: &GameState, id: ObjectId, keyword: KeywordAbility) -> bool {
    calculate_characteristics(state, id)
        .map(|chars| chars.keywords.contains(&keyword))
        .unwrap_or(false)
}
