//! Turn-based actions: untap, draw, cleanup, mana pool emptying (CR 500-514).

use crate::state::error::GameStateError;
use crate::state::game_object::ObjectId;
use crate::state::player::PlayerId;
use crate::state::turn::Step;
use crate::state::zone::ZoneId;
use crate::state::GameState;

use super::events::{GameEvent, LossReason};

/// Execute turn-based actions for the current step.
/// Returns events generated by the actions.
pub fn execute_turn_based_actions(state: &mut GameState) -> Result<Vec<GameEvent>, GameStateError> {
    match state.turn.step {
        Step::Untap => Ok(untap_active_player_permanents(state)),
        Step::Draw => draw_for_turn(state),
        Step::Cleanup => Ok(cleanup_actions(state)),
        _ => Ok(Vec::new()),
    }
}

/// CR 502.2: "Second, the active player's phased-out permanents phase in and
/// the active player determines which permanents they control will phase out
/// [...] Then the active player untaps all tapped permanents they control."
///
/// For M2 we skip phasing and just untap.
pub fn untap_active_player_permanents(state: &mut GameState) -> Vec<GameEvent> {
    let active = state.turn.active_player;
    let mut untapped = Vec::new();

    // Collect object IDs to untap (controlled by active player, on battlefield, tapped)
    let ids_to_untap: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(_, obj)| {
            obj.controller == active && obj.zone == ZoneId::Battlefield && obj.status.tapped
        })
        .map(|(id, _)| *id)
        .collect();

    for id in &ids_to_untap {
        if let Some(obj) = state.objects.get_mut(id) {
            obj.status.tapped = false;
            untapped.push(*id);
        }
    }

    if untapped.is_empty() {
        Vec::new()
    } else {
        vec![GameEvent::PermanentsUntapped {
            player: active,
            objects: untapped,
        }]
    }
}

/// CR 504.1: "First, the active player draws a card."
/// CR 103.8: "In multiplayer games using the shared team turns option,
/// the player who plays first skips the draw step of that player's first turn."
///
/// In M2: draws by moving top of library to hand. If library empty,
/// the player loses (CR 104.3b). M4's SBA system will replace this.
fn draw_for_turn(state: &mut GameState) -> Result<Vec<GameEvent>, GameStateError> {
    let active = state.turn.active_player;

    // CR 103.8: first player of the game skips their first draw
    if state.turn.is_first_turn_of_game {
        return Ok(Vec::new());
    }

    draw_card(state, active)
}

/// Draw a card for the given player: move top of library to hand.
/// Returns `PlayerLost` event if library is empty (CR 104.3b).
pub fn draw_card(
    state: &mut GameState,
    player: PlayerId,
) -> Result<Vec<GameEvent>, GameStateError> {
    let library_zone = ZoneId::Library(player);
    let library = state.zone(&library_zone)?;

    let top_id = match library.top() {
        Some(id) => id,
        None => {
            // Library empty — player loses (CR 104.3b)
            if let Some(p) = state.players.get_mut(&player) {
                p.has_lost = true;
            }
            return Ok(vec![GameEvent::PlayerLost {
                player,
                reason: LossReason::LibraryEmpty,
            }]);
        }
    };

    let hand_zone = ZoneId::Hand(player);
    let (new_id, _old_obj) = state.move_object_to_zone(top_id, hand_zone)?;

    // Mark that this player has drawn for the turn
    if let Some(p) = state.players.get_mut(&player) {
        p.has_drawn_for_turn = true;
    }

    Ok(vec![GameEvent::CardDrawn {
        player,
        new_object_id: new_id,
    }])
}

/// CR 514.1: "First, if the active player's hand contains more cards than their
/// maximum hand size [...] that player discards enough cards to reduce the hand
/// size to that number."
///
/// Then CR 514.2: "remove all damage from permanents and end 'until end of turn'
/// and 'this turn' effects."
///
/// M2: auto-discards from end of hand (no player choice). M3+ adds choice.
pub fn cleanup_actions(state: &mut GameState) -> Vec<GameEvent> {
    let active = state.turn.active_player;
    let mut events = Vec::new();

    // Discard to hand size
    let max_hand_size = state
        .players
        .get(&active)
        .map(|p| p.max_hand_size)
        .unwrap_or(7);
    let hand_zone = ZoneId::Hand(active);
    let graveyard_zone = ZoneId::Graveyard(active);

    loop {
        let hand_size = state.zone(&hand_zone).map(|z| z.len()).unwrap_or(0);
        if hand_size <= max_hand_size {
            break;
        }
        // Pick the last object in the hand (arbitrary in M2 — hand is unordered)
        let obj_ids = state
            .zone(&hand_zone)
            .map(|z| z.object_ids())
            .unwrap_or_default();
        if let Some(&discard_id) = obj_ids.last() {
            if let Ok((new_id, _)) = state.move_object_to_zone(discard_id, graveyard_zone) {
                events.push(GameEvent::DiscardedToHandSize {
                    player: active,
                    object_id: new_id,
                    zone_from: hand_zone,
                    zone_to: graveyard_zone,
                });
            }
        } else {
            break;
        }
    }

    // Clear damage from all permanents (CR 514.1)
    clear_damage(state);
    events.push(GameEvent::DamageCleared);

    // Remove "until end of turn" continuous effects (CR 514.2).
    super::layers::expire_end_of_turn_effects(state);

    // Empty mana pools
    empty_all_mana_pools(state);
    events.push(GameEvent::ManaPoolsEmptied);

    events.push(GameEvent::CleanupPerformed);
    events
}

/// CR 500.4: Empty all players' mana pools at step transitions.
pub fn empty_all_mana_pools(state: &mut GameState) -> Vec<GameEvent> {
    let player_ids: Vec<PlayerId> = state
        .players
        .iter()
        .filter(|(_, p)| !p.mana_pool.is_empty())
        .map(|(id, _)| *id)
        .collect();

    if player_ids.is_empty() {
        return Vec::new();
    }

    for id in &player_ids {
        if let Some(p) = state.players.get_mut(id) {
            p.mana_pool.empty();
        }
    }
    vec![GameEvent::ManaPoolsEmptied]
}

/// Set `damage_marked = 0` and clear `deathtouch_damage` on all battlefield permanents (CR 514.1).
pub fn clear_damage(state: &mut GameState) {
    let ids: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(_, obj)| obj.zone == ZoneId::Battlefield && (obj.damage_marked > 0 || obj.deathtouch_damage))
        .map(|(id, _)| *id)
        .collect();

    for id in &ids {
        if let Some(obj) = state.objects.get_mut(id) {
            obj.damage_marked = 0;
            obj.deathtouch_damage = false;
        }
    }
}

/// Reset per-turn state for a player starting their turn.
pub fn reset_turn_state(state: &mut GameState, player: PlayerId) {
    if let Some(p) = state.players.get_mut(&player) {
        p.land_plays_remaining = 1;
        p.has_drawn_for_turn = false;
    }
}
