//! Turn-based actions: untap, draw, cleanup, mana pool emptying, combat (CR 500-514).

use crate::cards::card_definition::{AbilityDefinition, TriggerCondition};
use crate::state::combat::CombatState;
use crate::state::error::GameStateError;
use crate::state::game_object::ObjectId;
use crate::state::player::PlayerId;
use crate::state::stubs::{PendingTrigger, PendingTriggerKind};
use crate::state::turn::Step;
use crate::state::types::AltCostKind;
use crate::state::types::{CounterType, CumulativeUpkeepCost, KeywordAbility};
use crate::state::zone::ZoneId;
use crate::state::GameState;

use super::events::{GameEvent, LossReason};

/// Execute turn-based actions for the current step.
/// Returns events generated by the actions.
pub fn execute_turn_based_actions(state: &mut GameState) -> Result<Vec<GameEvent>, GameStateError> {
    match state.turn.step {
        Step::Untap => Ok(untap_active_player_permanents(state)),
        Step::Upkeep => Ok(upkeep_actions(state)),
        Step::Draw => draw_for_turn(state),
        Step::BeginningOfCombat => Ok(begin_combat(state)),
        Step::FirstStrikeDamage => Ok(first_strike_damage_step(state)),
        Step::CombatDamage => Ok(combat_damage_step(state)),
        Step::EndOfCombat => Ok(end_combat(state)),
        Step::Cleanup => Ok(cleanup_actions(state)),
        Step::End => Ok(end_step_actions(state)),
        _ => Ok(Vec::new()),
    }
}

/// CR 503.1 / CR 702.62a: Upkeep step turn-based actions.
///
/// Queue suspend counter-removal triggers for each suspended card owned by the active
/// player in exile. CR 702.62a (second ability): "At the beginning of your upkeep, if
/// this card is suspended, remove a time counter from it."
///
/// A card is "suspended" (CR 702.62b) if:
/// - It is in the exile zone,
/// - It has the Suspend keyword ability, AND
/// - It has one or more time counters on it.
///
/// These are triggered abilities (not turn-based actions); they use the stack and can be
/// countered (e.g., Stifle prevents a time counter from being removed). In multiplayer,
/// only the ACTIVE player's suspended cards tick down on their own upkeep.
fn upkeep_actions(state: &mut GameState) -> Vec<GameEvent> {
    let active = state.turn.active_player;

    // Collect suspended cards in exile owned by the active player.
    // CR 702.62b: Must have suspend keyword, be in exile, AND have time counters.
    let suspended_cards: Vec<ObjectId> = state
        .objects
        .values()
        .filter(|obj| {
            obj.zone == ZoneId::Exile
                && obj.owner == active
                && obj.is_suspended
                && obj.counters.get(&CounterType::Time).copied().unwrap_or(0) > 0
        })
        .map(|obj| obj.id)
        .collect();

    for card_id in suspended_cards {
        // CR 702.62a: Queue a suspend counter-removal trigger. These go on the stack
        // in APNAP order (all controlled by active player here, so order is FIFO).
        state.pending_triggers.push_back(PendingTrigger {
            source: card_id,
            ability_index: 0,
            controller: active,
            kind: PendingTriggerKind::SuspendCounter,
            triggering_event: None,
            entering_object_id: None,
            targeting_stack_id: None,
            triggering_player: None,
            exalted_attacker_id: None,
            defending_player_id: None,
            madness_exiled_card: None,
            madness_cost: None,
            miracle_revealed_card: None,
            miracle_cost: None,
            modular_counter_count: None,
            evolve_entering_creature: None,
            suspend_card_id: Some(card_id),
            hideaway_count: None,
            partner_with_name: None,
            ingest_target_player: None,
            flanking_blocker_id: None,
            rampage_n: None,
            provoke_target_creature: None,
            renown_n: None,
            poisonous_n: None,
            poisonous_target_player: None,
            enlist_enlisted_creature: None,
            encore_activator: None,
            echo_cost: None,
            cumulative_upkeep_cost: None,
            recover_cost: None,
            recover_card: None,
            graft_entering_creature: None,
            backup_abilities: None,
            backup_n: None,
            champion_filter: None,
            champion_exiled_card: None,
            soulbond_pair_target: None,
            squad_count: None,
            gift_opponent: None,
            cipher_encoded_card_id: None,
            cipher_encoded_object_id: None,
            haunt_source_object_id: None,
            haunt_source_card_id: None,
        });
    }

    // CR 702.63a: Queue counter-removal triggers for all Vanishing permanents.
    // "At the beginning of your upkeep, if this permanent has a time counter on it,
    // remove a time counter from it."
    //
    // Only fires for permanents controlled by the active player (CR 702.63a: "your upkeep").
    // CR 702.63c: Each Vanishing instance triggers separately -- count instances and
    // queue one trigger per instance.
    // The trigger has an intervening-if condition (CR 603.4): re-checked at resolution.
    let vanishing_permanents: Vec<(ObjectId, usize)> = state
        .objects
        .values()
        .filter(|obj| {
            obj.zone == ZoneId::Battlefield
                && obj.controller == active
                && obj.counters.get(&CounterType::Time).copied().unwrap_or(0) > 0
                && obj
                    .characteristics
                    .keywords
                    .iter()
                    .any(|kw| matches!(kw, KeywordAbility::Vanishing(_)))
        })
        .map(|obj| {
            // Count Vanishing instances for CR 702.63c (each works separately).
            let instance_count = obj
                .characteristics
                .keywords
                .iter()
                .filter(|kw| matches!(kw, KeywordAbility::Vanishing(_)))
                .count();
            (obj.id, instance_count)
        })
        .collect();

    for (obj_id, instance_count) in vanishing_permanents {
        for _ in 0..instance_count {
            state.pending_triggers.push_back(PendingTrigger {
                source: obj_id,
                ability_index: 0, // unused for vanishing counter triggers
                controller: active,
                kind: PendingTriggerKind::VanishingCounter,
                triggering_event: None,
                entering_object_id: None,
                targeting_stack_id: None,
                triggering_player: None,
                exalted_attacker_id: None,
                defending_player_id: None,
                madness_exiled_card: None,
                madness_cost: None,
                miracle_revealed_card: None,
                miracle_cost: None,
                modular_counter_count: None,
                evolve_entering_creature: None,
                suspend_card_id: None,
                hideaway_count: None,
                partner_with_name: None,
                ingest_target_player: None,
                flanking_blocker_id: None,
                rampage_n: None,
                provoke_target_creature: None,
                renown_n: None,
                poisonous_n: None,
                poisonous_target_player: None,
                enlist_enlisted_creature: None,
                encore_activator: None,
                echo_cost: None,
                cumulative_upkeep_cost: None,
                recover_cost: None,
                recover_card: None,
                graft_entering_creature: None,
                backup_abilities: None,
                backup_n: None,
                champion_filter: None,
                champion_exiled_card: None,
                soulbond_pair_target: None,
                squad_count: None,
                gift_opponent: None,
                cipher_encoded_card_id: None,
                cipher_encoded_object_id: None,
                haunt_source_object_id: None,
                haunt_source_card_id: None,
            });
        }
    }

    // CR 702.32a: Queue upkeep triggers for all Fading permanents.
    // "At the beginning of your upkeep, remove a fade counter from this permanent.
    // If you can't, sacrifice the permanent."
    //
    // Only fires for permanents controlled by the active player (CR 702.32a: "your upkeep").
    // Unlike Vanishing, Fading has NO intervening-if condition -- the trigger fires regardless
    // of whether the permanent has fade counters. The "if you can't" is resolved at trigger
    // resolution, not as a filter on queueing.
    // Multiple instances of Fading each trigger separately.
    let fading_permanents: Vec<(ObjectId, usize)> = state
        .objects
        .values()
        .filter(|obj| {
            obj.zone == ZoneId::Battlefield
                && obj.controller == active
                && obj
                    .characteristics
                    .keywords
                    .iter()
                    .any(|kw| matches!(kw, KeywordAbility::Fading(_)))
        })
        .map(|obj| {
            // Count Fading instances (each triggers separately).
            let instance_count = obj
                .characteristics
                .keywords
                .iter()
                .filter(|kw| matches!(kw, KeywordAbility::Fading(_)))
                .count();
            (obj.id, instance_count)
        })
        .collect();

    for (obj_id, instance_count) in fading_permanents {
        for _ in 0..instance_count {
            state.pending_triggers.push_back(PendingTrigger {
                source: obj_id,
                ability_index: 0, // unused for fading triggers
                controller: active,
                kind: PendingTriggerKind::FadingUpkeep,
                triggering_event: None,
                entering_object_id: None,
                targeting_stack_id: None,
                triggering_player: None,
                exalted_attacker_id: None,
                defending_player_id: None,
                madness_exiled_card: None,
                madness_cost: None,
                miracle_revealed_card: None,
                miracle_cost: None,
                modular_counter_count: None,
                evolve_entering_creature: None,
                suspend_card_id: None,
                hideaway_count: None,
                partner_with_name: None,
                ingest_target_player: None,
                flanking_blocker_id: None,
                rampage_n: None,
                provoke_target_creature: None,
                renown_n: None,
                poisonous_n: None,
                poisonous_target_player: None,
                enlist_enlisted_creature: None,
                encore_activator: None,
                echo_cost: None,
                cumulative_upkeep_cost: None,
                recover_cost: None,
                recover_card: None,
                graft_entering_creature: None,
                backup_abilities: None,
                backup_n: None,
                champion_filter: None,
                champion_exiled_card: None,
                soulbond_pair_target: None,
                squad_count: None,
                gift_opponent: None,
                cipher_encoded_card_id: None,
                cipher_encoded_object_id: None,
                haunt_source_object_id: None,
                haunt_source_card_id: None,
            });
        }
    }

    // CR 702.30a: Queue upkeep triggers for all Echo permanents with echo_pending.
    // "At the beginning of your upkeep, if this permanent came under your control
    // since the beginning of your last upkeep, sacrifice it unless you pay [cost]."
    //
    // Only fires for permanents controlled by the active player (CR 702.30a: "your upkeep").
    // Intervening-if: echo_pending must be true AND the permanent still has
    // KeywordAbility::Echo(_) in its layer-resolved characteristics (per gotchas-infra.md:
    // "parameterized keyword N-value extraction must use layer-resolved chars").
    // This ensures effects like Humility that remove Echo prevent the trigger from firing.
    // Multiple instances of Echo each trigger separately (per CR 603.2b).
    let echo_permanents: Vec<(ObjectId, Vec<crate::state::game_object::ManaCost>)> = state
        .objects
        .values()
        .filter(|obj| {
            obj.zone == ZoneId::Battlefield && obj.controller == active && obj.echo_pending
        })
        .map(|obj| {
            let echo_costs: Vec<crate::state::game_object::ManaCost> = obj
                .characteristics
                .keywords
                .iter()
                .filter_map(|kw| {
                    if let KeywordAbility::Echo(cost) = kw {
                        Some(cost.clone())
                    } else {
                        None
                    }
                })
                .collect();
            (obj.id, echo_costs)
        })
        .filter(|(_, costs)| !costs.is_empty())
        .collect();

    for (obj_id, costs) in echo_permanents {
        for cost in costs {
            state.pending_triggers.push_back(PendingTrigger {
                source: obj_id,
                ability_index: 0, // unused for echo triggers
                controller: active,
                kind: PendingTriggerKind::EchoUpkeep,
                triggering_event: None,
                entering_object_id: None,
                targeting_stack_id: None,
                triggering_player: None,
                exalted_attacker_id: None,
                defending_player_id: None,
                madness_exiled_card: None,
                madness_cost: None,
                miracle_revealed_card: None,
                miracle_cost: None,
                modular_counter_count: None,
                evolve_entering_creature: None,
                suspend_card_id: None,
                hideaway_count: None,
                partner_with_name: None,
                ingest_target_player: None,
                flanking_blocker_id: None,
                rampage_n: None,
                provoke_target_creature: None,
                renown_n: None,
                poisonous_n: None,
                poisonous_target_player: None,
                enlist_enlisted_creature: None,
                encore_activator: None,
                echo_cost: Some(cost),
                cumulative_upkeep_cost: None,
                recover_cost: None,
                recover_card: None,
                graft_entering_creature: None,
                backup_abilities: None,
                backup_n: None,
                champion_filter: None,
                champion_exiled_card: None,
                soulbond_pair_target: None,
                squad_count: None,
                gift_opponent: None,
                cipher_encoded_card_id: None,
                cipher_encoded_object_id: None,
                haunt_source_object_id: None,
                haunt_source_card_id: None,
            });
        }
    }

    // CR 702.24a: Queue upkeep triggers for all cumulative upkeep permanents.
    // "At the beginning of your upkeep, if this permanent is on the battlefield,
    // put an age counter on this permanent. Then you may pay [cost] for each age
    // counter on it. If you don't, sacrifice it."
    //
    // Only fires for permanents controlled by the active player (CR 702.24a: "your upkeep").
    // Uses layer-resolved characteristics to check for CumulativeUpkeep keyword.
    // CR 702.24b: Each instance triggers separately.
    // NOTE: No pending flag needed -- cumulative upkeep fires EVERY upkeep unconditionally.
    let cu_permanents: Vec<(ObjectId, Vec<CumulativeUpkeepCost>)> = state
        .objects
        .values()
        .filter(|obj| obj.zone == ZoneId::Battlefield && obj.controller == active)
        .map(|obj| {
            let cu_costs: Vec<CumulativeUpkeepCost> = obj
                .characteristics
                .keywords
                .iter()
                .filter_map(|kw| {
                    if let KeywordAbility::CumulativeUpkeep(cost) = kw {
                        Some(cost.clone())
                    } else {
                        None
                    }
                })
                .collect();
            (obj.id, cu_costs)
        })
        .filter(|(_, costs)| !costs.is_empty())
        .collect();

    for (obj_id, costs) in cu_permanents {
        for cost in costs {
            state.pending_triggers.push_back(PendingTrigger {
                source: obj_id,
                ability_index: 0, // unused for CU triggers
                controller: active,
                kind: PendingTriggerKind::CumulativeUpkeep,
                triggering_event: None,
                entering_object_id: None,
                targeting_stack_id: None,
                triggering_player: None,
                exalted_attacker_id: None,
                defending_player_id: None,
                madness_exiled_card: None,
                madness_cost: None,
                miracle_revealed_card: None,
                miracle_cost: None,
                modular_counter_count: None,
                evolve_entering_creature: None,
                suspend_card_id: None,
                hideaway_count: None,
                partner_with_name: None,
                ingest_target_player: None,
                flanking_blocker_id: None,
                rampage_n: None,
                provoke_target_creature: None,
                renown_n: None,
                poisonous_n: None,
                poisonous_target_player: None,
                enlist_enlisted_creature: None,
                encore_activator: None,
                echo_cost: None,
                cumulative_upkeep_cost: Some(cost),
                recover_cost: None,
                recover_card: None,
                graft_entering_creature: None,
                backup_abilities: None,
                backup_n: None,
                champion_filter: None,
                champion_exiled_card: None,
                soulbond_pair_target: None,
                squad_count: None,
                gift_opponent: None,
                cipher_encoded_card_id: None,
                cipher_encoded_object_id: None,
                haunt_source_object_id: None,
                haunt_source_card_id: None,
            });
        }
    }

    // CR 603.3: Generic CardDef upkeep trigger sweep (MR-B9-01).
    //
    // Fire AbilityDefinition::Triggered abilities with AtBeginningOfYourUpkeep (for active
    // player's permanents) or AtBeginningOfEachUpkeep (for all players' permanents) conditions.
    //
    // Hardcoded keyword triggers (Suspend, Vanishing, Fading, Echo, CumulativeUpkeep) are
    // handled by the blocks above; this sweep catches all other CardDef-defined upkeep triggers
    // (e.g., Dreadhorde Invasion's life-loss + amass, Champion's paired trigger, etc.).
    //
    // CR 603.4: Intervening-if conditions (if any) are checked at resolution via the Normal
    // trigger dispatch path, consistent with all other CardDef trigger handling.
    let carddef_upkeep_triggers: Vec<(ObjectId, PlayerId, Vec<usize>)> = {
        let registry = &state.card_registry;
        state
            .objects
            .values()
            .filter(|obj| obj.zone == ZoneId::Battlefield && !obj.status.phased_out)
            .filter_map(|obj| {
                let card_id = obj.card_id.as_ref()?;
                let def = registry.get(card_id.clone())?;
                let controller = obj.controller;
                let indices: Vec<usize> = def
                    .abilities
                    .iter()
                    .enumerate()
                    .filter_map(|(idx, abil)| {
                        let AbilityDefinition::Triggered {
                            trigger_condition, ..
                        } = abil
                        else {
                            return None;
                        };
                        let fires = (matches!(
                            trigger_condition,
                            TriggerCondition::AtBeginningOfYourUpkeep
                        ) && controller == active)
                            || matches!(
                                trigger_condition,
                                TriggerCondition::AtBeginningOfEachUpkeep
                            );
                        fires.then_some(idx)
                    })
                    .collect();
                if indices.is_empty() {
                    None
                } else {
                    Some((obj.id, controller, indices))
                }
            })
            .collect()
    };

    for (obj_id, controller, indices) in carddef_upkeep_triggers {
        for ability_index in indices {
            state.pending_triggers.push_back(PendingTrigger {
                source: obj_id,
                ability_index,
                controller,
                kind: PendingTriggerKind::Normal,
                triggering_event: None,
                entering_object_id: None,
                targeting_stack_id: None,
                triggering_player: None,
                exalted_attacker_id: None,
                defending_player_id: None,
                madness_exiled_card: None,
                madness_cost: None,
                miracle_revealed_card: None,
                miracle_cost: None,
                modular_counter_count: None,
                evolve_entering_creature: None,
                suspend_card_id: None,
                hideaway_count: None,
                partner_with_name: None,
                ingest_target_player: None,
                flanking_blocker_id: None,
                rampage_n: None,
                provoke_target_creature: None,
                renown_n: None,
                poisonous_n: None,
                poisonous_target_player: None,
                enlist_enlisted_creature: None,
                encore_activator: None,
                echo_cost: None,
                cumulative_upkeep_cost: None,
                recover_cost: None,
                recover_card: None,
                graft_entering_creature: None,
                backup_abilities: None,
                backup_n: None,
                champion_filter: None,
                champion_exiled_card: None,
                soulbond_pair_target: None,
                squad_count: None,
                gift_opponent: None,
                cipher_encoded_card_id: None,
                cipher_encoded_object_id: None,
                haunt_source_object_id: None,
                haunt_source_card_id: None,
            });
        }
    }

    Vec::new() // No direct events; triggers are flushed by enter_step
}

/// CR 702.84a: End step actions -- queue delayed exile triggers for all unearthed permanents.
///
/// "Exile it at the beginning of the next end step."
/// At the beginning of the end step, scan all battlefield permanents with
/// `was_unearthed == true` and queue a `UnearthTrigger` for each one.
///
/// These are delayed triggered abilities created when the unearth ability resolved.
/// They can be countered (e.g., by Stifle); the replacement effect persists independently.
pub fn end_step_actions(state: &mut GameState) -> Vec<GameEvent> {
    // Collect unearthed permanents on the battlefield.
    let unearthed: Vec<(ObjectId, crate::state::player::PlayerId)> = state
        .objects
        .values()
        .filter(|obj| obj.zone == ZoneId::Battlefield && obj.was_unearthed)
        .map(|obj| (obj.id, obj.controller))
        .collect();

    for (obj_id, controller) in unearthed {
        state.pending_triggers.push_back(PendingTrigger {
            source: obj_id,
            ability_index: 0, // unused for unearth triggers
            controller,
            kind: PendingTriggerKind::Unearth,
            triggering_event: None,
            entering_object_id: None,
            targeting_stack_id: None,
            triggering_player: None,
            exalted_attacker_id: None,
            defending_player_id: None,
            madness_exiled_card: None,
            madness_cost: None,
            miracle_revealed_card: None,
            miracle_cost: None,
            modular_counter_count: None,
            evolve_entering_creature: None,
            suspend_card_id: None,
            hideaway_count: None,
            partner_with_name: None,
            ingest_target_player: None,
            flanking_blocker_id: None,
            rampage_n: None,
            provoke_target_creature: None,
            renown_n: None,
            poisonous_n: None,
            poisonous_target_player: None,
            enlist_enlisted_creature: None,
            encore_activator: None,
            echo_cost: None,
            cumulative_upkeep_cost: None,
            recover_cost: None,
            recover_card: None,
            graft_entering_creature: None,
            backup_abilities: None,
            backup_n: None,
            champion_filter: None,
            champion_exiled_card: None,
            soulbond_pair_target: None,
            squad_count: None,
            gift_opponent: None,
            cipher_encoded_card_id: None,
            cipher_encoded_object_id: None,
            haunt_source_object_id: None,
            haunt_source_card_id: None,
        });
    }

    // CR 702.141a: Queue sacrifice triggers for all encore tokens on the battlefield.
    // "Sacrifice them at the beginning of the next end step."
    // Each encore token is tagged with `encore_sacrifice_at_end_step = true` when
    // the EncoreAbility resolves. The activator is stored in `encore_activated_by`
    // on the token (ruling 2020-11-10: if control changes, token cannot be sacrificed,
    // so we must use the original activator identity, not the current controller).
    let encore_tokens: Vec<(
        ObjectId,
        crate::state::player::PlayerId,
        Option<crate::state::player::PlayerId>,
    )> = state
        .objects
        .values()
        .filter(|obj| {
            obj.zone == crate::state::zone::ZoneId::Battlefield && obj.encore_sacrifice_at_end_step
        })
        .map(|obj| (obj.id, obj.controller, obj.encore_activated_by))
        .collect();

    for (obj_id, controller, encore_activated_by) in encore_tokens {
        state.pending_triggers.push_back(PendingTrigger {
            source: obj_id,
            ability_index: 0, // unused for encore sacrifice triggers
            controller,
            kind: PendingTriggerKind::EncoreSacrifice,
            triggering_event: None,
            entering_object_id: None,
            targeting_stack_id: None,
            triggering_player: None,
            exalted_attacker_id: None,
            defending_player_id: None,
            madness_exiled_card: None,
            madness_cost: None,
            miracle_revealed_card: None,
            miracle_cost: None,
            modular_counter_count: None,
            evolve_entering_creature: None,
            suspend_card_id: None,
            hideaway_count: None,
            partner_with_name: None,
            ingest_target_player: None,
            flanking_blocker_id: None,
            rampage_n: None,
            provoke_target_creature: None,
            renown_n: None,
            poisonous_n: None,
            poisonous_target_player: None,
            enlist_enlisted_creature: None,
            // Ruling 2020-11-10: use the stored original activator, not the current
            // controller. If encore_activated_by is unset (e.g., old state from before
            // this field was added), fall back to current controller.
            encore_activator: encore_activated_by.or(Some(controller)),
            echo_cost: None,
            cumulative_upkeep_cost: None,
            recover_cost: None,
            recover_card: None,
            graft_entering_creature: None,
            backup_abilities: None,
            backup_n: None,
            champion_filter: None,
            champion_exiled_card: None,
            soulbond_pair_target: None,
            squad_count: None,
            gift_opponent: None,
            cipher_encoded_card_id: None,
            cipher_encoded_object_id: None,
            haunt_source_object_id: None,
            haunt_source_card_id: None,
        });
    }

    // CR 702.109a: Queue return-to-hand triggers for all dashed permanents.
    // "Return the permanent this spell becomes to its owner's hand at the
    // beginning of the next end step."
    // Each dashed permanent has `cast_alt_cost == Some(AltCostKind::Dash)` set when
    // the dash spell resolves (resolution.rs). At end step, we queue a DashReturnTrigger.
    let dashed_permanents: Vec<(ObjectId, crate::state::player::PlayerId)> = state
        .objects
        .values()
        .filter(|obj| {
            obj.zone == ZoneId::Battlefield && obj.cast_alt_cost == Some(AltCostKind::Dash)
        })
        .map(|obj| (obj.id, obj.controller))
        .collect();

    for (obj_id, controller) in dashed_permanents {
        state.pending_triggers.push_back(PendingTrigger {
            source: obj_id,
            ability_index: 0, // unused for dash return triggers
            controller,
            kind: PendingTriggerKind::DashReturn,
            triggering_event: None,
            entering_object_id: None,
            targeting_stack_id: None,
            triggering_player: None,
            exalted_attacker_id: None,
            defending_player_id: None,
            madness_exiled_card: None,
            madness_cost: None,
            miracle_revealed_card: None,
            miracle_cost: None,
            modular_counter_count: None,
            evolve_entering_creature: None,
            suspend_card_id: None,
            hideaway_count: None,
            partner_with_name: None,
            ingest_target_player: None,
            flanking_blocker_id: None,
            rampage_n: None,
            provoke_target_creature: None,
            renown_n: None,
            poisonous_n: None,
            poisonous_target_player: None,
            enlist_enlisted_creature: None,
            encore_activator: None,
            echo_cost: None,
            cumulative_upkeep_cost: None,
            recover_cost: None,
            recover_card: None,
            graft_entering_creature: None,
            backup_abilities: None,
            backup_n: None,
            champion_filter: None,
            champion_exiled_card: None,
            soulbond_pair_target: None,
            squad_count: None,
            gift_opponent: None,
            cipher_encoded_card_id: None,
            cipher_encoded_object_id: None,
            haunt_source_object_id: None,
            haunt_source_card_id: None,
        });
    }

    // CR 702.152a: Queue sacrifice triggers for all blitzed permanents.
    // "Sacrifice the permanent this spell becomes at the beginning of the
    // next end step."
    // Each blitzed permanent has `cast_alt_cost == Some(AltCostKind::Blitz)` set when
    // the blitz spell resolves (resolution.rs). At end step, we queue a BlitzSacrificeTrigger.
    let blitzed_permanents: Vec<(ObjectId, crate::state::player::PlayerId)> = state
        .objects
        .values()
        .filter(|obj| {
            obj.zone == ZoneId::Battlefield && obj.cast_alt_cost == Some(AltCostKind::Blitz)
        })
        .map(|obj| (obj.id, obj.controller))
        .collect();

    for (obj_id, controller) in blitzed_permanents {
        state.pending_triggers.push_back(PendingTrigger {
            source: obj_id,
            ability_index: 0, // unused for blitz sacrifice triggers
            controller,
            kind: PendingTriggerKind::BlitzSacrifice,
            triggering_event: None,
            entering_object_id: None,
            targeting_stack_id: None,
            triggering_player: None,
            exalted_attacker_id: None,
            defending_player_id: None,
            madness_exiled_card: None,
            madness_cost: None,
            miracle_revealed_card: None,
            miracle_cost: None,
            modular_counter_count: None,
            evolve_entering_creature: None,
            suspend_card_id: None,
            hideaway_count: None,
            partner_with_name: None,
            ingest_target_player: None,
            flanking_blocker_id: None,
            rampage_n: None,
            provoke_target_creature: None,
            renown_n: None,
            poisonous_n: None,
            poisonous_target_player: None,
            enlist_enlisted_creature: None,
            encore_activator: None,
            echo_cost: None,
            cumulative_upkeep_cost: None,
            recover_cost: None,
            recover_card: None,
            graft_entering_creature: None,
            backup_abilities: None,
            backup_n: None,
            champion_filter: None,
            champion_exiled_card: None,
            soulbond_pair_target: None,
            squad_count: None,
            gift_opponent: None,
            cipher_encoded_card_id: None,
            cipher_encoded_object_id: None,
            haunt_source_object_id: None,
            haunt_source_card_id: None,
        });
    }

    // CR 702.176a: Queue counter-removal triggers for all impending permanents.
    // "At the beginning of your end step, if this permanent's impending cost was
    // paid and it has a time counter on it, remove a time counter from it."
    //
    // Only fires for permanents whose controller matches the active player
    // (the player whose end step it is). The trigger has an intervening-if
    // condition (CR 603.4): checked here and again at resolution time.
    //
    // In multiplayer, each player's impending permanents tick down only on THEIR
    // own end step, not on other players' end steps (CR 702.176a: "your end step").
    let active = state.turn.active_player;
    let impending_permanents: Vec<ObjectId> = state
        .objects
        .values()
        .filter(|obj| {
            obj.zone == ZoneId::Battlefield
                && obj.controller == active
                && obj.cast_alt_cost == Some(AltCostKind::Impending)
                && obj.counters.get(&CounterType::Time).copied().unwrap_or(0) > 0
        })
        .map(|obj| obj.id)
        .collect();

    for obj_id in impending_permanents {
        state.pending_triggers.push_back(PendingTrigger {
            source: obj_id,
            ability_index: 0, // unused for impending counter triggers
            controller: active,
            kind: PendingTriggerKind::ImpendingCounter,
            triggering_event: None,
            entering_object_id: None,
            targeting_stack_id: None,
            triggering_player: None,
            exalted_attacker_id: None,
            defending_player_id: None,
            madness_exiled_card: None,
            madness_cost: None,
            miracle_revealed_card: None,
            miracle_cost: None,
            modular_counter_count: None,
            evolve_entering_creature: None,
            suspend_card_id: None,
            hideaway_count: None,
            partner_with_name: None,
            ingest_target_player: None,
            flanking_blocker_id: None,
            rampage_n: None,
            provoke_target_creature: None,
            renown_n: None,
            poisonous_n: None,
            poisonous_target_player: None,
            enlist_enlisted_creature: None,
            encore_activator: None,
            echo_cost: None,
            cumulative_upkeep_cost: None,
            recover_cost: None,
            recover_card: None,
            graft_entering_creature: None,
            backup_abilities: None,
            backup_n: None,
            champion_filter: None,
            champion_exiled_card: None,
            soulbond_pair_target: None,
            squad_count: None,
            gift_opponent: None,
            cipher_encoded_card_id: None,
            cipher_encoded_object_id: None,
            haunt_source_object_id: None,
            haunt_source_card_id: None,
        });
    }

    // Fire AbilityDefinition::Triggered abilities with AtBeginningOfYourEndStep (for active
    // player's permanents) or AtBeginningOfEachEndStep (for all players' permanents).
    //
    // Mirrors the carddef_upkeep_triggers sweep added in MR-B9-01. Catches all CardDef-defined
    // end-step triggers (e.g. Jadar's zombie token creation, future end-step triggers).
    //
    // CR 603.4: Intervening-if conditions are checked at resolution via the Normal trigger path.
    let carddef_end_step_triggers: Vec<(ObjectId, PlayerId, Vec<usize>)> = {
        let registry = &state.card_registry;
        state
            .objects
            .values()
            .filter(|obj| obj.zone == ZoneId::Battlefield && !obj.status.phased_out)
            .filter_map(|obj| {
                let card_id = obj.card_id.as_ref()?;
                let def = registry.get(card_id.clone())?;
                let controller = obj.controller;
                let indices: Vec<usize> = def
                    .abilities
                    .iter()
                    .enumerate()
                    .filter_map(|(idx, abil)| {
                        let AbilityDefinition::Triggered {
                            trigger_condition, ..
                        } = abil
                        else {
                            return None;
                        };
                        let fires = matches!(
                            trigger_condition,
                            TriggerCondition::AtBeginningOfYourEndStep
                        ) && controller == active;
                        fires.then_some(idx)
                    })
                    .collect();
                if indices.is_empty() {
                    None
                } else {
                    Some((obj.id, controller, indices))
                }
            })
            .collect()
    };

    for (obj_id, controller, indices) in carddef_end_step_triggers {
        for ability_index in indices {
            state.pending_triggers.push_back(PendingTrigger {
                source: obj_id,
                ability_index,
                controller,
                kind: PendingTriggerKind::Normal,
                triggering_event: None,
                entering_object_id: None,
                targeting_stack_id: None,
                triggering_player: None,
                exalted_attacker_id: None,
                defending_player_id: None,
                madness_exiled_card: None,
                madness_cost: None,
                miracle_revealed_card: None,
                miracle_cost: None,
                modular_counter_count: None,
                evolve_entering_creature: None,
                suspend_card_id: None,
                hideaway_count: None,
                partner_with_name: None,
                ingest_target_player: None,
                flanking_blocker_id: None,
                rampage_n: None,
                provoke_target_creature: None,
                renown_n: None,
                poisonous_n: None,
                poisonous_target_player: None,
                enlist_enlisted_creature: None,
                encore_activator: None,
                echo_cost: None,
                cumulative_upkeep_cost: None,
                recover_cost: None,
                recover_card: None,
                graft_entering_creature: None,
                backup_abilities: None,
                backup_n: None,
                champion_filter: None,
                champion_exiled_card: None,
                soulbond_pair_target: None,
                squad_count: None,
                gift_opponent: None,
                cipher_encoded_card_id: None,
                cipher_encoded_object_id: None,
                haunt_source_object_id: None,
                haunt_source_card_id: None,
            });
        }
    }

    Vec::new() // No direct events; the triggers will be flushed by enter_step
}

/// CR 502.2: "Second, the active player's phased-out permanents phase in and
/// the active player determines which permanents they control will phase out
/// [...] Then the active player untaps all tapped permanents they control."
///
/// Also clears summoning sickness (CR 302.6) for all permanents the active player
/// controls — they have now been under that player's control since the beginning
/// of their most recent turn.
pub fn untap_active_player_permanents(state: &mut GameState) -> Vec<GameEvent> {
    let active = state.turn.active_player;
    let mut events = Vec::new();

    // CR 730.2: As the second part of the untap step, check if the day/night designation
    // should change based on the previous turn's active player's spell count.
    // CR 730.2c: If it's neither day nor night, this check doesn't happen.
    let day_night_events = check_day_night_transition(state);
    events.extend(day_night_events);

    // CR 502.1 / CR 702.26a: Phase-in and phase-out happen SIMULTANEOUSLY.
    // We must snapshot BOTH sets before mutating anything, so that a creature
    // that phases in does NOT also appear in the phase-out set (because it was
    // phased-out when the snapshot was taken).
    //
    // Step 1: Snapshot the phase-IN set (currently phased-out, controller = active,
    // not indirect). These objects were phased out last turn.
    let phase_in_ids: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(_, obj)| {
            obj.status.phased_out
                && obj.phased_out_controller == Some(active)
                && !obj.phased_out_indirectly
        })
        .map(|(id, _)| *id)
        .collect();

    // Step 2: Snapshot the phase-OUT set (currently phased-IN, on battlefield,
    // controller = active, has Phasing keyword). These objects will phase out now.
    // Because we snapshot BEFORE phase-in mutations, objects in phase_in_ids are
    // still phased-out and will NOT appear in this set (CR 502.1 simultaneous rule).
    let phase_out_direct: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(_, obj)| {
            obj.zone == ZoneId::Battlefield && obj.controller == active && !obj.status.phased_out
        })
        .map(|(id, _)| *id)
        .collect::<Vec<_>>()
        .into_iter()
        .filter(|id| {
            super::layers::calculate_characteristics(state, *id)
                .map(|chars| chars.keywords.contains(&KeywordAbility::Phasing))
                .unwrap_or(false)
        })
        .collect();

    // Step 3: Apply phase-IN mutations (using the snapshot taken above).
    // CR 702.26d: Phasing in is NOT a zone change -- no ETB triggers fire.
    if !phase_in_ids.is_empty() {
        // Collect indirectly-phased attachments of each phasing-in host.
        let mut all_phased_in: Vec<ObjectId> = Vec::new();
        for host_id in &phase_in_ids {
            // Collect attached objects that phased out indirectly (CR 702.26g).
            // Find all objects where phased_out_indirectly == true and
            // attached_to == Some(host_id).
            let indirect_ids: Vec<ObjectId> = state
                .objects
                .iter()
                .filter(|(_, obj)| {
                    obj.status.phased_out
                        && obj.phased_out_indirectly
                        && obj.attached_to == Some(*host_id)
                })
                .map(|(id, _)| *id)
                .collect();
            for indirect_id in &indirect_ids {
                if let Some(obj) = state.objects.get_mut(indirect_id) {
                    obj.status.phased_out = false;
                    obj.phased_out_indirectly = false;
                    obj.phased_out_controller = None;
                }
                all_phased_in.push(*indirect_id);
            }
            // Phase in the host itself.
            if let Some(obj) = state.objects.get_mut(host_id) {
                obj.status.phased_out = false;
                obj.phased_out_controller = None;
            }
            all_phased_in.push(*host_id);
        }
        events.push(GameEvent::PermanentsPhasedIn {
            player: active,
            objects: all_phased_in,
        });
    }

    // Step 4: Apply phase-OUT mutations (using the snapshot taken above).
    // Collect IDs that will be forced to phase out indirectly (CR 702.26h):
    // any attachment that is in both phase_out_direct AND is an attachment of
    // another phasing-out host must phase out INDIRECTLY, not directly.
    let force_indirect: Vec<ObjectId> = {
        let mut fi = Vec::new();
        for host_id in &phase_out_direct {
            let attachments: Vec<ObjectId> = state
                .objects
                .get(host_id)
                .map(|obj| obj.attachments.iter().copied().collect::<Vec<_>>())
                .unwrap_or_default();
            for att_id in &attachments {
                // CR 702.26h: if attachment is also in phase_out_direct (has its own
                // Phasing keyword), it phases out INDIRECTLY (with its host), not directly.
                if phase_out_direct.contains(att_id) {
                    fi.push(*att_id);
                }
            }
        }
        fi
    };

    if !phase_out_direct.is_empty() {
        let mut all_phased_out: Vec<ObjectId> = Vec::new();
        for host_id in &phase_out_direct {
            // CR 702.26h: if this object is forced-indirect (it's an attachment of
            // another phasing-out host), skip it here — it will be processed indirectly.
            if force_indirect.contains(host_id) {
                continue;
            }
            // CR 702.26g: Phase out attached Auras/Equipment/Fortifications indirectly.
            let attachments: Vec<ObjectId> = state
                .objects
                .get(host_id)
                .map(|obj| obj.attachments.iter().copied().collect::<Vec<_>>())
                .unwrap_or_default();
            for att_id in &attachments {
                if let Some(att_obj) = state.objects.get_mut(att_id) {
                    if !att_obj.status.phased_out {
                        att_obj.status.phased_out = true;
                        // CR 702.26h: whether attachment has its own Phasing keyword or
                        // not, if it is phasing out because its host is phasing out,
                        // it phases out INDIRECTLY.
                        att_obj.phased_out_indirectly = true;
                        att_obj.phased_out_controller = Some(active);
                        all_phased_out.push(*att_id);
                    }
                }
            }
            // Phase out the host itself (directly).
            if let Some(obj) = state.objects.get_mut(host_id) {
                obj.status.phased_out = true;
                obj.phased_out_controller = Some(active);
                // phased_out_indirectly remains false (this is a direct phase-out).
            }
            all_phased_out.push(*host_id);
        }
        if !all_phased_out.is_empty() {
            events.push(GameEvent::PermanentsPhasedOut {
                player: active,
                objects: all_phased_out,
            });
        }
    }

    // CR 502.2: Collect object IDs on the battlefield controlled by the active player.
    // Exclude phased-out permanents (CR 702.26b: treated as if they don't exist).
    let ids_on_battlefield: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(_, obj)| {
            obj.controller == active && obj.zone == ZoneId::Battlefield && !obj.status.phased_out
        })
        .map(|(id, _)| *id)
        .collect();

    let mut untapped = Vec::new();
    for id in &ids_on_battlefield {
        if let Some(obj) = state.objects.get_mut(id) {
            // CR 302.6: Clear summoning sickness for permanents the player now controls.
            obj.has_summoning_sickness = false;
            // CR 701.15a: Goad expires at the start of the goaded creature's controller's
            // next turn (the untap step). Clear the goaded_by list now.
            if !obj.goaded_by.is_empty() {
                obj.goaded_by = im::Vector::new();
            }
            // CR 502.2: Untap tapped permanents.
            if obj.status.tapped {
                obj.status.tapped = false;
                untapped.push(*id);
            }
        }
    }

    if !untapped.is_empty() {
        events.push(GameEvent::PermanentsUntapped {
            player: active,
            objects: untapped,
        });
    }

    events
}

/// CR 504.1: "First, the active player draws a card."
/// CR 103.8a: In a two-player game, the player who plays first skips their first draw.
/// CR 103.8c: In all other multiplayer games, no player skips the draw step of their first turn.
fn draw_for_turn(state: &mut GameState) -> Result<Vec<GameEvent>, GameStateError> {
    let active = state.turn.active_player;

    // CR 103.8a: only in two-player games does the first player skip their first draw.
    // CR 103.8c: in multiplayer (3+), nobody skips.
    if state.turn.is_first_turn_of_game && state.players.len() <= 2 {
        return Ok(Vec::new());
    }

    draw_card(state, active)
}

/// Draw a card for the given player: move top of library to hand.
/// Returns `PlayerLost` event if library is empty (CR 104.3b).
pub fn draw_card(
    state: &mut GameState,
    player: PlayerId,
) -> Result<Vec<GameEvent>, GameStateError> {
    // MR-M2-04: Eliminated or conceded players cannot draw cards.
    if let Some(p) = state.players.get(&player) {
        if p.has_lost || p.has_conceded {
            return Ok(vec![]);
        }
    }

    // CR 614.11: Check WouldDraw replacement effects before performing the draw.
    // Shared logic lives in `replacement::check_would_draw_replacement` (MR-M8-07).
    // CR 702.52: Also checks for dredge-eligible cards in the graveyard.
    {
        use crate::rules::replacement::{self, DrawAction};
        match replacement::check_would_draw_replacement(state, player) {
            DrawAction::Proceed => {}
            DrawAction::Skip(event) => return Ok(vec![event]),
            DrawAction::NeedsChoice(event) => {
                // CR 616.1: Multiple WouldDraw replacements apply — defer the draw.
                return Ok(vec![event]);
            }
            DrawAction::DredgeAvailable(event) => {
                // CR 702.52: Dredge options available — pause for player choice.
                return Ok(vec![event]);
            }
        }
    }

    let library_zone = ZoneId::Library(player);
    let library = state.zone(&library_zone)?;

    let top_id = match library.top() {
        Some(id) => id,
        None => {
            // Library empty — player loses (CR 104.3b)
            if let Some(p) = state.players.get_mut(&player) {
                p.has_lost = true;
            }
            return Ok(vec![GameEvent::PlayerLost {
                player,
                reason: LossReason::LibraryEmpty,
            }]);
        }
    };

    let hand_zone = ZoneId::Hand(player);
    let (new_id, _old_obj) = state.move_object_to_zone(top_id, hand_zone)?;

    // Mark that this player has drawn for the turn and increment draw counter.
    if let Some(p) = state.players.get_mut(&player) {
        p.has_drawn_for_turn = true;
        // CR 121.1: track draws-per-turn for Sylvan Library and similar effects (CC#33).
        p.cards_drawn_this_turn += 1;
    }

    let mut events = vec![GameEvent::CardDrawn {
        player,
        new_object_id: new_id,
    }];

    // CR 702.94a: Check if the just-drawn card has miracle and is the first draw.
    // If so, emit MiracleRevealChoiceRequired so the player can choose to reveal.
    if let Some(miracle_event) = super::miracle::check_miracle_eligible(state, player, new_id) {
        events.push(miracle_event);
    }

    Ok(events)
}

/// CR 514.1: "First, if the active player's hand contains more cards than their
/// maximum hand size [...] that player discards enough cards to reduce the hand
/// size to that number."
///
/// Then CR 514.2: "remove all damage from permanents and end 'until end of turn'
/// and 'this turn' effects."
///
/// M2: auto-discards from end of hand (no player choice). M3+ adds choice.
pub fn cleanup_actions(state: &mut GameState) -> Vec<GameEvent> {
    let active = state.turn.active_player;
    let mut events = Vec::new();

    // CR 402.2: Recompute no_max_hand_size from the battlefield. A player has
    // no maximum hand size if they control a permanent with KeywordAbility::NoMaxHandSize
    // (e.g. Thought Vessel, Reliquary Tower).
    let has_no_max = state.objects.values().any(|obj| {
        obj.zone == ZoneId::Battlefield
            && obj.controller == active
            && obj
                .characteristics
                .keywords
                .contains(&crate::state::types::KeywordAbility::NoMaxHandSize)
    });
    if let Some(ps) = state.players.get_mut(&active) {
        ps.no_max_hand_size = has_no_max;
    }

    // Discard to hand size (CR 514.1)
    // Skip entirely if the player has no maximum hand size.
    // MR-M2-09: active player must always be in the players map; assert in debug.
    debug_assert!(
        state.players.contains_key(&active),
        "cleanup_actions: active player {:?} not in players map",
        active
    );
    let no_max = state
        .players
        .get(&active)
        .map(|p| p.no_max_hand_size)
        .unwrap_or(false);
    let max_hand_size = state
        .players
        .get(&active)
        .map(|p| p.max_hand_size)
        .unwrap_or(7);
    let hand_zone = ZoneId::Hand(active);
    let graveyard_zone = ZoneId::Graveyard(active);

    loop {
        if no_max {
            break;
        }
        let hand_size = state.zone(&hand_zone).map(|z| z.len()).unwrap_or(0);
        if hand_size <= max_hand_size {
            break;
        }
        // Pick the last object in the hand (arbitrary in M2 — hand is unordered)
        let obj_ids = state
            .zone(&hand_zone)
            .map(|z| z.object_ids())
            .unwrap_or_default();
        if let Some(&discard_id) = obj_ids.last() {
            // MR-M2-06: Use the old hand ObjectId, not the new graveyard ID.
            // `discard_id` identifies the card while it was in hand; callers
            // (triggers, UI) correlate by the hand identity, not the new zone ID.

            // CR 702.35a: If the discarded card has Madness, exile it instead of graveyard.
            let cleanup_card_id_opt = state
                .objects
                .get(&discard_id)
                .and_then(|o| o.card_id.clone());
            let has_madness = state
                .objects
                .get(&discard_id)
                .map(|obj| {
                    obj.characteristics
                        .keywords
                        .contains(&KeywordAbility::Madness)
                })
                .unwrap_or(false);

            let destination = if has_madness {
                ZoneId::Exile
            } else {
                graveyard_zone
            };

            if let Ok((new_id, _)) = state.move_object_to_zone(discard_id, destination) {
                events.push(GameEvent::DiscardedToHandSize {
                    player: active,
                    object_id: discard_id,
                    zone_from: hand_zone,
                    zone_to: destination,
                });

                // CR 702.35a: Queue the madness trigger via pending_triggers so that
                // flush_pending_triggers properly signals priority granting in cleanup.
                if has_madness {
                    let madness_cost = cleanup_card_id_opt.as_ref().and_then(|cid| {
                        state.card_registry.get(cid.clone()).and_then(|def| {
                            def.abilities.iter().find_map(|a| {
                                if let AbilityDefinition::Madness { cost } = a {
                                    Some(cost.clone())
                                } else {
                                    None
                                }
                            })
                        })
                    });
                    state.pending_triggers.push_back(PendingTrigger {
                        source: new_id,
                        ability_index: 0,
                        controller: active,
                        kind: PendingTriggerKind::Madness,
                        triggering_event: None,
                        entering_object_id: None,
                        targeting_stack_id: None,
                        triggering_player: None,
                        exalted_attacker_id: None,
                        defending_player_id: None,
                        madness_exiled_card: Some(new_id),
                        madness_cost,
                        miracle_revealed_card: None,
                        miracle_cost: None,
                        modular_counter_count: None,
                        evolve_entering_creature: None,
                        suspend_card_id: None,
                        hideaway_count: None,
                        partner_with_name: None,
                        ingest_target_player: None,
                        flanking_blocker_id: None,
                        rampage_n: None,
                        provoke_target_creature: None,
                        renown_n: None,
                        poisonous_n: None,
                        poisonous_target_player: None,
                        enlist_enlisted_creature: None,
                        encore_activator: None,
                        echo_cost: None,
                        cumulative_upkeep_cost: None,
                        recover_cost: None,
                        recover_card: None,
                        graft_entering_creature: None,
                        backup_abilities: None,
                        backup_n: None,
                        champion_filter: None,
                        champion_exiled_card: None,
                        soulbond_pair_target: None,
                        squad_count: None,
                        gift_opponent: None,
                        cipher_encoded_card_id: None,
                        cipher_encoded_object_id: None,
                        haunt_source_object_id: None,
                        haunt_source_card_id: None,
                    });
                }
            }
        } else {
            break;
        }
    }

    // Clear damage from all permanents (CR 514.1)
    clear_damage(state);
    events.push(GameEvent::DamageCleared);

    // CR 702.171b: Clear saddled designation from all battlefield permanents.
    // "Stays saddled until the end of the turn." Designation expires at cleanup.
    {
        let saddled_ids: Vec<crate::state::ObjectId> = state
            .objects
            .iter()
            .filter(|(_, obj)| {
                obj.zone == crate::state::zone::ZoneId::Battlefield && obj.is_saddled
            })
            .map(|(id, _)| *id)
            .collect();
        for id in saddled_ids {
            if let Some(obj) = state.objects.get_mut(&id) {
                obj.is_saddled = false;
            }
        }
    }

    // Remove "until end of turn" continuous effects (CR 514.2).
    super::layers::expire_end_of_turn_effects(state);

    // Empty mana pools
    empty_all_mana_pools(state);
    events.push(GameEvent::ManaPoolsEmptied);

    events.push(GameEvent::CleanupPerformed);
    events
}

/// CR 500.4: Empty all players' mana pools at step transitions.
pub fn empty_all_mana_pools(state: &mut GameState) -> Vec<GameEvent> {
    let player_ids: Vec<PlayerId> = state
        .players
        .iter()
        .filter(|(_, p)| !p.mana_pool.is_empty())
        .map(|(id, _)| *id)
        .collect();

    if player_ids.is_empty() {
        return Vec::new();
    }

    for id in &player_ids {
        if let Some(p) = state.players.get_mut(id) {
            p.mana_pool.empty();
        }
    }
    vec![GameEvent::ManaPoolsEmptied]
}

/// Set `damage_marked = 0` and clear `deathtouch_damage` on all battlefield permanents (CR 514.1).
pub fn clear_damage(state: &mut GameState) {
    let ids: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(_, obj)| {
            obj.zone == ZoneId::Battlefield && (obj.damage_marked > 0 || obj.deathtouch_damage)
        })
        .map(|(id, _)| *id)
        .collect();

    for id in &ids {
        if let Some(obj) = state.objects.get_mut(id) {
            obj.damage_marked = 0;
            obj.deathtouch_damage = false;
        }
    }
}

/// Reset per-turn state for a player starting their turn.
pub fn reset_turn_state(state: &mut GameState, player: PlayerId) {
    // CR 730.2a/b: Before resetting spells_cast_this_turn, save it as the
    // "previous turn's spell count" for day/night transition checking.
    // This is checked at the NEXT player's untap step (CR 730.2).
    let prev_spells = state
        .players
        .get(&player)
        .map(|p| p.spells_cast_this_turn)
        .unwrap_or(0);
    state.previous_turn_spells_cast = prev_spells;

    if let Some(p) = state.players.get_mut(&player) {
        p.land_plays_remaining = 1;
        p.has_drawn_for_turn = false;
        // CR 702.40a: per-turn spell cast count resets at the start of each turn.
        // Used by storm to count copies.
        p.spells_cast_this_turn = 0;
    }

    // CR 702.94a / CR 121.1: "the first card you've drawn this turn" refers to the
    // current game turn (the active player's turn). Every player's draw counter must
    // reset at each turn boundary so that miracle eligibility is correct in multiplayer.
    // Example: Player B draws on Player C's turn (counter = 1). If only the active player's
    // counter is reset, Player B's counter stays at 1 on Player D's turn, so the second draw
    // on Player D's turn is seen as draw #2 and miracle never triggers. Resetting ALL players'
    // draw counters at each turn boundary fixes this.
    //
    // Note: spells_cast_this_turn is NOT reset for all players because storm counts spells
    // cast during the storm player's own turn only. Draw tracking (miracle, Sylvan Library)
    // is scoped to "this game turn" for any player who draws.
    let player_ids: Vec<PlayerId> = state.players.keys().copied().collect();
    for pid in player_ids {
        if let Some(p) = state.players.get_mut(&pid) {
            // CR 121.1: per-turn draw count resets at the start of each turn for all players.
            p.cards_drawn_this_turn = 0;
            // CR 702.137a: per-turn life-loss counter resets at the start of each
            // turn for all players (Spectacle eligibility is scoped to the current game turn).
            p.life_lost_this_turn = 0;
            // CR 702.54a: per-turn damage-received counter resets at the start of each
            // turn for all players (Bloodthirst eligibility is scoped to the current game turn).
            p.damage_received_this_turn = 0;
        }
    }

    // CR 702.69a: Global permanents-to-graveyard count resets at the start of each turn.
    // Unlike spells_cast_this_turn (per-player) or life_lost_this_turn (per-player),
    // this is a shared global counter on GameState itself.
    state.permanents_put_into_graveyard_this_turn = 0;

    // CR 702.57b: Forecast once-per-turn tracking resets at the start of each turn.
    // Each card's forecast ability may be activated once per turn.
    state.forecast_used_this_turn = im::OrdSet::new();
}

// ---------------------------------------------------------------------------
// Day/Night enforcement (CR 730 + CR 702.145 Daybound/Nightbound)
// ---------------------------------------------------------------------------

/// CR 730.2: Check whether the game's day/night designation should change at the
/// start of the untap step.
///
/// - CR 730.2a: If it's day and the previous turn's active player cast no spells → becomes night.
/// - CR 730.2b: If it's night and the previous turn's active player cast two or more spells → becomes day.
/// - CR 730.2c: If it's neither, skip.
///
/// After any transition, applies daybound/nightbound enforcement (CR 702.145c/f).
fn check_day_night_transition(state: &mut GameState) -> Vec<GameEvent> {
    use crate::rules::events::GameEvent;
    use crate::state::DayNight;

    let mut events = Vec::new();

    let transition = match state.day_night {
        Some(DayNight::Day) if state.previous_turn_spells_cast == 0 => {
            // CR 730.2a: Becomes night.
            Some(DayNight::Night)
        }
        Some(DayNight::Night) if state.previous_turn_spells_cast >= 2 => {
            // CR 730.2b: Becomes day.
            Some(DayNight::Day)
        }
        _ => None, // CR 730.2c or no change
    };

    if let Some(new_designation) = transition {
        state.day_night = Some(new_designation);
        events.push(GameEvent::DayNightChanged {
            now: new_designation,
        });

        // After changing day/night, enforce daybound/nightbound transforms.
        let transform_events = enforce_daybound_nightbound(state);
        events.extend(transform_events);
    }

    events
}

/// CR 702.145c/f: Enforce daybound/nightbound immediate transforms.
///
/// Called whenever the day/night designation changes or when a daybound/nightbound
/// permanent enters the battlefield.
///
/// - If it's night and a permanent has daybound with front face up → transform it.
/// - If it's day and a permanent has nightbound with back face up → transform it.
/// - If it's neither and a permanent has daybound → establish day (CR 702.145d).
/// - If it's neither and a permanent has nightbound (and no daybound exists) → establish night (CR 702.145g).
///
/// CR 702.145b/c: "happens immediately and isn't a state-based action."
pub fn enforce_daybound_nightbound(state: &mut GameState) -> Vec<GameEvent> {
    use crate::rules::events::GameEvent;
    use crate::state::types::KeywordAbility;
    use crate::state::zone::ZoneId;
    use crate::state::DayNight;

    let mut events = Vec::new();

    // First, check if we need to establish day/night for the first time.
    if state.day_night.is_none() {
        let has_daybound = state.objects.values().any(|obj| {
            obj.zone == ZoneId::Battlefield
                && super::layers::calculate_characteristics(state, obj.id)
                    .map(|c| c.keywords.contains(&KeywordAbility::Daybound))
                    .unwrap_or(false)
        });
        let has_nightbound = state.objects.values().any(|obj| {
            obj.zone == ZoneId::Battlefield
                && super::layers::calculate_characteristics(state, obj.id)
                    .map(|c| c.keywords.contains(&KeywordAbility::Nightbound))
                    .unwrap_or(false)
        });

        if has_daybound {
            // CR 702.145d: Daybound causes it to become day.
            state.day_night = Some(DayNight::Day);
            events.push(GameEvent::DayNightChanged { now: DayNight::Day });
        } else if has_nightbound {
            // CR 702.145g: Nightbound causes it to become night (if no daybound exists).
            state.day_night = Some(DayNight::Night);
            events.push(GameEvent::DayNightChanged {
                now: DayNight::Night,
            });
        }
    }

    // Collect IDs of permanents that need transforming (to avoid borrow conflicts).
    let ids_to_transform: Vec<crate::state::game_object::ObjectId> = state
        .objects
        .iter()
        .filter_map(|(id, obj)| {
            if obj.zone != ZoneId::Battlefield {
                return None;
            }
            let chars = super::layers::calculate_characteristics(state, *id)?;

            // CR 702.145c: If it's night and the permanent has daybound and is front-face-up.
            if state.day_night == Some(DayNight::Night)
                && chars.keywords.contains(&KeywordAbility::Daybound)
                && !obj.is_transformed
            {
                return Some(*id);
            }

            // CR 702.145f: If it's day and the permanent has nightbound and is back-face-up.
            if state.day_night == Some(DayNight::Day)
                && chars.keywords.contains(&KeywordAbility::Nightbound)
                && obj.is_transformed
            {
                return Some(*id);
            }

            None
        })
        .collect();

    for id in ids_to_transform {
        if let Some(obj) = state.objects.get_mut(&id) {
            let to_back_face = !obj.is_transformed;
            obj.is_transformed = to_back_face;
            obj.last_transform_timestamp = state.timestamp_counter;
            state.timestamp_counter += 1;
            events.push(GameEvent::PermanentTransformed {
                object_id: id,
                to_back_face,
            });
        }
    }

    events
}

// ---------------------------------------------------------------------------
// Combat turn-based actions (M6)
// ---------------------------------------------------------------------------

/// CR 507.1: Initialize combat state at the start of the combat phase.
///
/// Sets up `GameState::combat` so that the combat phase tracking is ready.
/// Called as a turn-based action on entering `BeginningOfCombat`.
fn begin_combat(state: &mut GameState) -> Vec<GameEvent> {
    let active = state.turn.active_player;
    if state.combat.is_none() {
        state.combat = Some(CombatState::new(active));
    }
    Vec::new()
}

/// CR 510: Apply first-strike combat damage (creatures with FirstStrike or DoubleStrike).
///
/// Called as a turn-based action in `Step::FirstStrikeDamage`.
fn first_strike_damage_step(state: &mut GameState) -> Vec<GameEvent> {
    let events = super::combat::apply_combat_damage(state, true);
    if let Some(c) = state.combat.as_mut() {
        c.first_strike_damage_resolved = true;
    }
    events
}

/// CR 510: Apply regular combat damage (creatures without exclusive FirstStrike).
///
/// Called as a turn-based action in `Step::CombatDamage`.
fn combat_damage_step(state: &mut GameState) -> Vec<GameEvent> {
    super::combat::apply_combat_damage(state, false)
}

/// CR 511.1: Clear combat state at the end of the combat phase.
///
/// Called as a turn-based action in `Step::EndOfCombat`.
///
/// CR 702.116a: Before clearing combat state, exile all myriad token copies that
/// were created this combat. These tokens are tagged with `myriad_exile_at_eoc = true`.
/// CR 511.2: "at end of combat" triggers fire as the end of combat step begins,
/// which is modeled here as a turn-based action (no delayed trigger infrastructure
/// needed — the tag on the token is sufficient).
///
/// TODO(M10+): Per CR 702.116a / CR 603.7, the myriad exile is actually a delayed
/// triggered ability created when the myriad trigger resolves, not a turn-based action.
/// As a delayed trigger it would go on the stack at the beginning of the end-of-combat
/// step (CR 511.2), giving players an opportunity to respond (e.g., Stifle to keep the
/// tokens). The current TBA implementation exiles tokens with no interaction window.
/// Refactor to use a proper DelayedTrigger when that infrastructure is expanded (M10+).
fn end_combat(state: &mut GameState) -> Vec<GameEvent> {
    let mut events = Vec::new();

    // CR 702.116a: Exile all myriad tokens. Collect first to avoid borrow issues.
    let myriad_token_ids: Vec<crate::state::game_object::ObjectId> = state
        .objects
        .values()
        .filter(|obj| {
            obj.zone == crate::state::zone::ZoneId::Battlefield
                && obj.is_token
                && obj.myriad_exile_at_eoc
        })
        .map(|obj| obj.id)
        .collect();

    for token_id in myriad_token_ids {
        // Capture controller before moving zone (needed for the exile event).
        let controller = state
            .objects
            .get(&token_id)
            .map(|o| o.controller)
            .unwrap_or(state.turn.active_player);

        if let Ok((new_exile_id, _old)) =
            state.move_object_to_zone(token_id, crate::state::zone::ZoneId::Exile)
        {
            events.push(GameEvent::ObjectExiled {
                player: controller,
                object_id: token_id,
                new_exile_id,
            });
        }
    }

    // CR 702.147a: Sacrifice all creatures that attacked with decayed.
    // Creatures are tagged with `decayed_sacrifice_at_eoc = true` in
    // `handle_declare_attackers` in combat.rs when they attack.
    //
    // Ruling 2021-09-24: "Once a creature with decayed attacks, it will be
    // sacrificed at end of combat, even if it no longer has decayed at that time."
    //
    // CR 701.17a: Sacrifice is NOT destruction — indestructible does not prevent it.
    //
    // TODO(M10+): Per CR 702.147a / CR 603.7, the EOC sacrifice is technically a
    // delayed triggered ability ("sacrifice it at end of combat"). The current TBA
    // implementation sacrifices with no interaction window (can't Stifle the
    // sacrifice). Same caveat as Myriad's EOC exile. Refactor when delayed trigger
    // infrastructure is expanded.
    let decayed_sacrifice_ids: Vec<ObjectId> = state
        .objects
        .values()
        .filter(|obj| {
            obj.zone == crate::state::zone::ZoneId::Battlefield && obj.decayed_sacrifice_at_eoc
        })
        .map(|obj| obj.id)
        .collect();

    for obj_id in decayed_sacrifice_ids {
        let (owner, controller, pre_death_counters) = match state.objects.get(&obj_id) {
            Some(obj) => (obj.owner, obj.controller, obj.counters.clone()),
            None => continue,
        };

        // CR 614: Check replacement effects before moving to graveyard.
        let action = crate::rules::replacement::check_zone_change_replacement(
            state,
            obj_id,
            crate::state::zone::ZoneType::Battlefield,
            crate::state::zone::ZoneType::Graveyard,
            owner,
            &std::collections::HashSet::new(),
        );

        match action {
            crate::rules::replacement::ZoneChangeAction::Redirect {
                to,
                events: repl_events,
                ..
            } => {
                events.extend(repl_events);
                if let Ok((new_id, _old)) = state.move_object_to_zone(obj_id, to) {
                    match to {
                        crate::state::zone::ZoneId::Exile => {
                            events.push(GameEvent::ObjectExiled {
                                player: controller,
                                object_id: obj_id,
                                new_exile_id: new_id,
                            });
                        }
                        crate::state::zone::ZoneId::Command(_) => {
                            // Commander redirected to command zone — no CreatureDied.
                        }
                        _ => {
                            events.push(GameEvent::CreatureDied {
                                object_id: obj_id,
                                new_grave_id: new_id,
                                controller,
                                pre_death_counters,
                            });
                        }
                    }
                }
            }
            crate::rules::replacement::ZoneChangeAction::Proceed => {
                if let Ok((new_id, _old)) =
                    state.move_object_to_zone(obj_id, crate::state::zone::ZoneId::Graveyard(owner))
                {
                    events.push(GameEvent::CreatureDied {
                        object_id: obj_id,
                        new_grave_id: new_id,
                        controller,
                        pre_death_counters,
                    });
                }
            }
            crate::rules::replacement::ZoneChangeAction::ChoiceRequired { .. } => {
                // Multiple replacements — in the absence of full choice infrastructure
                // for TBA context, fall back to Proceed (graveyard).
                if let Ok((new_id, _old)) =
                    state.move_object_to_zone(obj_id, crate::state::zone::ZoneId::Graveyard(owner))
                {
                    events.push(GameEvent::CreatureDied {
                        object_id: obj_id,
                        new_grave_id: new_id,
                        controller,
                        pre_death_counters,
                    });
                }
            }
        }
    }

    state.combat = None;
    events.push(GameEvent::CombatEnded);
    events
}
