//! Turn-based actions: untap, draw, cleanup, mana pool emptying, combat (CR 500-514).

use crate::cards::card_definition::AbilityDefinition;
use crate::state::combat::CombatState;
use crate::state::error::GameStateError;
use crate::state::game_object::ObjectId;
use crate::state::player::PlayerId;
use crate::state::stubs::PendingTrigger;
use crate::state::turn::Step;
use crate::state::types::{CounterType, KeywordAbility};
use crate::state::zone::ZoneId;
use crate::state::GameState;

use super::events::{GameEvent, LossReason};

/// Execute turn-based actions for the current step.
/// Returns events generated by the actions.
pub fn execute_turn_based_actions(state: &mut GameState) -> Result<Vec<GameEvent>, GameStateError> {
    match state.turn.step {
        Step::Untap => Ok(untap_active_player_permanents(state)),
        Step::Upkeep => Ok(upkeep_actions(state)),
        Step::Draw => draw_for_turn(state),
        Step::BeginningOfCombat => Ok(begin_combat(state)),
        Step::FirstStrikeDamage => Ok(first_strike_damage_step(state)),
        Step::CombatDamage => Ok(combat_damage_step(state)),
        Step::EndOfCombat => Ok(end_combat(state)),
        Step::Cleanup => Ok(cleanup_actions(state)),
        Step::End => Ok(end_step_actions(state)),
        _ => Ok(Vec::new()),
    }
}

/// CR 503.1 / CR 702.62a: Upkeep step turn-based actions.
///
/// Queue suspend counter-removal triggers for each suspended card owned by the active
/// player in exile. CR 702.62a (second ability): "At the beginning of your upkeep, if
/// this card is suspended, remove a time counter from it."
///
/// A card is "suspended" (CR 702.62b) if:
/// - It is in the exile zone,
/// - It has the Suspend keyword ability, AND
/// - It has one or more time counters on it.
///
/// These are triggered abilities (not turn-based actions); they use the stack and can be
/// countered (e.g., Stifle prevents a time counter from being removed). In multiplayer,
/// only the ACTIVE player's suspended cards tick down on their own upkeep.
fn upkeep_actions(state: &mut GameState) -> Vec<GameEvent> {
    let active = state.turn.active_player;

    // Collect suspended cards in exile owned by the active player.
    // CR 702.62b: Must have suspend keyword, be in exile, AND have time counters.
    let suspended_cards: Vec<ObjectId> = state
        .objects
        .values()
        .filter(|obj| {
            obj.zone == ZoneId::Exile
                && obj.owner == active
                && obj.is_suspended
                && obj.counters.get(&CounterType::Time).copied().unwrap_or(0) > 0
        })
        .map(|obj| obj.id)
        .collect();

    for card_id in suspended_cards {
        // CR 702.62a: Queue a suspend counter-removal trigger. These go on the stack
        // in APNAP order (all controlled by active player here, so order is FIFO).
        state.pending_triggers.push_back(PendingTrigger {
            source: card_id,
            ability_index: 0,
            controller: active,
            triggering_event: None,
            entering_object_id: None,
            targeting_stack_id: None,
            triggering_player: None,
            exalted_attacker_id: None,
            defending_player_id: None,
            is_evoke_sacrifice: false,
            is_madness_trigger: false,
            madness_exiled_card: None,
            madness_cost: None,
            is_miracle_trigger: false,
            miracle_revealed_card: None,
            miracle_cost: None,
            is_unearth_trigger: false,
            is_exploit_trigger: false,
            is_modular_trigger: false,
            modular_counter_count: None,
            is_evolve_trigger: false,
            evolve_entering_creature: None,
            is_myriad_trigger: false,
            is_suspend_counter_trigger: true,
            is_suspend_cast_trigger: false,
            suspend_card_id: Some(card_id),
            is_hideaway_trigger: false,
            hideaway_count: None,
            is_partner_with_trigger: false,
            partner_with_name: None,
            is_ingest_trigger: false,
            ingest_target_player: None,
            is_flanking_trigger: false,
            flanking_blocker_id: None,
            is_rampage_trigger: false,
            rampage_n: None,
            is_provoke_trigger: false,
            provoke_target_creature: None,
            is_renown_trigger: false,
            renown_n: None,
            is_melee_trigger: false,
            is_poisonous_trigger: false,
            poisonous_n: None,
            poisonous_target_player: None,
            is_enlist_trigger: false,
            enlist_enlisted_creature: None,
        });
    }

    Vec::new() // No direct events; triggers are flushed by enter_step
}

/// CR 702.84a: End step actions -- queue delayed exile triggers for all unearthed permanents.
///
/// "Exile it at the beginning of the next end step."
/// At the beginning of the end step, scan all battlefield permanents with
/// `was_unearthed == true` and queue a `UnearthTrigger` for each one.
///
/// These are delayed triggered abilities created when the unearth ability resolved.
/// They can be countered (e.g., by Stifle); the replacement effect persists independently.
pub fn end_step_actions(state: &mut GameState) -> Vec<GameEvent> {
    // Collect unearthed permanents on the battlefield.
    let unearthed: Vec<(ObjectId, crate::state::player::PlayerId)> = state
        .objects
        .values()
        .filter(|obj| obj.zone == ZoneId::Battlefield && obj.was_unearthed)
        .map(|obj| (obj.id, obj.controller))
        .collect();

    for (obj_id, controller) in unearthed {
        state.pending_triggers.push_back(PendingTrigger {
            source: obj_id,
            ability_index: 0, // unused for unearth triggers
            controller,
            triggering_event: None,
            entering_object_id: None,
            targeting_stack_id: None,
            triggering_player: None,
            exalted_attacker_id: None,
            defending_player_id: None,
            is_evoke_sacrifice: false,
            is_madness_trigger: false,
            madness_exiled_card: None,
            madness_cost: None,
            is_miracle_trigger: false,
            miracle_revealed_card: None,
            miracle_cost: None,
            is_unearth_trigger: true,
            is_exploit_trigger: false,
            is_modular_trigger: false,
            modular_counter_count: None,
            is_evolve_trigger: false,
            evolve_entering_creature: None,
            is_myriad_trigger: false,
            is_suspend_counter_trigger: false,
            is_suspend_cast_trigger: false,
            suspend_card_id: None,
            is_hideaway_trigger: false,
            hideaway_count: None,
            is_partner_with_trigger: false,
            partner_with_name: None,
            is_ingest_trigger: false,
            ingest_target_player: None,
            is_flanking_trigger: false,
            flanking_blocker_id: None,
            is_rampage_trigger: false,
            rampage_n: None,
            is_provoke_trigger: false,
            provoke_target_creature: None,
            is_renown_trigger: false,
            renown_n: None,
            is_melee_trigger: false,
            is_poisonous_trigger: false,
            poisonous_n: None,
            poisonous_target_player: None,
            is_enlist_trigger: false,
            enlist_enlisted_creature: None,
        });
    }

    Vec::new() // No direct events; the triggers will be flushed by enter_step
}

/// CR 502.2: "Second, the active player's phased-out permanents phase in and
/// the active player determines which permanents they control will phase out
/// [...] Then the active player untaps all tapped permanents they control."
///
/// For M2 we skip phasing and just untap.
///
/// Also clears summoning sickness (CR 302.6) for all permanents the active player
/// controls — they have now been under that player's control since the beginning
/// of their most recent turn.
pub fn untap_active_player_permanents(state: &mut GameState) -> Vec<GameEvent> {
    let active = state.turn.active_player;
    let mut untapped = Vec::new();

    // Collect object IDs on the battlefield controlled by the active player.
    let ids_on_battlefield: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(_, obj)| obj.controller == active && obj.zone == ZoneId::Battlefield)
        .map(|(id, _)| *id)
        .collect();

    for id in &ids_on_battlefield {
        if let Some(obj) = state.objects.get_mut(id) {
            // CR 302.6: Clear summoning sickness for permanents the player now controls.
            obj.has_summoning_sickness = false;
            // CR 701.15a: Goad expires at the start of the goaded creature's controller's
            // next turn (the untap step). Clear the goaded_by list now.
            if !obj.goaded_by.is_empty() {
                obj.goaded_by = im::Vector::new();
            }
            // CR 502.2: Untap tapped permanents.
            if obj.status.tapped {
                obj.status.tapped = false;
                untapped.push(*id);
            }
        }
    }

    if untapped.is_empty() {
        Vec::new()
    } else {
        vec![GameEvent::PermanentsUntapped {
            player: active,
            objects: untapped,
        }]
    }
}

/// CR 504.1: "First, the active player draws a card."
/// CR 103.8a: In a two-player game, the player who plays first skips their first draw.
/// CR 103.8c: In all other multiplayer games, no player skips the draw step of their first turn.
fn draw_for_turn(state: &mut GameState) -> Result<Vec<GameEvent>, GameStateError> {
    let active = state.turn.active_player;

    // CR 103.8a: only in two-player games does the first player skip their first draw.
    // CR 103.8c: in multiplayer (3+), nobody skips.
    if state.turn.is_first_turn_of_game && state.players.len() <= 2 {
        return Ok(Vec::new());
    }

    draw_card(state, active)
}

/// Draw a card for the given player: move top of library to hand.
/// Returns `PlayerLost` event if library is empty (CR 104.3b).
pub fn draw_card(
    state: &mut GameState,
    player: PlayerId,
) -> Result<Vec<GameEvent>, GameStateError> {
    // MR-M2-04: Eliminated or conceded players cannot draw cards.
    if let Some(p) = state.players.get(&player) {
        if p.has_lost || p.has_conceded {
            return Ok(vec![]);
        }
    }

    // CR 614.11: Check WouldDraw replacement effects before performing the draw.
    // Shared logic lives in `replacement::check_would_draw_replacement` (MR-M8-07).
    // CR 702.52: Also checks for dredge-eligible cards in the graveyard.
    {
        use crate::rules::replacement::{self, DrawAction};
        match replacement::check_would_draw_replacement(state, player) {
            DrawAction::Proceed => {}
            DrawAction::Skip(event) => return Ok(vec![event]),
            DrawAction::NeedsChoice(event) => {
                // CR 616.1: Multiple WouldDraw replacements apply — defer the draw.
                return Ok(vec![event]);
            }
            DrawAction::DredgeAvailable(event) => {
                // CR 702.52: Dredge options available — pause for player choice.
                return Ok(vec![event]);
            }
        }
    }

    let library_zone = ZoneId::Library(player);
    let library = state.zone(&library_zone)?;

    let top_id = match library.top() {
        Some(id) => id,
        None => {
            // Library empty — player loses (CR 104.3b)
            if let Some(p) = state.players.get_mut(&player) {
                p.has_lost = true;
            }
            return Ok(vec![GameEvent::PlayerLost {
                player,
                reason: LossReason::LibraryEmpty,
            }]);
        }
    };

    let hand_zone = ZoneId::Hand(player);
    let (new_id, _old_obj) = state.move_object_to_zone(top_id, hand_zone)?;

    // Mark that this player has drawn for the turn and increment draw counter.
    if let Some(p) = state.players.get_mut(&player) {
        p.has_drawn_for_turn = true;
        // CR 121.1: track draws-per-turn for Sylvan Library and similar effects (CC#33).
        p.cards_drawn_this_turn += 1;
    }

    let mut events = vec![GameEvent::CardDrawn {
        player,
        new_object_id: new_id,
    }];

    // CR 702.94a: Check if the just-drawn card has miracle and is the first draw.
    // If so, emit MiracleRevealChoiceRequired so the player can choose to reveal.
    if let Some(miracle_event) = super::miracle::check_miracle_eligible(state, player, new_id) {
        events.push(miracle_event);
    }

    Ok(events)
}

/// CR 514.1: "First, if the active player's hand contains more cards than their
/// maximum hand size [...] that player discards enough cards to reduce the hand
/// size to that number."
///
/// Then CR 514.2: "remove all damage from permanents and end 'until end of turn'
/// and 'this turn' effects."
///
/// M2: auto-discards from end of hand (no player choice). M3+ adds choice.
pub fn cleanup_actions(state: &mut GameState) -> Vec<GameEvent> {
    let active = state.turn.active_player;
    let mut events = Vec::new();

    // CR 402.2: Recompute no_max_hand_size from the battlefield. A player has
    // no maximum hand size if they control a permanent with KeywordAbility::NoMaxHandSize
    // (e.g. Thought Vessel, Reliquary Tower).
    let has_no_max = state.objects.values().any(|obj| {
        obj.zone == ZoneId::Battlefield
            && obj.controller == active
            && obj
                .characteristics
                .keywords
                .contains(&crate::state::types::KeywordAbility::NoMaxHandSize)
    });
    if let Some(ps) = state.players.get_mut(&active) {
        ps.no_max_hand_size = has_no_max;
    }

    // Discard to hand size (CR 514.1)
    // Skip entirely if the player has no maximum hand size.
    let no_max = state
        .players
        .get(&active)
        .map(|p| p.no_max_hand_size)
        .unwrap_or(false);
    let max_hand_size = state
        .players
        .get(&active)
        .map(|p| p.max_hand_size)
        .unwrap_or(7);
    let hand_zone = ZoneId::Hand(active);
    let graveyard_zone = ZoneId::Graveyard(active);

    loop {
        if no_max {
            break;
        }
        let hand_size = state.zone(&hand_zone).map(|z| z.len()).unwrap_or(0);
        if hand_size <= max_hand_size {
            break;
        }
        // Pick the last object in the hand (arbitrary in M2 — hand is unordered)
        let obj_ids = state
            .zone(&hand_zone)
            .map(|z| z.object_ids())
            .unwrap_or_default();
        if let Some(&discard_id) = obj_ids.last() {
            // MR-M2-06: Use the old hand ObjectId, not the new graveyard ID.
            // `discard_id` identifies the card while it was in hand; callers
            // (triggers, UI) correlate by the hand identity, not the new zone ID.

            // CR 702.35a: If the discarded card has Madness, exile it instead of graveyard.
            let cleanup_card_id_opt = state
                .objects
                .get(&discard_id)
                .and_then(|o| o.card_id.clone());
            let has_madness = state
                .objects
                .get(&discard_id)
                .map(|obj| {
                    obj.characteristics
                        .keywords
                        .contains(&KeywordAbility::Madness)
                })
                .unwrap_or(false);

            let destination = if has_madness {
                ZoneId::Exile
            } else {
                graveyard_zone
            };

            if let Ok((new_id, _)) = state.move_object_to_zone(discard_id, destination) {
                events.push(GameEvent::DiscardedToHandSize {
                    player: active,
                    object_id: discard_id,
                    zone_from: hand_zone,
                    zone_to: destination,
                });

                // CR 702.35a: Queue the madness trigger via pending_triggers so that
                // flush_pending_triggers properly signals priority granting in cleanup.
                if has_madness {
                    let madness_cost = cleanup_card_id_opt.as_ref().and_then(|cid| {
                        state.card_registry.get(cid.clone()).and_then(|def| {
                            def.abilities.iter().find_map(|a| {
                                if let AbilityDefinition::Madness { cost } = a {
                                    Some(cost.clone())
                                } else {
                                    None
                                }
                            })
                        })
                    });
                    state.pending_triggers.push_back(PendingTrigger {
                        source: new_id,
                        ability_index: 0,
                        controller: active,
                        triggering_event: None,
                        entering_object_id: None,
                        targeting_stack_id: None,
                        triggering_player: None,
                        exalted_attacker_id: None,
                        defending_player_id: None,
                        is_evoke_sacrifice: false,
                        is_madness_trigger: true,
                        madness_exiled_card: Some(new_id),
                        madness_cost,
                        is_miracle_trigger: false,
                        miracle_revealed_card: None,
                        miracle_cost: None,
                        is_unearth_trigger: false,
                        is_exploit_trigger: false,
                        is_modular_trigger: false,
                        modular_counter_count: None,
                        is_evolve_trigger: false,
                        evolve_entering_creature: None,
                        is_myriad_trigger: false,
                        is_suspend_counter_trigger: false,
                        is_suspend_cast_trigger: false,
                        suspend_card_id: None,
                        is_hideaway_trigger: false,
                        hideaway_count: None,
                        is_partner_with_trigger: false,
                        partner_with_name: None,
                        is_ingest_trigger: false,
                        ingest_target_player: None,
                        is_flanking_trigger: false,
                        flanking_blocker_id: None,
                        is_rampage_trigger: false,
                        rampage_n: None,
                        is_provoke_trigger: false,
                        provoke_target_creature: None,
                        is_renown_trigger: false,
                        renown_n: None,
                        is_melee_trigger: false,
                        is_poisonous_trigger: false,
                        poisonous_n: None,
                        poisonous_target_player: None,
                        is_enlist_trigger: false,
                        enlist_enlisted_creature: None,
                    });
                }
            }
        } else {
            break;
        }
    }

    // Clear damage from all permanents (CR 514.1)
    clear_damage(state);
    events.push(GameEvent::DamageCleared);

    // Remove "until end of turn" continuous effects (CR 514.2).
    super::layers::expire_end_of_turn_effects(state);

    // Empty mana pools
    empty_all_mana_pools(state);
    events.push(GameEvent::ManaPoolsEmptied);

    events.push(GameEvent::CleanupPerformed);
    events
}

/// CR 500.4: Empty all players' mana pools at step transitions.
pub fn empty_all_mana_pools(state: &mut GameState) -> Vec<GameEvent> {
    let player_ids: Vec<PlayerId> = state
        .players
        .iter()
        .filter(|(_, p)| !p.mana_pool.is_empty())
        .map(|(id, _)| *id)
        .collect();

    if player_ids.is_empty() {
        return Vec::new();
    }

    for id in &player_ids {
        if let Some(p) = state.players.get_mut(id) {
            p.mana_pool.empty();
        }
    }
    vec![GameEvent::ManaPoolsEmptied]
}

/// Set `damage_marked = 0` and clear `deathtouch_damage` on all battlefield permanents (CR 514.1).
pub fn clear_damage(state: &mut GameState) {
    let ids: Vec<ObjectId> = state
        .objects
        .iter()
        .filter(|(_, obj)| {
            obj.zone == ZoneId::Battlefield && (obj.damage_marked > 0 || obj.deathtouch_damage)
        })
        .map(|(id, _)| *id)
        .collect();

    for id in &ids {
        if let Some(obj) = state.objects.get_mut(id) {
            obj.damage_marked = 0;
            obj.deathtouch_damage = false;
        }
    }
}

/// Reset per-turn state for a player starting their turn.
pub fn reset_turn_state(state: &mut GameState, player: PlayerId) {
    if let Some(p) = state.players.get_mut(&player) {
        p.land_plays_remaining = 1;
        p.has_drawn_for_turn = false;
        // CR 702.40a: per-turn spell cast count resets at the start of each turn.
        // Used by storm to count copies.
        p.spells_cast_this_turn = 0;
    }

    // CR 702.94a / CR 121.1: "the first card you've drawn this turn" refers to the
    // current game turn (the active player's turn). Every player's draw counter must
    // reset at each turn boundary so that miracle eligibility is correct in multiplayer.
    // Example: Player B draws on Player C's turn (counter = 1). If only the active player's
    // counter is reset, Player B's counter stays at 1 on Player D's turn, so the second draw
    // on Player D's turn is seen as draw #2 and miracle never triggers. Resetting ALL players'
    // draw counters at each turn boundary fixes this.
    //
    // Note: spells_cast_this_turn is NOT reset for all players because storm counts spells
    // cast during the storm player's own turn only. Draw tracking (miracle, Sylvan Library)
    // is scoped to "this game turn" for any player who draws.
    let player_ids: Vec<PlayerId> = state.players.keys().copied().collect();
    for pid in player_ids {
        if let Some(p) = state.players.get_mut(&pid) {
            // CR 121.1: per-turn draw count resets at the start of each turn for all players.
            p.cards_drawn_this_turn = 0;
        }
    }
}

// ---------------------------------------------------------------------------
// Combat turn-based actions (M6)
// ---------------------------------------------------------------------------

/// CR 507.1: Initialize combat state at the start of the combat phase.
///
/// Sets up `GameState::combat` so that the combat phase tracking is ready.
/// Called as a turn-based action on entering `BeginningOfCombat`.
fn begin_combat(state: &mut GameState) -> Vec<GameEvent> {
    let active = state.turn.active_player;
    if state.combat.is_none() {
        state.combat = Some(CombatState::new(active));
    }
    Vec::new()
}

/// CR 510: Apply first-strike combat damage (creatures with FirstStrike or DoubleStrike).
///
/// Called as a turn-based action in `Step::FirstStrikeDamage`.
fn first_strike_damage_step(state: &mut GameState) -> Vec<GameEvent> {
    let events = super::combat::apply_combat_damage(state, true);
    if let Some(c) = state.combat.as_mut() {
        c.first_strike_damage_resolved = true;
    }
    events
}

/// CR 510: Apply regular combat damage (creatures without exclusive FirstStrike).
///
/// Called as a turn-based action in `Step::CombatDamage`.
fn combat_damage_step(state: &mut GameState) -> Vec<GameEvent> {
    super::combat::apply_combat_damage(state, false)
}

/// CR 511.1: Clear combat state at the end of the combat phase.
///
/// Called as a turn-based action in `Step::EndOfCombat`.
///
/// CR 702.116a: Before clearing combat state, exile all myriad token copies that
/// were created this combat. These tokens are tagged with `myriad_exile_at_eoc = true`.
/// CR 511.2: "at end of combat" triggers fire as the end of combat step begins,
/// which is modeled here as a turn-based action (no delayed trigger infrastructure
/// needed — the tag on the token is sufficient).
///
/// TODO(M10+): Per CR 702.116a / CR 603.7, the myriad exile is actually a delayed
/// triggered ability created when the myriad trigger resolves, not a turn-based action.
/// As a delayed trigger it would go on the stack at the beginning of the end-of-combat
/// step (CR 511.2), giving players an opportunity to respond (e.g., Stifle to keep the
/// tokens). The current TBA implementation exiles tokens with no interaction window.
/// Refactor to use a proper DelayedTrigger when that infrastructure is expanded (M10+).
fn end_combat(state: &mut GameState) -> Vec<GameEvent> {
    let mut events = Vec::new();

    // CR 702.116a: Exile all myriad tokens. Collect first to avoid borrow issues.
    let myriad_token_ids: Vec<crate::state::game_object::ObjectId> = state
        .objects
        .values()
        .filter(|obj| {
            obj.zone == crate::state::zone::ZoneId::Battlefield
                && obj.is_token
                && obj.myriad_exile_at_eoc
        })
        .map(|obj| obj.id)
        .collect();

    for token_id in myriad_token_ids {
        // Capture controller before moving zone (needed for the exile event).
        let controller = state
            .objects
            .get(&token_id)
            .map(|o| o.controller)
            .unwrap_or(state.turn.active_player);

        if let Ok((new_exile_id, _old)) =
            state.move_object_to_zone(token_id, crate::state::zone::ZoneId::Exile)
        {
            events.push(GameEvent::ObjectExiled {
                player: controller,
                object_id: token_id,
                new_exile_id,
            });
        }
    }

    // CR 702.147a: Sacrifice all creatures that attacked with decayed.
    // Creatures are tagged with `decayed_sacrifice_at_eoc = true` in
    // `handle_declare_attackers` in combat.rs when they attack.
    //
    // Ruling 2021-09-24: "Once a creature with decayed attacks, it will be
    // sacrificed at end of combat, even if it no longer has decayed at that time."
    //
    // CR 701.17a: Sacrifice is NOT destruction — indestructible does not prevent it.
    //
    // TODO(M10+): Per CR 702.147a / CR 603.7, the EOC sacrifice is technically a
    // delayed triggered ability ("sacrifice it at end of combat"). The current TBA
    // implementation sacrifices with no interaction window (can't Stifle the
    // sacrifice). Same caveat as Myriad's EOC exile. Refactor when delayed trigger
    // infrastructure is expanded.
    let decayed_sacrifice_ids: Vec<ObjectId> = state
        .objects
        .values()
        .filter(|obj| {
            obj.zone == crate::state::zone::ZoneId::Battlefield && obj.decayed_sacrifice_at_eoc
        })
        .map(|obj| obj.id)
        .collect();

    for obj_id in decayed_sacrifice_ids {
        let (owner, controller, pre_death_counters) = match state.objects.get(&obj_id) {
            Some(obj) => (obj.owner, obj.controller, obj.counters.clone()),
            None => continue,
        };

        // CR 614: Check replacement effects before moving to graveyard.
        let action = crate::rules::replacement::check_zone_change_replacement(
            state,
            obj_id,
            crate::state::zone::ZoneType::Battlefield,
            crate::state::zone::ZoneType::Graveyard,
            owner,
            &std::collections::HashSet::new(),
        );

        match action {
            crate::rules::replacement::ZoneChangeAction::Redirect {
                to,
                events: repl_events,
                ..
            } => {
                events.extend(repl_events);
                if let Ok((new_id, _old)) = state.move_object_to_zone(obj_id, to) {
                    match to {
                        crate::state::zone::ZoneId::Exile => {
                            events.push(GameEvent::ObjectExiled {
                                player: controller,
                                object_id: obj_id,
                                new_exile_id: new_id,
                            });
                        }
                        crate::state::zone::ZoneId::Command(_) => {
                            // Commander redirected to command zone — no CreatureDied.
                        }
                        _ => {
                            events.push(GameEvent::CreatureDied {
                                object_id: obj_id,
                                new_grave_id: new_id,
                                controller,
                                pre_death_counters,
                            });
                        }
                    }
                }
            }
            crate::rules::replacement::ZoneChangeAction::Proceed => {
                if let Ok((new_id, _old)) =
                    state.move_object_to_zone(obj_id, crate::state::zone::ZoneId::Graveyard(owner))
                {
                    events.push(GameEvent::CreatureDied {
                        object_id: obj_id,
                        new_grave_id: new_id,
                        controller,
                        pre_death_counters,
                    });
                }
            }
            crate::rules::replacement::ZoneChangeAction::ChoiceRequired { .. } => {
                // Multiple replacements — in the absence of full choice infrastructure
                // for TBA context, fall back to Proceed (graveyard).
                if let Ok((new_id, _old)) =
                    state.move_object_to_zone(obj_id, crate::state::zone::ZoneId::Graveyard(owner))
                {
                    events.push(GameEvent::CreatureDied {
                        object_id: obj_id,
                        new_grave_id: new_id,
                        controller,
                        pre_death_counters,
                    });
                }
            }
        }
    }

    state.combat = None;
    events.push(GameEvent::CombatEnded);
    events
}
